{
 "title": "Overview",
 "tags": [ "perf" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" },
   {
    "name": "cpu_count",
    "query": "SELECT\n  cpu_count\nFROM pganalyze.sys_stats\nORDER BY time DESC LIMIT 1"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT 1 AS \"Running\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    'PostgreSQL' AS component,\n    current_setting('server_version') AS version\n\nUNION ALL\n\nSELECT\n    initcap(extname) AS component,\n    extversion AS version\nFROM pg_extension\nWHERE extname LIKE 'timescale%'\nORDER BY component;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  load15 / cpu_count * 100 AS \"CPU (total $cpu_count)\",\n  (mem_total - mem_avail) / mem_total::double precision * 100 AS \"RAM\"\n  FROM pganalyze.sys_stats\n  WHERE $__timeFilter(time)\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "WITH user_hypertables AS (\n    SELECT hypertable_schema,\n           hypertable_name\n    FROM timescaledb_information.hypertables\n    WHERE hypertable_schema NOT LIKE '_timescale%'\n),\nall_chunks AS (\n    SELECT\n        c.hypertable_schema,\n        c.hypertable_name,\n        ch.chunk_name,\n        ch.is_compressed\n    FROM user_hypertables c\n    JOIN timescaledb_information.chunks ch\n      ON ch.hypertable_name = c.hypertable_name\n     AND ch.hypertable_schema = c.hypertable_schema\n),\nchunk_sizes AS (\n    SELECT\n        ac.is_compressed,\n        cds.total_bytes\n    FROM all_chunks ac\n    JOIN LATERAL chunks_detailed_size(ac.hypertable_schema || '.' || ac.hypertable_name) cds\n       ON cds.chunk_name = ac.chunk_name\n)\nSELECT\n    SUM(CASE WHEN is_compressed = false THEN total_bytes ELSE 0 END) AS \"Rowstore\",\n    SUM(CASE WHEN is_compressed = true THEN total_bytes ELSE 0 END) AS \"Columnstore\",\n    SUM(total_bytes) AS \"Storage used\"\nFROM chunk_sizes;\n"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  db_size\nFROM pganalyze.database_stats\nWHERE $__timeFilter(collected_at) \nORDER BY collected_at\n"
    }
   ]
  },
  {
   "title": "Temp files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  temp_files - LAG(temp_files) OVER (ORDER BY collected_at) AS temp_files,\n  temp_bytes - LAG(temp_bytes) OVER (ORDER BY collected_at) AS temp_bytes\nFROM pganalyze.database_stats\nWHERE $__timeFilter(collected_at) \nORDER BY collected_at\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT extract(epoch from current_timestamp - pg_postmaster_start_time()) as \"Uptime\""
    }
   ]
  },
  { "title": "Database KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Queries runtime",
   "type": "timeseries",
   "description": "Average execution time per call",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket(INTERVAL '$__interval', collected_at) AS time,\n\n  -- Average total latency per query (planning + execution)\n  (delta(counter_agg(collected_at, total_plan_time)) +\n   delta(counter_agg(collected_at, total_exec_time)))\n   / NULLIF(delta(counter_agg(collected_at, calls)), 0) AS \"Avg query latency\",\n\n  -- Average I/O time per query (read + write)\n  (delta(counter_agg(collected_at, blk_read_time)) +\n   delta(counter_agg(collected_at, blk_write_time)))\n   / NULLIF(delta(counter_agg(collected_at, calls)), 0) AS \"Avg I/O time\",\n  \n  -- Average rows returned per query\n  delta(counter_agg(collected_at, rows))\n   / NULLIF(delta(counter_agg(collected_at, calls)), 0) AS \"Avg rows per call\"\n\nFROM pganalyze.stat_snapshots\nWHERE $__timeFilter(collected_at)\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Total tuples rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket AS time,\n    (\n        rate(counter_agg(collected_at, tup_inserted)) +\n        rate(counter_agg(collected_at, tup_updated)) +\n        rate(counter_agg(collected_at, tup_deleted)) +\n        rate(counter_agg(collected_at, tup_fetched)) +\n        rate(counter_agg(collected_at, tup_returned))\n    ) AS total_tuples_rate_per_sec\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        tup_inserted,\n        tup_updated,\n        tup_deleted,\n        tup_fetched,\n        tup_returned\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Tuples rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket AS time,\n    rate(counter_agg(collected_at, tup_inserted)) AS inserted,\n    rate(counter_agg(collected_at, tup_updated)) AS updated,\n    rate(counter_agg(collected_at, tup_deleted)) AS deleted,\n    rate(counter_agg(collected_at, tup_fetched)) AS fetched,\n    rate(counter_agg(collected_at, tup_returned)) AS returned\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        tup_inserted,\n        tup_updated,\n        tup_deleted,\n        tup_fetched,\n        tup_returned\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Transactions rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket AS time,\n    rate(counter_agg(collected_at, xact_commit)) AS commits,\n    rate(counter_agg(collected_at, xact_rollback)) AS rollbacks\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        xact_commit,\n        xact_rollback\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Total transactions rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket AS time,\n    (\n        rate(counter_agg(collected_at, xact_commit)) +\n        rate(counter_agg(collected_at, xact_rollback))\n    ) AS total_xact_rate_per_sec\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        xact_commit,\n        xact_rollback\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "I/O block operations",
   "type": "stat",
   "description": "Time spent reading/writing file blocks",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket as time,\n    (\n      delta(counter_agg(collected_at, blk_read_time)) +\n      delta(counter_agg(collected_at, blk_write_time))\n    ) AS blk_io_time_ms\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        blk_read_time,\n        blk_write_time\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Total locks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_locks\nFROM pg_locks\nWHERE database = (SELECT oid FROM pg_database WHERE datname = current_database())"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    bucket as time,\n    (delta(counter_agg(collected_at, blks_hit)))::double precision\n      / NULLIF(\n          delta(counter_agg(collected_at, blks_hit))\n        + delta(counter_agg(collected_at, blks_read)),\n          0\n        ) * 100.0 AS cache_hit_ratio\nFROM (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        collected_at,\n        blks_hit,\n        blks_read\n    FROM pganalyze.database_stats\n    WHERE $__timeFilter(collected_at)\n) sub\nGROUP BY bucket\nORDER BY bucket;\n"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  deadlocks\nFROM pganalyze.database_stats\nORDER BY collected_at\n"
    }
   ]
  }
 ]
}