{
 "title": "Queries",
 "tags": [ "perf" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" },
   { "name": "queryid", "query": "3818243180016244925" },
   {
    "name": "query",
    "query": "WITH per_table_options AS (\n  SELECT\n    n.nspname AS schema,\n    c.relname AS tbl,\n    opt.option_name,\n    opt.option_value\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  CROSS JOIN LATERAL pg_options_to_table(c.reloptions) AS opt\n  WHERE c.relkind = $1 -- only tables\n    AND n.nspname NOT LIKE $2\n),\n\neffective_options AS (\n  SELECT\n    t.schema,\n    t.tbl,\n    COALESCE(MAX(CASE WHEN o.option_name = $3 THEN o.option_value END), $4) AS table_scale_factor,\n    COALESCE(MAX(CASE WHEN o.option_name = $5 THEN o.option_value END), $6) AS table_threshold\n  FROM (\n    SELECT DISTINCT n.nspname AS schema, c.relname AS tbl\n    FROM pg_class c\n    JOIN pg_namespace n ON n.oid = c.relnamespace\n    WHERE c.relkind = $7\n      AND n.nspname NOT SIMILAR TO $8\n  ) t\n  LEFT JOIN per_table_options o ON o.schema = t.schema AND o.tbl = t.tbl\n  GROUP BY t.schema, t.tbl\n),\n\ntable_sizes AS (\n  SELECT \n    t.schemaname AS schema,\n    t.relname AS tbl,\n    CASE \n      WHEN ht.hypertable_name IS NOT NULL THEN hypertable_size(ht.hypertable_schema || $9 || ht.hypertable_name)\n      ELSE pg_total_relation_size(t.schemaname || $10 || t.relname)\n    END AS table_size_bytes\n  FROM pg_stat_user_tables t\n  LEFT JOIN timescaledb_information.hypertables ht\n    ON ht.hypertable_schema = t.schemaname\n   AND ht.hypertable_name = t.relname\n  WHERE t.schemaname NOT LIKE $11\n),\n\nbloat_stats AS (\n  SELECT\n    schema,\n    tbl,\n    SUM(bloat_bytes) AS dead_bytes\n  FROM (\n    -- normal tables\n    SELECT\n      n.nspname AS schema,\n      c.relname AS tbl,\n      (stats.dead_tuple_len   stats.approx_free_space)::numeric AS bloat_bytes\n    FROM pg_class c\n    JOIN pg_namespace n ON n.oid = c.relnamespace\n    CROSS JOIN LATERAL pgstattuple_approx(format($12, n.nspname, c.relname)) AS stats\n    WHERE c.relkind = $13\n      AND n.nspname NOT SIMILAR TO $14\n\n    UNION ALL\n\n    -- hypertable chunks\n    SELECT\n      ch.hypertable_schema AS schema,\n      ch.hypertable_name AS tbl,\n      (stats.dead_tuple_len   stats.approx_free_space)::numeric AS bloat_bytes\n    FROM timescaledb_information.chunks ch\n    CROSS JOIN LATERAL pgstattuple_approx(format($15, ch.chunk_schema, ch.chunk_name)) AS stats\n  ) sub\n  GROUP BY schema, tbl\n),\n\nlast_vacuum AS (\n  SELECT\n    schemaname AS schema,\n    relname AS tbl,\n    last_vacuum,\n    last_autovacuum\n  FROM pg_stat_user_tables\n  WHERE schemaname NOT LIKE $16\n)\n\nSELECT\n  eo.schema AS \"Schema\",\n  eo.tbl AS \"Table\",\n  eo.table_scale_factor AS \"Scale factor\",\n  eo.table_threshold AS \"Threshold\",\n  ts.table_size_bytes AS \"Data size\",\n  bs.dead_bytes AS \"Est. bloat\",\n  ROUND(bs.dead_bytes / NULLIF(ts.table_size_bytes,$17) * $18, $19) AS \"Est. bloat %\",\n  GREATEST(lv.last_vacuum, lv.last_autovacuum) AS \"Last vacuumed\"\nFROM effective_options eo\nLEFT JOIN table_sizes ts ON ts.schema = eo.schema AND ts.tbl = eo.tbl\nLEFT JOIN bloat_stats bs ON bs.schema = eo.schema AND bs.tbl = eo.tbl\nLEFT JOIN last_vacuum lv ON lv.schema = eo.schema AND lv.tbl = eo.tbl\nORDER BY eo.schema, eo.tbl"
   },
   { "name": "plan" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query runtime",
   "type": "timeseries",
   "description": "Per call statistics over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        collected_at,\n        queryid,\n        calls - LAG(calls) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_calls,\n        total_plan_time - LAG(total_plan_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_plan_time,\n        total_exec_time - LAG(total_exec_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_exec_time,\n        blk_read_time - LAG(blk_read_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_blk_read_time,\n        blk_write_time - LAG(blk_write_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_blk_write_time\n    FROM pganalyze.stat_statements\n    WHERE $__timeFilter(collected_at) \n),\nweighted_exec AS (\n    SELECT\n        collected_at,\n        queryid,\n        delta_calls,\n        (delta_plan_time + delta_exec_time) / NULLIF(delta_calls,0) AS weighted_exec_time,\n        (delta_blk_read_time + delta_blk_write_time) AS total_io_time\n    FROM deltas\n)\nSELECT\n    time_bucket(INTERVAL '$__interval', collected_at) AS time,\n    COALESCE(approx_percentile(0.5, percentile_agg(weighted_exec_time)), 0) AS \"Median time\",\n    COALESCE(approx_percentile(0.95, percentile_agg(weighted_exec_time)), 0) AS \"P95 time\",\n    COALESCE(SUM(total_io_time) / NULLIF(SUM(delta_calls),0), 0) AS \"Avg I/O time\"\nFROM weighted_exec\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\n    SELECT\n        userid,\n        queryid,\n        calls - LAG(calls) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_calls,\n        total_plan_time - LAG(total_plan_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_plan_time,\n        total_exec_time - LAG(total_exec_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_exec_time,\n        blk_read_time - LAG(blk_read_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_blk_read_time,\n        blk_write_time - LAG(blk_write_time) OVER (PARTITION BY queryid ORDER BY collected_at) AS delta_blk_write_time\n    FROM pganalyze.stat_statements\n    WHERE $__timeFilter(collected_at)\n),\nagg AS (\n    SELECT\n        userid,\n        queryid,\n        SUM(delta_calls) AS total_calls,\n        SUM(delta_plan_time + delta_exec_time) AS total_exec_time,\n        COALESCE(SUM(delta_blk_read_time + delta_blk_write_time), 0) AS total_io\n    FROM deltas\n    WHERE delta_calls > 0\n    GROUP BY queryid, userid\n)\nSELECT\n    a.queryid::text,\n    q.query AS \"Query\",\n    (a.total_exec_time / NULLIF(a.total_calls,0)) AS \"Avg time\",\n    (a.total_calls / NULLIF((($__to - $__from) / 1000) / 60, 0)) AS \"Calls/min\",\n    (a.total_exec_time / NULLIF(SUM(a.total_exec_time) OVER (),0) * 100) AS \"% of all runtime\",\n    (a.total_io / NULLIF(SUM(a.total_io) OVER (),0) * 100) AS \"% of all I/O\",\n    r.rolname AS \"User\"\nFROM agg a\nJOIN pganalyze.queries q ON q.queryid = a.queryid\nJOIN pg_roles r ON r.oid = a.userid\nORDER BY \"Avg time\" DESC;\n"
    }
   ]
  },
  { "title": "Query performance: #$queryid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH query_range AS (\n  SELECT\n    (MAX(calls) - MIN(calls)) AS calls_delta,\n    (MAX(total_exec_time) - MIN(total_exec_time)) AS total_time_delta,\n    MAX(total_exec_time) AS max_time,\n    (MAX(shared_blks_read) - MIN(shared_blks_read)) AS shared_blks_read_delta,\n    (MAX(local_blks_read) - MIN(local_blks_read)) AS local_blks_read_delta,\n    (MAX(temp_blks_read) - MIN(temp_blks_read)) AS temp_blks_read_delta\n  FROM pganalyze.stat_statements\n  WHERE $__timeFilter(collected_at)\n    AND queryid = $queryid\n)\nSELECT\n  (total_time_delta / NULLIF(calls_delta,0)) AS \"Avg time per call\",\n  (max_time / NULLIF(calls_delta,0)) AS \"Max time per call\",\n  ((shared_blks_read_delta + local_blks_read_delta + temp_blks_read_delta)\n     * current_setting('block_size')::int\n     / NULLIF(calls_delta,0)) AS \"Data read from disk per call\",\n  calls_delta AS \"Total calls\"\nFROM query_range;\n"
    }
   ]
  },
  {
   "title": "Avg time & calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket(INTERVAL '$__interval', collected_at) AS time,\n    delta(counter_agg(collected_at, total_exec_time)) AS \"Total time\",\n    delta(counter_agg(collected_at, blk_read_time + blk_write_time)) AS \"Total I/O time\",\n    delta(counter_agg(collected_at, calls)) AS \"Calls\"\nFROM pganalyze.stat_statements\nWHERE $__timeFilter(collected_at) \n  AND queryid = $queryid  \nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\nSELECT\n    time_bucket(INTERVAL '$__interval', collected_at) AS time,\n    delta(counter_agg(collected_at, shared_blks_hit)) AS delta_shared_blks_hit,\n    delta(counter_agg(collected_at, shared_blks_read)) AS delta_shared_blks_read,\n    delta(counter_agg(collected_at, calls)) AS delta_calls\nFROM pganalyze.stat_statements\nWHERE $__timeFilter(collected_at) \n  AND queryid = $queryid\nGROUP BY time\nORDER BY time\n),\nfiltered AS (\n     SELECT *\n     FROM deltas\n     WHERE delta_calls > 0\n)\n\nSELECT\n  time,\n  \n  -- Calculate % from buffer cache (cache hits)\n  CASE WHEN SUM(delta_shared_blks_hit + delta_shared_blks_read) > 0\n       THEN 100.0 * SUM(delta_shared_blks_hit)::float / SUM(delta_shared_blks_hit + delta_shared_blks_read)\n       ELSE NULL\n  END AS \"Percent from buffer cache\",\n\n  -- % from disk (reads)\n  CASE WHEN SUM(delta_shared_blks_hit + delta_shared_blks_read) > 0\n       THEN 100.0 * SUM(delta_shared_blks_read)::float / SUM(delta_shared_blks_hit + delta_shared_blks_read)\n       ELSE NULL\n  END AS \"Percent from disk\",\n\n  -- Bytes read from disk per call (blocks * 8KB)\n  CASE WHEN SUM(delta_calls) > 0\n       THEN (SUM(delta_shared_blks_read) * 8192)::float / SUM(delta_calls)\n       ELSE NULL\n  END AS \"Bytes read from disk per call\"\n\nFROM filtered\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  { "title": "SQL statement for #$queryid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "type": "text", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 }, "options": { "content": "${query:raw}" } },
  {
   "title": "EXPLAINs: #$queryid [only if duration > 500ms]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "EXPLAIN plans",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"Executed at\",\n  total_cost AS \"Est. cost\",\n  duration AS \"Runtime\",\n  io_read_time AS \"I/O read time\",\n  io_read_time / duration * 100.0 AS \"I/O read time %\",\n  bytes_read AS \"Read from disk\",\n  queryid::text,\n  plan\nFROM\n  pganalyze.stat_explains\nWHERE\n  queryid = $queryid\nORDER BY\n  time DESC"
      }
     ]
    },
    { "title": "Plan", "type": "text", "gridPos": { "h": 15, "w": 13, "x": 0, "y": 54 }, "options": { "content": "$plan" } }
   ]
  }
 ]
}