{
 "title": "Queries",
 "tags": [ "perf" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" },
   { "name": "queryid", "query": "4372641507196789939" },
   {
    "name": "query",
    "query": "WITH bucketed AS (\n    SELECT\n        time_bucket(INTERVAL $1, collected_at) AS bucket,\n        delta(counter_agg(collected_at, calls)) AS delta_calls,\n        delta(counter_agg(collected_at, total_plan_time))  \n        delta(counter_agg(collected_at, total_exec_time)) AS delta_total_time,\n        delta(counter_agg(collected_at, blk_read_time))  \n        delta(counter_agg(collected_at, blk_write_time)) AS delta_total_io\n    FROM pganalyze.stat_statements\n    WHERE collected_at BETWEEN $2 AND $3\n    GROUP BY bucket, queryid\n)\nSELECT\n    bucket AS time,\n    approx_percentile($4, percentile_agg(delta_total_time / NULLIF(delta_calls,$5))) AS \"Median time\",\n    approx_percentile($6, percentile_agg(delta_total_time / NULLIF(delta_calls,$7))) AS \"P95 time\",\n    SUM(delta_total_io) / NULLIF(SUM(delta_calls),$8) AS \"Avg I/O time\"\nFROM bucketed\nWHERE delta_calls > $9\nGROUP BY bucket\nORDER BY bucket"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query runtime",
   "type": "timeseries",
   "description": "Per call statistics over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "tem",
     "rawSql": "WITH bucketed AS (\n    SELECT\n        time_bucket(INTERVAL '$__interval', collected_at) AS bucket,\n        delta(counter_agg(collected_at, calls)) AS delta_calls,\n        delta(counter_agg(collected_at, total_plan_time)) +\n        delta(counter_agg(collected_at, total_exec_time)) AS delta_total_time,\n        delta(counter_agg(collected_at, blk_read_time)) +\n        delta(counter_agg(collected_at, blk_write_time)) AS delta_total_io\n    FROM pganalyze.stat_statements\n    WHERE $__timeFilter(collected_at)\n    GROUP BY bucket, queryid\n)\nSELECT\n    bucket AS time,\n    approx_percentile(0.5, percentile_agg(delta_total_time / NULLIF(delta_calls,0))) AS \"Median time\",\n    approx_percentile(0.95, percentile_agg(delta_total_time / NULLIF(delta_calls,0))) AS \"P95 time\",\n    SUM(delta_total_io) / NULLIF(SUM(delta_calls),0) AS \"Avg I/O time\"\nFROM bucketed\nWHERE delta_calls > 0\nGROUP BY bucket\nORDER BY bucket\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "tem",
     "rawSql": "WITH agg AS (\n    SELECT\n        userid,\n        queryid,\n        delta(counter_agg(collected_at, calls)) AS total_calls,\n        delta(counter_agg(collected_at, total_plan_time)) AS total_plan_time,\n        delta(counter_agg(collected_at, total_exec_time)) AS total_exec_time,\n        delta(counter_agg(collected_at, blk_read_time)) AS total_blk_read_time,\n        delta(counter_agg(collected_at, blk_write_time)) AS total_blk_write_time\n    FROM pganalyze.stat_statements\n    WHERE $__timeFilter(collected_at)\n    GROUP BY queryid, userid\n)\nSELECT\n    a.queryid::text,\n    q.query AS \"Query\",\n    ((a.total_plan_time + a.total_exec_time) / NULLIF(a.total_calls, 0)) AS \"Avg time\",\n    (a.total_calls / NULLIF((($__to - $__from) / 1000) / 60, 0)) AS \"Calls/min\",\n    ((a.total_plan_time + a.total_exec_time) / NULLIF(SUM(a.total_plan_time + a.total_exec_time) OVER (), 0) * 100) AS \"% of all runtime\",\n    ((a.total_blk_read_time + a.total_blk_write_time) / NULLIF(SUM(a.total_blk_read_time + a.total_blk_write_time) OVER (), 0) * 100) AS \"% of all I/O\",\n    r.rolname AS \"User\"\nFROM agg a\nJOIN pganalyze.queries q ON q.queryid = a.queryid\nJOIN pg_roles r ON r.oid = a.userid\nWHERE a.total_calls > 0\nORDER BY \"Avg time\" DESC;"
    }
   ]
  },
  { "title": "Query performance: #$queryid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "WITH query_range AS (\n  SELECT\n    (MAX(calls) - MIN(calls)) AS calls_delta,\n    (MAX(total_exec_time) - MIN(total_exec_time)) AS total_time_delta,\n    MAX(total_exec_time) AS max_time,\n    (MAX(shared_blks_read) - MIN(shared_blks_read)) AS shared_blks_read_delta,\n    (MAX(local_blks_read) - MIN(local_blks_read)) AS local_blks_read_delta,\n    (MAX(temp_blks_read) - MIN(temp_blks_read)) AS temp_blks_read_delta\n  FROM pganalyze.stat_statements\n  WHERE $__timeFilter(collected_at)\n    AND queryid = $queryid\n)\nSELECT\n  (total_time_delta / NULLIF(calls_delta,0)) AS \"Avg time per call\",\n  (max_time / NULLIF(calls_delta,0)) AS \"Max time per call\",\n  ((shared_blks_read_delta + local_blks_read_delta + temp_blks_read_delta)\n     * current_setting('block_size')::int\n     / NULLIF(calls_delta,0)) AS \"Data read from disk per call\",\n  calls_delta AS \"Total calls\"\nFROM query_range;\n"
    }
   ]
  },
  {
   "title": "Avg time & calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket(INTERVAL '$__interval', collected_at) AS time,\n    delta(counter_agg(collected_at, total_exec_time)) AS \"Total time\",\n    delta(counter_agg(collected_at, blk_read_time + blk_write_time)) AS \"Total I/O time\",\n    delta(counter_agg(collected_at, calls)) AS \"Calls\"\nFROM pganalyze.stat_statements\nWHERE $__timeFilter(collected_at) \n  AND queryid = $queryid  \nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH deltas AS (\nSELECT\n    time_bucket(INTERVAL '$__interval', collected_at) AS time,\n    delta(counter_agg(collected_at, shared_blks_hit)) AS delta_shared_blks_hit,\n    delta(counter_agg(collected_at, shared_blks_read)) AS delta_shared_blks_read,\n    delta(counter_agg(collected_at, calls)) AS delta_calls\nFROM pganalyze.stat_statements\nWHERE $__timeFilter(collected_at) \n  AND queryid = $queryid\nGROUP BY time\nORDER BY time\n),\nfiltered AS (\n     SELECT *\n     FROM deltas\n     WHERE delta_calls > 0\n)\n\nSELECT\n  time,\n  \n  -- Calculate % from buffer cache (cache hits)\n  CASE WHEN SUM(delta_shared_blks_hit + delta_shared_blks_read) > 0\n       THEN 100.0 * SUM(delta_shared_blks_hit)::float / SUM(delta_shared_blks_hit + delta_shared_blks_read)\n       ELSE NULL\n  END AS \"Percent from buffer cache\",\n\n  -- % from disk (reads)\n  CASE WHEN SUM(delta_shared_blks_hit + delta_shared_blks_read) > 0\n       THEN 100.0 * SUM(delta_shared_blks_read)::float / SUM(delta_shared_blks_hit + delta_shared_blks_read)\n       ELSE NULL\n  END AS \"Percent from disk\",\n\n  -- Bytes read from disk per call (blocks * 8KB)\n  CASE WHEN SUM(delta_calls) > 0\n       THEN (SUM(delta_shared_blks_read) * 8192)::float / SUM(delta_calls)\n       ELSE NULL\n  END AS \"Bytes read from disk per call\"\n\nFROM filtered\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  { "title": "SQL statement for #$queryid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "type": "text", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 }, "options": { "content": "${query:raw}" } },
  {
   "title": "EXPLAINs: #$queryid [only if duration > 500ms]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "EXPLAIN plans",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"Executed at\",\n  'See details',\n  queryid::text,\n  total_cost AS \"Est. cost\",\n  duration AS \"Runtime\",\n  io_read_time AS \"I/O read time\",\n  io_read_time / duration * 100.0 AS \"I/O read time %\",\n  bytes_read AS \"Read from disk\",\n  plan\nFROM\n  pganalyze.stat_explains\nWHERE\n  queryid = $queryid\nORDER BY\n  time DESC"
    }
   ]
  }
 ]
}