{
 "title": "Schema statistics",
 "tags": [ "perf" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" },
   { "name": "table" },
   { "name": "index" },
   { "name": "schema", "query": "public,uec,pganalyze" }
  ]
 },
 "panels": [
  {
   "title": "Select table to analyze",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  schemaname || '.' || relname AS name,\n  pg_total_relation_size(schemaname || '.' || relname) AS size_bytes\nFROM \n  pg_stat_user_tables\nWHERE schemaname = '$schema'\nORDER BY \n  size_bytes DESC\n"
    }
   ]
  },
  {
   "title": "Table size and columns for $table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n table_bytes + toast_bytes AS \"Data + TOAST size\",\n index_bytes AS \"Size of indexes\",\n total_bytes AS \"Total size\"\nFROM pganalyze.table_stats\nWHERE relid = '$table'::regclass::oid\nORDER BY collected_at DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Size growth",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  table_bytes AS \"Data size\",\n  index_bytes AS \"Index size\",\n  toast_bytes AS \"TOAST size\"\n  --total_bytes AS \"Total size\"\nFROM pganalyze.table_stats\nWHERE relid = '$table'::regclass::oid\nORDER BY collected_at;\n"
    }
   ]
  },
  {
   "title": "Hypertable chunks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH chunk_stats AS (\n  SELECT\n    ch.hypertable_name || '.' || ch.chunk_name AS \"Name\",\n    ch.range_start::text AS \"Start range\",\n    ch.range_end::text AS \"End range\",\n    pg_total_relation_size(quote_ident(ch.chunk_schema) || '.' || quote_ident(ch.chunk_name)) AS \"Size\",\n    CASE\n      WHEN (st.n_live_tup + st.n_dead_tup) = 0 THEN 0\n      ELSE st.n_dead_tup::float / NULLIF((st.n_live_tup + st.n_dead_tup), 0) * 100.0\n    END AS \"Dead rows\"\n  FROM\n    timescaledb_information.chunks ch\n  LEFT JOIN\n    pg_stat_user_tables st ON st.relname = ch.chunk_name\n  WHERE\n    ch.hypertable_schema = split_part('${table}', '.', 1)\n    AND ch.hypertable_name = split_part('${table}', '.', 2)\n)\nSELECT *\nFROM chunk_stats\nORDER BY \"Dead rows\" DESC\n"
    }
   ]
  },
  {
   "title": "Columns",
   "type": "table",
   "description": "Num. distinct (*) means a fraction-based extimate",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  a.attname AS \"Name\",\n  pg_catalog.format_type(a.atttypid, a.atttypmod) AS \"Type\",\n  ROUND((s.null_frac * 100)::numeric, 2) AS \"Null %\",\n  s.avg_width AS \"Avg. size (bytes)\",\n  CASE\n    WHEN s.n_distinct < 0 THEN\n      (ROUND(((-s.n_distinct) * c.reltuples)::numeric)::TEXT || '*')\n    ELSE\n      s.n_distinct::TEXT\n  END AS \"Num. distinct\",\n  CASE\n    WHEN EXISTS (\n      SELECT 1\n      FROM pg_index i\n      WHERE\n        i.indrelid = a.attrelid\n        AND a.attnum = ANY(i.indkey)\n    ) THEN 'yes'\n    ELSE 'no'\n  END AS \"Indexed?\"\nFROM\n  pg_attribute a\n  JOIN pg_class c ON a.attrelid = c.oid\n  JOIN pg_namespace n ON c.relnamespace = n.oid\n  LEFT JOIN pg_stats s ON\n    s.schemaname = n.nspname\n    AND s.tablename = c.relname\n    AND s.attname = a.attname\nWHERE\n  c.oid = '$table'::regclass::oid\n  AND a.attnum > 0\n  AND NOT a.attisdropped\nORDER BY\n  a.attnum;\n"
    }
   ]
  },
  { "title": "Indexes for $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (indexrelid)\n  indexrelid AS \"ID\",\n  indexrelname AS \"Name\",\n  size_bytes AS \"Size\"\nFROM pganalyze.index_stats\nWHERE relid = '$table'::regclass::oid\nORDER BY indexrelid, collected_at DESC;\n"
    }
   ]
  },
  {
   "title": "Index size $index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  size_bytes\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nORDER BY collected_at\n"
    }
   ]
  },
  {
   "title": "Index scans $index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  scan - LAG(scan) OVER (PARTITION BY relid ORDER BY collected_at) AS scans_per_interval\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nORDER BY collected_at\n"
    }
   ]
  },
  {
   "title": "Index hits & reads $index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  CASE \n    WHEN (blks_hit + blks_read) > 0 THEN ROUND(100.0 * blks_hit / (blks_hit + blks_read), 2)\n    ELSE 0\n  END AS \"% From Buffer Cache\",\n  CASE \n    WHEN (blks_hit + blks_read) > 0 THEN ROUND(100.0 * blks_read / (blks_hit + blks_read), 2)\n    ELSE 0\n  END AS \"% From Disk\"\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nORDER BY collected_at\n"
    }
   ]
  },
  { "title": "Vacuum of $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Per table settings",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "WITH per_table_options AS (\n  SELECT\n    opt.option_name,\n    opt.option_value\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  CROSS JOIN LATERAL pg_options_to_table(c.reloptions) AS opt\n  WHERE c.oid = '$table'::regclass::oid\n),\nsettings AS (\n  SELECT\n    name,\n    setting\n  FROM pg_settings\n  WHERE name IN (\n    'autovacuum_vacuum_cost_delay',\n    'autovacuum_vacuum_threshold',\n    'autovacuum_freeze_max_age',\n    'autovacuum_vacuum_insert_threshold',\n    'autovacuum_vacuum_cost_limit',\n    'autovacuum_vacuum_scale_factor',\n    'autovacuum_multixact_freeze_max_age',\n    'autovacuum_vacuum_insert_scale_factor'\n  )\n)\nSELECT\n  s.name,\n  COALESCE(p.option_value, s.setting) AS effective_value\nFROM settings s\nLEFT JOIN per_table_options p ON p.option_name = s.name\nORDER BY s.name"
    }
   ]
  },
  {
   "title": "Table vacuums",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"Finished at\",\n  duration AS \"Duration\",\n  tuples_removed AS \"Tuples removed\",\n  tuples_removed / (tuples_removed + tuples_remain) * 100.0 AS \"Effectiveness\",\n  wraparound AS \"Anti-wraparound?\",\n  details AS \"Details\"\nFROM pganalyze.vacuum_stats\nWHERE datname = current_database()\n  AND (schemaname || '.' || tablename) = '$table'\n  AND $__timeFilter(started_at)\nORDER BY finished_at DESC\n"
    }
   ]
  },
  {
   "title": "Dead rows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "WITH settings AS (\n  SELECT\n    c.oid,\n    c.relname,\n    COALESCE(\n      MAX(CASE WHEN optname = 'autovacuum_vacuum_threshold' THEN optvalue::int END),\n      (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_vacuum_threshold')\n    ) AS vacuum_threshold,\n    COALESCE(\n      MAX(CASE WHEN optname = 'autovacuum_vacuum_scale_factor' THEN optvalue::float END),\n      (SELECT setting::float FROM pg_settings WHERE name = 'autovacuum_vacuum_scale_factor')\n    ) AS vacuum_scale_factor\n  FROM pg_class c\n  LEFT JOIN LATERAL pg_options_to_table(c.reloptions) AS opt(optname, optvalue) ON true\n  WHERE c.oid = '$table'::regclass::oid\n  GROUP BY c.oid, c.relname\n)\nSELECT \n  ts.collected_at AS time,\n  ts.num_dead_rows AS dead_rows,\n  (s.vacuum_threshold + s.vacuum_scale_factor * c.reltuples) AS threshold\nFROM pganalyze.table_stats ts\nJOIN settings s ON ts.relid = s.oid\nJOIN pg_class c ON c.oid = ts.relid\nWHERE ts.relid = '$table'::regclass::oid\n  AND $__timeFilter(ts.collected_at)\nORDER BY ts.collected_at"
    }
   ]
  },
  {
   "title": "Oldest unfrozen XID age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "rawSql": "WITH threshold AS (\n  SELECT\n    c.oid AS relid,\n    COALESCE(\n      (SELECT option_value::int\n       FROM pg_options_to_table(c.reloptions) opt\n       WHERE opt.option_name = 'autovacuum_freeze_max_age'),\n      (SELECT setting::int\n       FROM pg_settings\n       WHERE name = 'autovacuum_freeze_max_age')\n    ) AS freeze_max_age\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  WHERE n.nspname NOT LIKE '\\_timescaledb%'\n    AND c.relkind IN ('r','p')\n)\nSELECT\n  ts.collected_at AS time,\n  ts.frozen_xid_age,\n  t.freeze_max_age AS threshold\nFROM pganalyze.table_stats ts\nJOIN threshold t ON t.relid = ts.relid\nWHERE ts.relid = '$table'::regclass::oid\n  AND $__timeFilter(ts.collected_at)\nORDER BY ts.collected_at"
    }
   ]
  }
 ]
}