{
 "title": "Schema statistics",
 "tags": [ "perf" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" },
   { "name": "table" },
   { "name": "index" },
   { "name": "index_name" },
   { "name": "schema", "query": "public,uec,pganalyze" }
  ]
 },
 "panels": [
  {
   "title": "Total objects",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH all_tables AS (\n    SELECT 'Hypertables' AS type, h.hypertable_schema || '.' || h.hypertable_name AS name\n    FROM timescaledb_information.hypertables h\n\n    UNION ALL\n\n    SELECT 'PostgreSQL tables' AS type, t.table_schema || '.' || t.table_name AS name\n    FROM information_schema.tables t\n    WHERE t.table_type = 'BASE TABLE'\n      AND t.table_schema NOT IN (\n          'pg_catalog', 'information_schema',\n          '_timescaledb_catalog', '_timescaledb_internal'\n      )\n      AND NOT EXISTS (\n          SELECT 1\n          FROM timescaledb_information.hypertables h\n          WHERE h.hypertable_schema = t.table_schema\n            AND h.hypertable_name = t.table_name\n      )\n),\n\ncontinuous_aggregates AS (\n    SELECT 'Continuous aggregates' AS type, c.view_schema || '.' || c.view_name AS name\n    FROM timescaledb_information.continuous_aggregates c\n),\n\nmaterialized_views AS (\n    SELECT 'Materialized views' AS type, m.schemaname || '.' || m.matviewname AS name\n    FROM pg_matviews m\n)\n\nSELECT type, COUNT(*) AS total\nFROM (\n    SELECT * FROM all_tables\n    UNION ALL\n    SELECT * FROM continuous_aggregates\n    UNION ALL\n    SELECT * FROM materialized_views\n) t\nGROUP BY type\nORDER BY total DESC"
    }
   ]
  },
  {
   "title": "Select table to analyze",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    t.tablename AS name,\n    CASE \n        WHEN ht.hypertable_name IS NOT NULL THEN hypertable_size(ht.hypertable_schema || '.' || ht.hypertable_name)\n        ELSE pg_total_relation_size(t.schemaname || '.' || t.tablename)\n    END AS size_bytes\nFROM pg_tables t\nLEFT JOIN timescaledb_information.hypertables ht\n    ON ht.hypertable_schema = t.schemaname\n   AND ht.hypertable_name = t.tablename\nWHERE t.schemaname = '$schema'\nORDER BY size_bytes DESC;\n"
    }
   ]
  },
  {
   "title": "Table size and columns for $table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    ts.table_bytes + ts.toast_bytes AS \"Data + TOAST size\",\n    ts.index_bytes AS \"Size of indexes\",\n    ts.table_bytes + ts.index_bytes + ts.toast_bytes AS \"Total size\",\n    approximate_row_count(format('%I.%I', '$schema', '$table')::regclass) AS \"Approx row count\"\nFROM pganalyze.table_stats ts\nWHERE ts.relid = format('%I.%I', '$schema', '$table')::regclass::oid\nORDER BY ts.collected_at DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Size growth",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  table_bytes AS \"Data size\",\n  index_bytes AS \"Index size\",\n  toast_bytes AS \"TOAST size\"\nFROM pganalyze.table_stats\nWHERE relid = format('%I.%I', '$schema', '$table')::regclass::oid\n  AND $__timeFilter(collected_at) \n"
    }
   ]
  },
  {
   "title": "Hypertable options",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    ht.num_chunks AS \"Chunks\",\n    d.time_interval AS \"Chunk time interval\",\n    ht.compression_enabled AS \"Compression\"\nFROM timescaledb_information.dimensions d\nJOIN timescaledb_information.hypertables ht ON ht.hypertable_schema = d.hypertable_schema AND ht.hypertable_name = d.hypertable_name\nWHERE ht.hypertable_schema = '$schema'\n    AND ht.hypertable_name = '$table'\n"
    }
   ]
  },
  {
   "title": "Hypertable chunks",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    c.chunk_name AS \"Name\",\n    (cds).total_bytes AS \"Size\",\n    (cds).index_bytes AS \"Index size\",\n    c.is_compressed AS \"Compressed\",\n    c.range_start::text AS \"Start time\",\n    c.range_end::text   AS \"End time\"\nFROM timescaledb_information.chunks c\nJOIN LATERAL chunks_detailed_size('$schema' || '.' || '$table') AS cds ON cds.chunk_name = c.chunk_name\nWHERE c.hypertable_schema = '$schema'\n    AND c.hypertable_name = '$table'\nORDER BY range_end DESC;\n"
    }
   ]
  },
  {
   "title": "Columns",
   "type": "table",
   "description": "Num. distinct (*) means a fraction-based extimate",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n    a.attname AS \"Name\",\n    pg_catalog.format_type(a.atttypid, a.atttypmod) AS \"Type\",\n    COALESCE(ROUND((s.null_frac * 100)::numeric, 2), 0) AS \"Null %\",\n    COALESCE(s.avg_width, 0) AS \"Avg. size (bytes)\",\n    CASE\n        WHEN s.n_distinct IS NULL THEN 'n/a'\n        WHEN s.n_distinct < 0 THEN\n            (ROUND(((-s.n_distinct) * c.reltuples)::numeric)::TEXT || '*')\n        ELSE\n            s.n_distinct::TEXT\n    END AS \"Num. distinct\",\n    CASE\n        WHEN EXISTS (\n            SELECT 1\n            FROM pg_index i\n            WHERE\n                i.indrelid = a.attrelid\n                AND a.attnum = ANY(i.indkey)\n        ) THEN 'yes'\n        ELSE 'no'\n    END AS \"Indexed?\"\nFROM\n    pg_attribute a\n    JOIN pg_class c ON a.attrelid = c.oid\n    JOIN pg_namespace n ON c.relnamespace = n.oid\n    LEFT JOIN pg_stats s ON\n        s.schemaname = n.nspname\n        AND s.tablename = c.relname\n        AND s.attname = a.attname\nWHERE\n    n.nspname = '$schema'\n    AND c.relname = '$table'\n    AND a.attnum > 0\n    AND NOT a.attisdropped\nORDER BY\n    a.attnum;\n"
    }
   ]
  },
  { "title": "Indexes for $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH index_list AS (\n    SELECT DISTINCT ON (i.indexrelid)\n        i.indexrelid AS index_id,\n        c.relname    AS index_name,\n        i.size_bytes AS size_bytes\n    FROM pganalyze.index_stats i\n    JOIN pg_class c ON c.oid = i.indexrelid\n    WHERE i.relid = format('%I.%I', '$schema', '$table')::regclass::oid\n    ORDER BY i.indexrelid, i.collected_at DESC\n)\nSELECT\n    il.index_id   AS \"ID\",\n    il.index_name AS \"Name\",\n    am.amname || ' (' || string_agg(pg_get_indexdef(il.index_id, k + 1, true), ', ') || ')' AS \"Definition\",\n    CASE\n        WHEN ix.indisprimary THEN 'PRIMARY KEY'\n        WHEN ix.indisunique  THEN 'UNIQUE'\n        ELSE NULL\n    END AS \"Constraint\",\n    il.size_bytes AS \"Size\"\nFROM index_list il\nJOIN pg_index ix ON ix.indexrelid = il.index_id\nJOIN pg_am am    ON am.oid = (SELECT relam FROM pg_class WHERE oid = il.index_id)\nCROSS JOIN LATERAL generate_subscripts(ix.indkey, 1) AS k\nGROUP BY il.index_id, il.index_name, il.size_bytes, am.amname, ix.indisprimary, ix.indisunique\nORDER BY il.index_id;\n"
    }
   ]
  },
  {
   "title": "Index size: $index_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  size_bytes\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nAND $__timeFilter(collected_at) \n"
    }
   ]
  },
  {
   "title": "Index scans: $index_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  scan - LAG(scan) OVER (PARTITION BY relid ORDER BY collected_at) AS scans_per_interval\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nAND $__timeFilter(collected_at) "
    }
   ]
  },
  {
   "title": "Index hits & reads: $index_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  collected_at AS time,\n  CASE \n    WHEN (blks_hit + blks_read) > 0 THEN ROUND(100.0 * blks_hit / (blks_hit + blks_read), 2)\n    ELSE 0\n  END AS \"% From Buffer Cache\",\n  CASE \n    WHEN (blks_hit + blks_read) > 0 THEN ROUND(100.0 * blks_read / (blks_hit + blks_read), 2)\n    ELSE 0\n  END AS \"% From Disk\"\nFROM pganalyze.index_stats\nWHERE indexrelid = $index\nAND $__timeFilter(collected_at) \n"
    }
   ]
  },
  { "title": "Vacuum of $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Per table settings",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "WITH per_table_options AS (\n  SELECT\n    opt.option_name,\n    opt.option_value\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  CROSS JOIN LATERAL pg_options_to_table(c.reloptions) AS opt\n  WHERE c.oid = format('%I.%I', '$schema', '$table')::regclass::oid\n),\nsettings AS (\n  SELECT\n    name,\n    setting\n  FROM pg_settings\n  WHERE name IN (\n    'autovacuum_vacuum_cost_delay',\n    'autovacuum_vacuum_threshold',\n    'autovacuum_freeze_max_age',\n    'autovacuum_vacuum_insert_threshold',\n    'autovacuum_vacuum_cost_limit',\n    'autovacuum_vacuum_scale_factor',\n    'autovacuum_multixact_freeze_max_age',\n    'autovacuum_vacuum_insert_scale_factor'\n  )\n)\nSELECT\n  s.name,\n  COALESCE(p.option_value, s.setting) AS effective_value\nFROM settings s\nLEFT JOIN per_table_options p ON p.option_name = s.name\nORDER BY s.name"
    }
   ]
  },
  {
   "title": "Table vacuums",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"Finished at\",\n  finished_at-started_at AS \"Duration\",\n  tuples_removed AS \"Tuples removed\",\n  tuples_removed / (tuples_removed + tuples_remain) * 100.0 AS \"Effectiveness\",\n  wraparound AS \"Anti-wraparound?\",\n  '' AS \"Chunk\",\n  regexp_replace(\n    details,\n    '^automatic vacuum of table \"[^\"]+\": ',\n    ''\n) AS \"Details\"\nFROM pganalyze.vacuum_stats\nWHERE relid = format('%I.%I', '$schema', '$table')::regclass::oid\n  AND $__timeFilter(started_at)\nORDER BY finished_at DESC\n"
    },
    {
     "dataset": "tem",
     "rawSql": "SELECT\n  finished_at AS \"Finished at\",\n  finished_at-started_at AS \"Duration\",\n  tuples_removed AS \"Tuples removed\",\n  tuples_removed / (tuples_removed + tuples_remain) * 100.0 AS \"Effectiveness\",\n  wraparound AS \"Anti-wraparound?\",\n  c.chunk_name AS \"Chunk\",\n  regexp_replace(\n    details,\n    '^automatic vacuum of table \"[^\"]+\": ',\n    ''\n) AS \"Details\"\nFROM pganalyze.vacuum_stats v\nJOIN timescaledb_information.chunks c\n  ON v.relid = (c.chunk_schema || '.' || c.chunk_name)::regclass::oid\nWHERE c.hypertable_schema = '$schema'\n  AND c.hypertable_name = '$table'\n  AND $__timeFilter(v.started_at)\nORDER BY finished_at DESC\n"
    }
   ]
  },
  {
   "title": "Dead rows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "WITH settings AS (\n  SELECT\n    c.oid,\n    c.relname,\n    COALESCE(\n      MAX(CASE WHEN optname = 'autovacuum_vacuum_threshold' THEN optvalue::int END),\n      (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_vacuum_threshold')\n    ) AS vacuum_threshold,\n    COALESCE(\n      MAX(CASE WHEN optname = 'autovacuum_vacuum_scale_factor' THEN optvalue::float END),\n      (SELECT setting::float FROM pg_settings WHERE name = 'autovacuum_vacuum_scale_factor')\n    ) AS vacuum_scale_factor\n  FROM pg_class c\n  LEFT JOIN LATERAL pg_options_to_table(c.reloptions) AS opt(optname, optvalue) ON true\n  WHERE c.oid = format('%I.%I', '$schema', '$table')::regclass::oid\n  GROUP BY c.oid, c.relname\n)\nSELECT \n  ts.collected_at AS time,\n  ts.num_dead_rows AS dead_rows,\n  (s.vacuum_threshold + s.vacuum_scale_factor * c.reltuples)::int AS threshold\nFROM pganalyze.table_stats ts\nJOIN settings s ON ts.relid = s.oid\nJOIN pg_class c ON c.oid = ts.relid\nWHERE ts.relid = format('%I.%I', '$schema', '$table')::regclass::oid\n  AND $__timeFilter(ts.collected_at)"
    }
   ]
  },
  {
   "title": "Oldest unfrozen XID age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "rawSql": "WITH threshold AS (\n  SELECT\n    c.oid AS relid,\n    COALESCE(\n      (SELECT option_value::int\n       FROM pg_options_to_table(c.reloptions) opt\n       WHERE opt.option_name = 'autovacuum_freeze_max_age'),\n      (SELECT setting::int\n       FROM pg_settings\n       WHERE name = 'autovacuum_freeze_max_age')\n    ) AS freeze_max_age\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  WHERE n.nspname NOT LIKE '\\_timescaledb%'\n    AND c.relkind IN ('r','p')\n)\nSELECT\n  ts.collected_at AS time,\n  ts.frozen_xid_age,\n  t.freeze_max_age AS threshold\nFROM pganalyze.table_stats ts\nJOIN threshold t ON t.relid = ts.relid\nWHERE ts.relid = format('%I.%I', '$schema', '$table')::regclass::oid\n  AND $__timeFilter(ts.collected_at)"
    }
   ]
  }
 ]
}