{
 "title": "VACUUM analysis",
 "tags": [ "perf" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Config settings",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "  SELECT\n    name,\n    setting\n  FROM pg_settings\n  WHERE name IN (\n    'autovacuum_max_workers',\n    'autovacuum_vacuum_cost_delay',\n    'autovacuum_vacuum_threshold',\n    'autovacuum_freeze_max_age',\n    'autovacuum_vacuum_insert_threshold',\n    'autovacuum_vacuum_cost_limit',\n    'autovacuum_vacuum_scale_factor',\n    'autovacuum_multixact_freeze_max_age',\n    'autovacuum_vacuum_insert_scale_factor',\n    'autovacuum_naptime',\n    'autovacuum_work_mem'\n  )"
    }
   ]
  },
  {
   "title": "Total autovacuum count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Total\",\n  COUNT(*) FILTER (WHERE wraparound) AS \"Anti-wraparound vacuums\"\nFROM pganalyze.vacuum_stats\nWHERE $__timeFilter(started_at)\n"
    }
   ]
  },
  {
   "title": "VACUUM summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  schemaname || '.' || tablename AS \"Table\",\n  COUNT(*) AS \"Vacuum count\",\n  SUM(tuples_removed) || ' (' || ROUND(SUM(tuples_removed) / NULLIF(SUM(tuples_removed + tuples_remain), 0) * 100.0, 2) || '%)' AS \"Tuples removed\",\n  SUM(index_scans) AS \"Index scans\",\n  SUM(pages_removed) AS \"Pages removed\",\n  MAX(duration) AS \"Max duration\",\n  MAX(finished_at) AS \"Last vacuum\"\nFROM pganalyze.vacuum_stats\nWHERE $__timeFilter(started_at)\nGROUP BY schemaname, tablename\nORDER BY \"Tuples removed\" DESC\n"
    }
   ]
  },
  {
   "title": "Anti-Wraparound Vacuum Frequency",
   "type": "stat",
   "description": "How often an Anti-Wraparound VACUUM is estimated to be scheduled on average from all tables - this is a function of the rate of transaction ID consumption, as well as the autovacuum_freeze_max_age and vacuum_freeze_min_age settings. Higher values are better.",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    c.oid,\n    (c.relfrozenxid::text)::bigint AS relfrozenxid_int,\n    txid_current() AS current_xid,\n    (SELECT setting::bigint FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') AS freeze_max_age,\n    (SELECT setting::bigint FROM pg_settings WHERE name = 'vacuum_freeze_min_age') AS freeze_min_age,\n    ((d.xact_commit + d.xact_rollback) / NULLIF(EXTRACT(EPOCH FROM (now() - COALESCE(d.stats_reset, pg_postmaster_start_time()) )), 0)) AS xid_per_sec\n  FROM pg_class c\n  CROSS JOIN pg_stat_database d\n  WHERE d.datname = current_database()\n    AND c.relkind = 'r'\n)\nSELECT\n  AVG(\n    CASE\n      WHEN xid_per_sec > 0 THEN (freeze_min_age / xid_per_sec) / 3600 -- hours\n      ELSE NULL\n    END\n  ) AS avg_anti_wraparound_vacuum_frequency_hours\nFROM params;\n"
    }
   ]
  },
  {
   "title": "Max read I/O impact",
   "type": "stat",
   "description": "Theoretical maximum impact that VACUUM can have on your system",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH settings AS (\n  SELECT\n    (CASE \n       WHEN (SELECT setting FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_limit') = '-1'\n       THEN (SELECT setting::numeric FROM pg_settings WHERE name = 'vacuum_cost_limit')\n       ELSE (SELECT setting::numeric FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_limit')\n     END) AS vacuum_cost_limit_effective,\n    (SELECT setting::numeric FROM pg_settings WHERE name = 'vacuum_cost_page_miss') AS vacuum_cost_page_miss,\n    (SELECT setting::numeric FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_delay') AS autovacuum_vacuum_cost_delay,\n    8192 AS block_size_bytes -- 8kB block size\n)\nSELECT\n  (vacuum_cost_limit_effective / vacuum_cost_page_miss * block_size_bytes / autovacuum_vacuum_cost_delay) * 1000 AS max_vacuum_read_rate_bytes_per_sec\nFROM settings\n"
    }
   ]
  },
  {
   "title": "Max write I/O impact",
   "type": "stat",
   "description": "Theoretical maximum impact that VACUUM can have on your system",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH settings AS (\n  SELECT\n    (CASE \n       WHEN (SELECT setting FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_limit') = '-1'\n       THEN (SELECT setting::numeric FROM pg_settings WHERE name = 'vacuum_cost_limit')\n       ELSE (SELECT setting::numeric FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_limit')\n     END) AS vacuum_cost_limit_effective,\n    (SELECT setting::numeric FROM pg_settings WHERE name = 'vacuum_cost_page_dirty') AS vacuum_cost_page_dirty,\n    (SELECT setting::numeric FROM pg_settings WHERE name = 'autovacuum_vacuum_cost_delay') AS autovacuum_vacuum_cost_delay,\n    8192 AS block_size_bytes -- 8kB block size\n)\nSELECT\n  (vacuum_cost_limit_effective / vacuum_cost_page_dirty * block_size_bytes / autovacuum_vacuum_cost_delay) * 1000 AS max_vacuum_write_rate_bytes_per_sec\nFROM settings\n"
    }
   ]
  },
  { "title": "Bloat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Est. Table Bloat",
   "type": "stat",
   "description": "The estimated overall table bloat on this server or database - this is a very rough estimate and should be reviewed for individual tables. Only tables > 64kB are considered",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH tables AS (\n  SELECT schemaname, tablename\n  FROM pg_tables\n  WHERE schemaname NOT SIMILAR TO '(pg_catalog|information_schema|_timescaledb%)'\n),\nbloat_data AS (\n  SELECT\n    stats.table_len,\n    (stats.dead_tuple_len + stats.approx_free_space)::numeric AS bloat_bytes,\n    ((stats.dead_tuple_len + stats.approx_free_space)::numeric / NULLIF(stats.table_len, 0)) AS bloat_ratio\n  FROM tables t,\n  LATERAL pgstattuple_approx(format('%I.%I', t.schemaname, t.tablename)) stats\n  WHERE stats.table_len >= 65536 -- 64kb min\n)\nSELECT\n  COALESCE(SUM(bloat_bytes), 0) AS total_bloat,\n  COALESCE(ROUND(100.0 * AVG(bloat_ratio), 2), 0) AS avg_bloat_percent\nFROM bloat_data\nWHERE bloat_ratio IS NOT NULL;\n"
    }
   ]
  },
  {
   "title": "Total tables",
   "type": "stat",
   "description": "The total number of tables on this database - databases with a lot of tables can often times suffer from more autovacuum scheduling challenges.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_tables\nFROM pg_tables\nWHERE schemaname NOT SIMILAR TO '(pg_catalog|information_schema|_timescaledb%)'\n"
    }
   ]
  },
  {
   "title": "Xmin Horizon Assigned",
   "type": "stat",
   "description": "How long ago the xmin horizon was assigned, indicating up to which point VACUUM can clean up dead rows.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH xmin_candidates AS (\n  SELECT\n    COALESCE((\n      SELECT\n        CASE WHEN COALESCE(pg_catalog.age(backend_xid), 0) > COALESCE(pg_catalog.age(backend_xmin), 0)\n          THEN backend_xid::text::bigint\n          ELSE backend_xmin::text::bigint\n        END\n      FROM pg_catalog.pg_stat_activity\n      WHERE backend_xmin IS NOT NULL OR backend_xid IS NOT NULL\n      ORDER BY greatest(pg_catalog.age(backend_xmin), pg_catalog.age(backend_xid)) DESC\n      LIMIT 1\n    ), 0) AS backend,\n\n    COALESCE((\n      SELECT xmin::text::bigint\n      FROM pg_catalog.pg_replication_slots\n      WHERE xmin IS NOT NULL\n      ORDER BY pg_catalog.age(xmin) DESC\n      LIMIT 1\n    ), 0) AS replication_slot_xmin,\n\n    COALESCE((\n      SELECT catalog_xmin::text::bigint\n      FROM pg_catalog.pg_replication_slots\n      WHERE catalog_xmin IS NOT NULL\n      ORDER BY pg_catalog.age(catalog_xmin) DESC\n      LIMIT 1\n    ), 0) AS replication_slot_catalog_xmin,\n\n    COALESCE((\n      SELECT transaction::text::bigint\n      FROM pg_catalog.pg_prepared_xacts\n      ORDER BY pg_catalog.age(transaction) DESC\n      LIMIT 1\n    ), 0) AS prepare_xact,\n\n    COALESCE((\n      SELECT backend_xmin::text::bigint\n      FROM pg_catalog.pg_stat_replication\n      WHERE backend_xmin IS NOT NULL\n      ORDER BY pg_catalog.age(backend_xmin) DESC\n      LIMIT 1\n    ), 0) AS standby\n),\ntrue_xmin AS (\n  SELECT\n    LEAST(\n      backend,\n      replication_slot_xmin,\n      replication_slot_catalog_xmin,\n      prepare_xact,\n      standby\n    ) AS xmin\n  FROM xmin_candidates\n),\ntxn_rate AS (\n  SELECT\n    EXTRACT(epoch FROM (now() - COALESCE(stats_reset, pg_postmaster_start_time()))) AS seconds_since_startup,\n    (xact_commit + xact_rollback) AS total_txns,\n    CASE \n      WHEN (xact_commit + xact_rollback) > 0\n      THEN EXTRACT(epoch FROM (now() - COALESCE(stats_reset, pg_postmaster_start_time()))) / (xact_commit + xact_rollback)\n      ELSE NULL\n    END AS seconds_per_txn\n  FROM pg_stat_database\n  WHERE datname = current_database()\n)\nSELECT\n  CASE WHEN seconds_per_txn IS NOT NULL\n       THEN (txid_current() - xmin) * seconds_per_txn\n       ELSE NULL\n  END AS approx_seconds_ago\nFROM true_xmin CROSS JOIN txn_rate;\n"
    }
   ]
  },
  {
   "title": "Table bloat info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH per_table_options AS (\n  SELECT\n    n.nspname AS schema,\n    c.relname AS table,\n    opt.option_name,\n    opt.option_value\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  CROSS JOIN LATERAL pg_options_to_table(c.reloptions) AS opt\n  WHERE c.relkind = 'r' -- only tables\n    AND n.nspname NOT LIKE '\\_timescaledb%'\n),\n\nsettings AS (\n  SELECT\n    name,\n    setting\n  FROM pg_settings\n  WHERE name IN (\n    'autovacuum_vacuum_threshold',\n    'autovacuum_vacuum_scale_factor'\n  )\n),\n\neffective_options AS (\n  SELECT\n    t.schema,\n    t.table,\n    MAX(CASE WHEN o.option_name = 'autovacuum_vacuum_scale_factor' THEN o.option_value END) AS table_scale_factor,\n    MAX(CASE WHEN o.option_name = 'autovacuum_vacuum_threshold' THEN o.option_value END) AS table_threshold\n  FROM (\n    SELECT DISTINCT n.nspname AS schema, c.relname AS table\n    FROM pg_class c\n    JOIN pg_namespace n ON n.oid = c.relnamespace\n    WHERE c.relkind = 'r'\n      AND n.nspname NOT SIMILAR TO '(pg_catalog|information_schema|_timescaledb%)'\n  ) t\n  LEFT JOIN per_table_options o ON o.schema = t.schema AND o.table = t.table\n  GROUP BY t.schema, t.table\n),\n\ntable_sizes AS (\n  SELECT \n  schemaname AS schema,\n  relname AS table,\n  pg_total_relation_size(schemaname || '.' || relname) AS table_size_bytes\nFROM \n  pg_stat_user_tables\nWHERE schemaname NOT LIKE '\\_timescaledb%'\n),\n\n-- estimated bloat (approximate, using pgstattuple_approx)\nbloat_stats AS (\n  SELECT\n    n.nspname AS schema,\n    c.relname AS table,\n    stats.approx_free_space AS free_bytes,\n    stats.approx_tuple_len AS live_bytes,\n    stats.dead_tuple_len AS dead_bytes,\n    stats.approx_free_percent AS free_percent,\n    stats.dead_tuple_percent AS dead_percent\n  FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n  CROSS JOIN LATERAL pgstattuple_approx(format('%I.%I', n.nspname, c.relname)) AS stats\n  WHERE c.relkind = 'r'\n    AND n.nspname NOT SIMILAR TO '(pg_catalog|information_schema|_timescaledb%)'\n\n),\n\nlast_vacuum AS (\n  SELECT\n    schemaname AS schema,\n    relname AS table,\n    last_vacuum,\n    last_autovacuum\n  FROM pg_stat_user_tables\n  WHERE schemaname NOT LIKE '\\_timescaledb%'\n)\n\nSELECT\n  eo.schema AS \"Schema\",\n  eo.table AS \"Table\",\n  COALESCE(eo.table_scale_factor, '[default]') AS \"Scale factor\",\n  COALESCE(eo.table_threshold, '[default]') AS \"Threshold\",\n  ts.table_size_bytes AS \"Data size\",\n  bs.dead_bytes AS \"Est. bloat\",\n  bs.dead_percent AS \"Est. bloat %\",\n  GREATEST(lv.last_vacuum, lv.last_autovacuum) AS \"Last vacuumed\"\nFROM effective_options eo\nLEFT JOIN table_sizes ts ON ts.schema = eo.schema AND ts.table = eo.table\nLEFT JOIN bloat_stats bs ON bs.schema = eo.schema AND bs.table = eo.table\nLEFT JOIN last_vacuum lv ON lv.schema = eo.schema AND lv.table = eo.table\nORDER BY eo.schema, eo.table\n"
    }
   ]
  },
  { "title": "Freezing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Transaction ID Allocation",
   "type": "stat",
   "description": "The rate of transaction IDs that are allocated per minute, as averaged over the last 24 hours. Higher allocation rates generally mean more freezing will be required.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(\n    ((xact_commit + xact_rollback) / (LEAST(EXTRACT(EPOCH FROM now() - COALESCE(stats_reset, pg_postmaster_start_time())), 24 * 3600) / 60.0))::numeric,\n    2\n  ) AS txn_id_allocation_per_minute_24h_avg\nFROM pg_stat_database\nWHERE datname = current_database()\n"
    }
   ]
  },
  {
   "title": "Approaching Transaction ID Wraparound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH threshold AS (\n  SELECT setting::bigint AS \"autovacuum_freeze_max_age\"\n  FROM pg_settings\n  WHERE name ='autovacuum_freeze_max_age'\n)\n\nSELECT\n  collected_at AS time,\n  frozen_xid_age,\n  (SELECT autovacuum_freeze_max_age FROM threshold) AS autovacuum_freeze_max_age\nFROM pganalyze.database_stats\nORDER BY collected_at"
    }
   ]
  },
  {
   "title": "Approaching Multixact ID Wraparound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH threshold AS (\n  SELECT setting::bigint AS \"autovacuum_multixact_freeze_max_age\"\n  FROM pg_settings\n  WHERE name ='autovacuum_multixact_freeze_max_age'\n)\n\nSELECT\n  collected_at AS time,\n  frozen_mxid_age,\n  (SELECT autovacuum_multixact_freeze_max_age FROM threshold) AS autovacuum_multixact_freeze_max_age\nFROM pganalyze.database_stats\nORDER BY collected_at"
    }
   ]
  },
  {
   "title": "Transaction ID Utilization",
   "type": "stat",
   "description": "How much transaction ID space is utilized among the actual maximum available transaction IDs, in percent.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(100.0 * age(datfrozenxid) / 4294967296, 4) AS xid_utilization_percent\nFROM pg_database\nWHERE datname = current_database()"
    }
   ]
  }
 ]
}