CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pgstattuple;

CREATE TABLE IF NOT EXISTS schema_info (
    version int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- public schema
CREATE TABLE IF NOT EXISTS instruments (
                                           id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           instrument TEXT NOT NULL UNIQUE,
                                           serial INTEGER NOT NULL UNIQUE,
                                           model TEXT NOT NULL,
                                           name TEXT NOT NULL,
                                           template TEXT NOT NULL,
                                           server inet,
                                           ds_version TEXT
);

CREATE TABLE IF NOT EXISTS enumerations (
                                            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            instrument_id INTEGER NOT NULL REFERENCES instruments(id),
                                            enum_id INTEGER NOT NULL,
                                            enum TEXT NOT NULL,
                                            name TEXT NOT NULL,
                                            value INTEGER NOT NULL,
                                            UNIQUE (instrument_id, enum, value)
);

CREATE INDEX ON enumerations (instrument_id, enum, value);

CREATE TABLE IF NOT EXISTS parameters (
                                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          instrument_id INTEGER NOT NULL REFERENCES instruments(id),
                                          param_id INTEGER NOT NULL,
                                          subsystem TEXT NOT NULL,
                                          component TEXT NOT NULL,
                                          param_name TEXT NOT NULL,
                                          display_name TEXT NOT NULL,
                                          display_unit TEXT,
                                          storage_unit TEXT,
                                          display_scale TEXT,
                                          enum_id INTEGER,
                                          value_type TEXT NOT NULL,
                                          is_active BOOLEAN DEFAULT TRUE,
                                          UNIQUE (instrument_id, param_id)
);

CREATE INDEX ON parameters (instrument_id, param_id);

CREATE TABLE IF NOT EXISTS data (
                                    time TIMESTAMPTZ NOT NULL,
                                    instrument_id INTEGER NOT NULL REFERENCES instruments(id),
                                    param_id INTEGER NOT NULL,
                                    value_num DOUBLE PRECISION,
                                    value_text TEXT,
                                    UNIQUE (time, instrument_id, param_id)
);

CREATE INDEX ON data (instrument_id, param_id, time ASC);

SELECT create_hypertable(
               'data',
               time_column_name := 'time',
               partitioning_column := 'instrument_id',
               number_partitions := :TBL_DATA_PARTITIONS,
               chunk_time_interval := INTERVAL :TBL_DATA_CHUNK_INTERVAL,
               if_not_exists := TRUE
       );

ALTER TABLE data
    SET (
        timescaledb.compress,
        timescaledb.compress_orderby = 'time DESC',
        timescaledb.compress_segmentby = 'instrument_id, param_id'
        );

SELECT add_compression_policy('data', INTERVAL :TBL_DATA_COMPRESSION);

GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana;

-- uec schema
CREATE SCHEMA IF NOT EXISTS uec;
CREATE TABLE IF NOT EXISTS uec.error_definitions (
                                                     error_definition_id INTEGER NOT NULL,
                                                     subsystem_id INTEGER NOT NULL,
                                                     subsystem TEXT NOT NULL,
                                                     device_type_id INTEGER NOT NULL,
                                                     device_type TEXT NOT NULL,
                                                     device_instance_id INTEGER NOT NULL,
                                                     device_instance TEXT NOT NULL,
                                                     error_code_id INTEGER NOT NULL,
                                                     error_code TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_error_def_id ON uec.error_definitions (error_definition_id);

CREATE TABLE IF NOT EXISTS uec.errors (
                                          time TIMESTAMPTZ NOT NULL,
                                          instrument_id INTEGER NOT NULL REFERENCES public.instruments(id),
                                          error_id INTEGER NOT NULL REFERENCES uec.error_definitions(error_definition_id),
                                          message_text TEXT,
                                          UNIQUE (time, instrument_id, error_id)
);
CREATE INDEX ON uec.errors (instrument_id, time ASC);

GRANT USAGE ON SCHEMA uec TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA uec TO grafana;
ALTER DEFAULT PRIVILEGES IN SCHEMA uec GRANT SELECT ON TABLES TO grafana;

-- set schema version
INSERT INTO schema_info (version) VALUES (1);
