{
 "title": "Fleet overview",
 "description": "General overview of all systems",
 "tags": [
  "overview",
  "sem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Beam time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instrument",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH combined AS (\n    SELECT day, state, seconds\n    FROM sem_beamtime_daily\n    WHERE instrument_id = $instrument \n    AND $__timeFilter(day)\n\n    UNION ALL\n\n    SELECT\n        day,\n        'Unknown' AS state,\n        GREATEST(86400 - SUM(seconds), 0) AS seconds\n    FROM sem_beamtime_daily\n    WHERE instrument_id = $instrument \n    AND $__timeFilter(day)\n    GROUP BY day\n)\nSELECT\n    state,\n    SUM(seconds) AS duration_seconds,\n    ROUND(100.0 * SUM(seconds) / NULLIF(SUM(SUM(seconds)) OVER (), 0), 2) AS percentage\nFROM combined\nGROUP BY state\nORDER BY percentage DESC\n"
    }
   ]
  },
  { "title": "Ion source lifetime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "repeat": "instrument",
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT instrument_id, param_id\n  FROM parameters\n  WHERE instrument_id IN ($instrument)\n    AND component = 'FIB'\n    AND param_name IN ('SourceAgeParameter', 'OperatingTimeFIBParameter')\n),\n\nfiltered AS (\n  SELECT\n    d.time,\n    d.value_num AS operate_time,\n    lag(d.value_num) OVER (ORDER BY time) AS prev_value\n  FROM data d\n  JOIN counter_param p USING (instrument_id, param_id)\n),\n\nlast_replacement AS (\n  SELECT time\n  FROM filtered\n  WHERE operate_time < prev_value   -- counter reset\n  ORDER BY time DESC\n  LIMIT 1\n),\n\nlast_value AS (\n  SELECT last(operate_time, time) AS source_age\n  FROM filtered\n)\n\nSELECT\n  lv.source_age / 3600 AS \"Source age\",\n  lr.time AS \"Last replacement\"\nFROM last_value lv\nLEFT JOIN last_replacement lr ON true\n"
    }
   ]
  },
  { "title": "Last cryo cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    param_name,\n    enum_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument \n    AND param_name LIKE '%TemperatureState'\n    AND subsystem LIKE '%TemperatureControl'\n),\nstate_enum AS (\n  SELECT\n    p.param_id,\n    e.value AS cryocycle\n  FROM\n    state_param p\n    JOIN enum_values e ON e.enum_id = p.enum_id\n  WHERE\n    e.member_name = 'CryoCycle'\n),\nautoloader_states AS (\n  SELECT\n    sp.param_id,\n    sp.param_name,\n    st.state,\n    st.start_time,\n    st.end_time\n  FROM\n    state_param sp\n    CROSS JOIN LATERAL (\n      SELECT\n        state,\n        start_time,\n        end_time\n      FROM\n        state_int_timeline(\n          (\n            SELECT\n              state_agg(d.time, d.value_num :: bigint)\n            FROM\n              data d\n            WHERE\n              d.instrument_id = $instrument \n              AND d.param_id = sp.param_id\n          )\n        )\n    ) AS st\n),\ncryo_cycles AS (\n  SELECT\n    r.param_name,\n    r.start_time,\n    r.end_time,\n    EXTRACT(EPOCH FROM(r.end_time - r.start_time)) AS total_duration\n  FROM\n    autoloader_states r\n    JOIN state_enum se USING (param_id)\n  WHERE\n    r.state = se.cryocycle\n    AND (r.end_time - r.start_time) > INTERVAL '0 second'\n  ORDER BY r.start_time\n)\nSELECT DISTINCT ON (param_name)\n  param_name,\n  CURRENT_DATE - start_time::date AS days_since_cryocycle_start\nFROM cryo_cycles\nORDER BY param_name, start_time DESC;\n"
    },
    {
     "rawSql": "WITH params AS (\n    SELECT param_id\n    FROM parameters\n    WHERE instrument_id = $instrument \n      AND subsystem = 'Options'\n      AND component = 'Thermometers'\n      AND param_name LIKE 'ExperimentalThermometerCryoShieldTemperature'\n),\n\nstate_series AS (\n    SELECT\n        state_agg(\n            d.time,\n            (d.value_num > 0)::int\n        ) AS agg\n    FROM data d\n    JOIN params p ON p.param_id = d.param_id\n    WHERE d.instrument_id = $instrument \n),\n\ncryo_cycles AS (\n    SELECT\n        start_time,\n        end_time\n    FROM state_series,\n    LATERAL state_int_timeline(agg)\n    WHERE state = 1\n    ORDER BY start_time\n)\n\nSELECT CURRENT_DATE - start_time::date AS days_since_cryocycle_start\nFROM cryo_cycles\nORDER BY start_time DESC\nLIMIT 1\n"
    }
   ]
  },
  { "title": "GIS usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "targets": [
    {
     "rawSql": "WITH gis_params AS (\n  SELECT\n    instrument_id,\n    param_id,\n    component AS port\n  FROM parameters\n  WHERE instrument_id IN ($instrument)\n    AND subsystem = 'GISes'\n    AND param_name LIKE 'GIS%ValveOpenTimeParameter'\n)\n\n    SELECT\n        port,\n        last(value_num, time)/3600.0 AS gis_usage\n    FROM data d\n    JOIN gis_params p USING (instrument_id, param_id)\n    WHERE $__timeFilter(time) \n    GROUP BY port\n"
    }
   ]
  },
  {
   "title": "Specimen throughput (Arctis only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Autogrid loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cartridge_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON i.id = lcd.instrument_id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  {
   "title": "Cassette loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cassette_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON lcd.instrument_id = i.id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  }
 ]
}