{
 "title": "Fleet overview",
 "description": "General overview of all systems",
 "tags": [
  "overview",
  "sem"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Beam time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instrument",
   "type": "piechart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total AS (\n  SELECT SUM(seconds) AS total_seconds\n  FROM vacuum_state_daily\n  WHERE $__timeFilter(day)\n    AND instrument_id = $instrument\n)\nSELECT\n  v.state,\n  SUM(v.seconds) AS duration_seconds,\n  ROUND(100.0 * SUM(v.seconds) / NULLIF(t.total_seconds, 0), 2) AS percentage\nFROM vacuum_state_daily v\nCROSS JOIN total t\nWHERE $__timeFilter(v.day)\n  AND v.instrument_id = $instrument\nGROUP BY v.state, t.total_seconds\nORDER BY percentage DESC;\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$instrument",
   "type": "gauge",
   "description": "Average amount of time EPU or Tomo  acquisition is running ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH total AS (\n  SELECT\n    (SELECT EXTRACT(EPOCH FROM SUM(running_duration))\n     FROM epu_running_daily\n     WHERE instrument_id = $instrument\n       AND $__timeFilter(time)) AS total_epu_seconds,\n    (SELECT EXTRACT(EPOCH FROM SUM(running_duration))\n     FROM tomo_running_daily\n     WHERE instrument_id = $instrument\n       AND $__timeFilter(time)) AS total_tomo_seconds\n)\nSELECT\n  ROUND(COALESCE(total_epu_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS epu_utilization_percent,\n  ROUND(COALESCE(total_tomo_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS tomo_utilization_percent\nFROM total;\n"
    }
   ]
  },
  { "title": "Last cryo cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    param_name,\n    enum_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument \n    AND param_name LIKE '%TemperatureState'\n    AND subsystem LIKE '%TemperatureControl'\n),\nstate_enum AS (\n  SELECT\n    p.param_id,\n    e.value AS cryocycle\n  FROM\n    state_param p\n    JOIN enum_values e ON e.enum_id = p.enum_id\n  WHERE\n    e.member_name = 'CryoCycle'\n),\nautoloader_states AS (\n  SELECT\n    sp.param_id,\n    sp.param_name,\n    st.state,\n    st.start_time,\n    st.end_time\n  FROM\n    state_param sp\n    CROSS JOIN LATERAL (\n      SELECT\n        state,\n        start_time,\n        end_time\n      FROM\n        state_int_timeline(\n          (\n            SELECT\n              state_agg(d.time, d.value_num :: bigint)\n            FROM\n              data d\n            WHERE\n              d.instrument_id = $instrument \n              AND d.param_id = sp.param_id\n          )\n        )\n    ) AS st\n),\ncryo_cycles AS (\n  SELECT\n    r.param_name,\n    r.start_time,\n    r.end_time,\n    EXTRACT(EPOCH FROM(r.end_time - r.start_time)) AS total_duration\n  FROM\n    autoloader_states r\n    JOIN state_enum se USING (param_id)\n  WHERE\n    r.state = se.cryocycle\n    AND (r.end_time - r.start_time) > INTERVAL '0 second'\n  ORDER BY r.start_time\n)\nSELECT DISTINCT ON (param_name)\n  param_name,\n  CURRENT_DATE - start_time::date AS days_since_cryocycle_start\nFROM cryo_cycles\nORDER BY param_name, start_time DESC;\n"
    },
    {
     "rawSql": "WITH params AS (\n    SELECT param_id\n    FROM parameters\n    WHERE instrument_id = $instrument \n      AND subsystem = 'Options'\n      AND component = 'Thermometers'\n      AND param_name LIKE 'ExperimentalThermometerCryoShieldTemperature'\n),\n\nflagged AS (\n    SELECT\n        d.time,\n        d.value_num AS temp,\n        CASE WHEN d.value_num > 0 THEN 1 ELSE 0 END AS is_positive\n    FROM data d\n    JOIN params p ON p.param_id = d.param_id\n    WHERE d.instrument_id = $instrument \n      AND $__timeFilter(d.time)\n),\n\ngrouped AS (\n    SELECT\n        *,\n        ROW_NUMBER() OVER (ORDER BY time) \n        - ROW_NUMBER() OVER (PARTITION BY is_positive ORDER BY time) AS grp\n    FROM flagged\n),\n\ncryo_cycles AS (\nSELECT\n    MIN(time) AS start_time,\n    MAX(time) AS end_time,\n    MAX(time)-MIN(time) AS duration\nFROM grouped\nWHERE is_positive = 1\nGROUP BY grp\nORDER BY start_time\n)\n\nSELECT CURRENT_DATE - start_time::date AS days_since_cryocycle_start\nFROM cryo_cycles\nORDER BY start_time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Specimen throughput (Arctis only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Autogrid loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cartridge_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON i.id = lcd.instrument_id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  {
   "title": "Cassette loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cassette_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON lcd.instrument_id = i.id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  }
 ]
}