{
 "title": "Module | FLM",
 "tags": [
  "module",
  "sem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is for Arctis only!"
   }
  },
  {
   "title": "Filter type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    enum_id\n  FROM\n    parameters p\n  WHERE\n    p.instrument_id = $instrument\n    AND p.param_name = 'FilterSwitcherFilterType'\n    AND p.subsystem = 'FLM'\n),\n\nstate_enum AS (\n  SELECT\n    p.param_id,\n    e.member_name,\n    e.value\n  FROM\n    enum_values e\n    JOIN state_param p USING (enum_id)\n),\n\nstates AS (\n  SELECT\n    state,\n    duration\n  FROM\n    toolkit_experimental.into_int_values((\n        SELECT\n          toolkit_experimental.compact_state_agg(d.time, d.value_num :: bigint) AS agg\n        FROM\n          data d\n        JOIN state_param p USING (param_id)\n        WHERE\n          d.instrument_id = $instrument\n          AND $__timeFilter(d.time)\n      ))\n)\n\nSELECT\n  e.member_name AS state,\n  EXTRACT(EPOCH FROM s.duration) AS duration\nFROM\n  states s\n  JOIN state_enum e ON e.value = s.state\n  "
    }
   ]
  },
  {
   "title": "Light source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    enum_id\n  FROM\n    parameters p\n  WHERE\n    p.instrument_id = $instrument\n    AND p.param_name = 'LightSourceLEDColor'\n    AND p.subsystem = 'FLM'\n),\n\nstate_enum AS (\n  SELECT\n    p.param_id,\n    e.member_name,\n    e.value\n  FROM\n    enum_values e\n    JOIN state_param p USING (enum_id)\n),\n\nstates AS (\n  SELECT\n    state,\n    duration\n  FROM\n    toolkit_experimental.into_int_values((\n        SELECT\n          toolkit_experimental.compact_state_agg(d.time, d.value_num :: bigint) AS agg\n        FROM\n          data d\n        JOIN state_param p USING (param_id)\n        WHERE\n          d.instrument_id = $instrument\n          AND $__timeFilter(d.time)\n      ))\n)\n\nSELECT\n  e.member_name AS state,\n  EXTRACT(EPOCH FROM s.duration) AS duration\nFROM\n  states s\n  JOIN state_enum e ON e.value = s.state\n  "
    }
   ]
  },
  {
   "title": "Last errors for Objective lens",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "WITH matching_params AS (\n  SELECT param_id, param_name, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument \n  AND component = 'RetractableObjective'\n  AND param_name LIKE 'Retractable%State'\n  AND subsystem = 'FLM'\n),\n\nerror_states AS (\n  SELECT p.param_id, p.param_name, e.member_name, e.value\n  FROM enum_values e\n  JOIN matching_params p USING (enum_id)\n  WHERE e.member_name IN ('OverTemperature', 'PositionerFault', 'PowerSupplyOverload', 'PowerSupplyFailure', 'Error')\n)\n\nSELECT\n  d.time AS \"Time\",\n  e.param_name AS \"Component\",\n  e.member_name AS \"Error\"\nFROM data d\nJOIN error_states e ON e.param_id = d.param_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument \n  AND $__timeFilter(d.time)\nORDER BY d.time DESC\n"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AreaScanCamera",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id, enum_id\n  FROM parameters p\n  WHERE instrument_id = $instrument\n    AND subsystem = 'FluorescenceMicroscope'\n    AND param_name = 'OpticalMicroscopeStateParameter'\n),\n\noffline_state AS (\n  SELECT p.param_id, e.value\n  FROM enum_values e\n  JOIN matching_param p USING (enum_id)\n  WHERE e.member_name = 'Offline'\n)\n\nSELECT\n  d.time,\n  d.value_num\nFROM\n  data d\n  JOIN offline_state oe ON oe.param_id = d.param_id\n    AND d.value_num = oe.value\nWHERE\n  instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY\n  d.time\n"
    }
   ]
  },
  {
   "title": "FilterExchanger",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id, enum_id\n  FROM parameters p\n  WHERE instrument_id = $instrument\n    AND subsystem = 'FLM'\n    AND component = 'FilterExchanger'\n    AND param_name = 'FilterSwitcherFaultState'\n),\n\nnoerror_state AS (\n  SELECT p.param_id, e.value\n  FROM enum_values e\n  JOIN matching_param p USING (enum_id)\n  WHERE e.member_name = 'None'\n)\n\nSELECT\n  d.time,\n  d.value_num\nFROM\n  data d\n  JOIN noerror_state ns ON ns.param_id = d.param_id\n    AND d.value_num != ns.value\nWHERE\n  instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY\n  d.time\n"
    }
   ]
  }
 ]
}