{
 "title": "Module | FLM",
 "tags": [
  "module",
  "sem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is for Arctis only!"
   }
  },
  {
   "title": "Filter type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_agg AS (\n  SELECT\n    p.enum_id,\n    toolkit_experimental.compact_state_agg(\n        d.time,\n        d.value_num::bigint\n    ) AS agg\n  FROM data d\n  JOIN parameters p USING (instrument_id, param_id)\n  WHERE d.instrument_id = $instrument \n    AND p.param_name = 'FilterSwitcherFilterType'\n    AND p.subsystem = 'FLM'\n    AND $__timeFilter(d.time)\n  GROUP BY p.enum_id\n)\n\nSELECT\n  ev.member_name AS state,\n  EXTRACT(EPOCH FROM s.duration) AS duration\nFROM state_agg sa\nCROSS JOIN LATERAL toolkit_experimental.into_int_values(sa.agg) s\nJOIN enum_values ev\n  ON ev.enum_id = sa.enum_id\n AND ev.value = s.state\nORDER BY ev.member_name"
    }
   ]
  },
  {
   "title": "Light source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_agg AS (\n  SELECT\n    p.enum_id,\n    toolkit_experimental.compact_state_agg(\n        d.time,\n        d.value_num::bigint\n    ) AS agg\n  FROM data d\n  JOIN parameters p USING (instrument_id, param_id)\n  WHERE d.instrument_id = $instrument \n    AND p.param_name = 'LightSourceLEDColor'\n    AND p.subsystem = 'FLM'\n    AND $__timeFilter(d.time)\n  GROUP BY p.enum_id\n)\n\nSELECT\n  ev.member_name AS state,\n  EXTRACT(EPOCH FROM s.duration) AS duration\nFROM state_agg sa\nCROSS JOIN LATERAL toolkit_experimental.into_int_values(sa.agg) s\nJOIN enum_values ev\n  ON ev.enum_id = sa.enum_id\n AND ev.value = s.state\nORDER BY ev.member_name"
    }
   ]
  },
  {
   "title": "Last errors for Objective lens",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.time AS \"Time\",\n    p.param_name AS \"Component\",\n    e.member_name AS \"Error\"\nFROM data d\nJOIN parameters p\n    ON p.param_id = d.param_id\n    AND p.instrument_id = $instrument\n    AND p.component = 'RetractableObjective'\n    AND p.param_name LIKE 'Retractable%State'\n    AND p.subsystem = 'FLM'\nJOIN enum_values e\n    ON e.enum_id = p.enum_id\n    AND e.value = d.value_num\n    AND e.member_name IN (\n        'OverTemperature',\n        'PositionerFault',\n        'PowerSupplyOverload',\n        'PowerSupplyFailure',\n        'Error'\n    )\nWHERE $__timeFilter(d.time)\nORDER BY d.time DESC"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AreaScanCamera",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.time,\n    d.value_num\nFROM data d\nJOIN parameters p \n    ON p.param_id = d.param_id\nJOIN enum_values e \n    ON e.enum_id = p.enum_id\n   AND e.value = d.value_num -- capture offline = 3\nWHERE p.instrument_id = $instrument\n  AND p.subsystem = 'FluorescenceMicroscope'\n  AND p.param_name = 'OpticalMicroscopeStateParameter'\n  AND e.member_name = 'Offline'\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
    }
   ]
  },
  {
   "title": "FilterExchanger",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    d.time,\n    d.value_num\nFROM data d\nJOIN parameters p \n    ON p.param_id = d.param_id\nJOIN enum_values e \n    ON e.enum_id = p.enum_id\n   AND e.value != d.value_num -- capture only error codes. No value = 99 = ON\nWHERE p.instrument_id = $instrument\n  AND p.subsystem = 'FLM'\n  AND p.param_name = 'FilterSwitcherFaultState'\n  AND e.member_name = 'None'\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
    }
   ]
  }
 ]
}