{
 "title": "Module | Source",
 "tags": [
  "module",
  "sem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  { "title": "Electron Gun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FEG Operate time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FEG'\n    AND param_name = 'OperateTimeFEGParameter'\n)\n\nSELECT d.value_num AS \"OperationTimeCounter\"\nFROM data d\nJOIN counter_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time) \nORDER BY d.time DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "IGP spikes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id, param_name\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name IN ('I-Column.IGP1_PeakCount', 'I-Column.IGP2_PeakCount')\n    AND subsystem = 'Vacuum'\n)\nSELECT\n  p.param_name,\n  MAX(d.value_num) - MIN(d.value_num) AS counts\nFROM data d\nJOIN state_param p USING (param_id)\nWHERE instrument_id = $instrument \n  AND $__timeFilter(d.time)\nGROUP BY p.param_name"
    }
   ]
  },
  {
   "title": "IGP1 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS time,\n  param_name,\n  mean_value AS \"1-hour average\"\nFROM sem_pressure_hourly\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'E-Column.IGP1'\n  AND $__timeFilter(hour)\nORDER BY hour"
    },
    {
     "rawSql": "SELECT\n  day AS time,\n  param_name,\n  mean_value AS \"24-hour average\"\nFROM sem_pressure_daily\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'E-Column.IGP1'\n  AND $__timeFilter(day)\nORDER BY day"
    }
   ]
  },
  {
   "title": "FEG states",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH cagg AS (\n  SELECT\n    p.enum_id,\n    state_agg(d.time, d.value_num :: int) AS agg\n  FROM\n    data d\n    JOIN parameters p USING (instrument_id, param_id)\n  WHERE\n    d.instrument_id = $instrument \n    AND $__timeFilter(d.time)\n    AND p.param_name = 'ExternalStateParameter'\n    AND p.component = 'FEG'\n  GROUP BY\n    p.enum_id\n)\nSELECT\n  ev.member_name AS state,\n  COUNT(*) AS interval_count\nFROM\n  cagg\n  CROSS JOIN LATERAL state_int_timeline(agg) s\n  JOIN enum_values ev ON ev.enum_id = cagg.enum_id AND ev.value = s.state\nGROUP BY\n  ev.member_name\nORDER BY\n  ev.member_name"
    }
   ]
  },
  {
   "title": "IGP2 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS time,\n  param_name,\n  mean_value AS \"1-hour average\"\nFROM sem_pressure_hourly\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'E-Column.IGP2'\n  AND $__timeFilter(hour)\nORDER BY hour"
    },
    {
     "rawSql": "SELECT\n  day AS time,\n  param_name,\n  mean_value AS \"24-hour average\"\nFROM sem_pressure_daily\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'E-Column.IGP2'\n  AND $__timeFilter(day)\nORDER BY day"
    }
   ]
  },
  {
   "title": "Emission current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'FEG'\n    AND param_name = 'EmissionFEGParameter'\n)\n\nSELECT\n  time,\n  value\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (SELECT param_id FROM matching_param)\n    AND $__timeFilter(time)\n))\nORDER BY 1;\n"
    }
   ]
  },
  { "title": "Ion Gun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "IGP spikes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id, param_name\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name IN ('I-Column.IGP3_PeakCount', 'I-Column.IGP4_PeakCount')\n    AND subsystem = 'Vacuum'\n)\nSELECT\n  p.param_name,\n  MAX(d.value_num) - MIN(d.value_num) AS counts\nFROM data d\nJOIN state_param p USING (param_id)\nWHERE instrument_id = $instrument \n  AND $__timeFilter(d.time)\nGROUP BY p.param_name"
    }
   ]
  },
  {
   "title": "IGP3 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS time,\n  param_name,\n  mean_value AS \"1-hour average\"\nFROM sem_pressure_hourly\nWHERE\n  instrument_id = $instrument\n  AND param_name IN ('IGP3Parameter', 'I-Column.IGP3')\n  AND $__timeFilter(hour)\nORDER BY hour"
    },
    {
     "rawSql": "SELECT\n  day AS time,\n  param_name,\n  mean_value AS \"24-hour average\"\nFROM sem_pressure_daily\nWHERE\n  instrument_id = $instrument\n  AND param_name IN ('IGP3Parameter', 'I-Column.IGP3')\n  AND $__timeFilter(day)\nORDER BY day"
    }
   ]
  },
  {
   "title": "PFIB gas usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT instrument_id, param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name LIKE 'GasUsage_%Parameter'\n),\n\ntotals AS (\n  SELECT\n    substring(p.param_name FROM '^GasUsage_(.+)Parameter$') AS gas_type,\n    delta(counter_agg(d.time, d.value_num)) AS total_usage\n  FROM data d\n  JOIN params p USING (instrument_id, param_id)\n  WHERE $__timeFilter(d.time)\n  GROUP BY p.param_name\n)\n\nSELECT\n  gas_type,\n  total_usage,\n  total_usage * 100.0\n    / NULLIF(SUM(total_usage) OVER (), 0) AS pct_of_total\nFROM totals\nORDER BY pct_of_total DESC\n"
    }
   ]
  },
  {
   "title": "LMIS/PFIB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT instrument_id, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name IN ('SourceAgeParameter', 'OperatingTimeFIBParameter')\n),\n\nfiltered AS (\n  SELECT\n    d.time,\n    d.value_num AS operate_time\n  FROM data d\n  JOIN counter_param p USING (instrument_id, param_id)\n),\n\nchanges AS (\n  SELECT\n    time,\n    operate_time,\n    lag(operate_time) OVER (ORDER BY time) AS prev_value\n  FROM filtered\n),\n\nlast_replacement AS (\n  SELECT time\n  FROM changes\n  WHERE operate_time < prev_value   -- counter reset\n  ORDER BY time DESC\n  LIMIT 1\n),\n\nlast_value AS (\n  SELECT last(operate_time, time) AS source_age\n  FROM filtered\n)\n\nSELECT\n  lv.source_age / 3600 AS \"Source age\",\n  lr.time AS \"Last replacement\"\nFROM last_value lv\nLEFT JOIN last_replacement lr ON true\n"
    }
   ]
  },
  {
   "title": "LMIS heat cycles / PFIB ignition count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT d.value_num\nFROM data d\nJOIN parameters p\n  ON d.param_id = p.param_id\nWHERE p.instrument_id = $instrument\n  AND p.component = 'FIB'\n  AND p.param_name IN ('TotalLifetimeHeatsParameter', 'TotalIgnitionCountParameter')\nORDER BY d.time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "LMIS emission current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name = 'EmissionFIBParameter'\n)\n\nSELECT\n  time,\n  value\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (SELECT param_id FROM matching_param)\n    AND $__timeFilter(time)\n))\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "IGP4 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hour AS time,\n  param_name,\n  mean_value AS \"1-hour average\"\nFROM sem_pressure_hourly\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'IGP4Parameter'\n  AND $__timeFilter(hour)\nORDER BY hour"
    },
    {
     "rawSql": "SELECT\n  day AS time,\n  param_name,\n  mean_value AS \"24-hour average\"\nFROM sem_pressure_daily\nWHERE\n  instrument_id = $instrument\n  AND param_name = 'IGP4Parameter'\n  AND $__timeFilter(day)\nORDER BY day"
    }
   ]
  },
  {
   "title": "PFIB jacket water flow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  average(stats_agg(d.value_num)) AS avg_flow\nFROM\n  data d\n  JOIN parameters p USING (instrument_id, param_id)\nWHERE\n  d.instrument_id = $instrument \n  AND $__timeFilter(d.time)\n  AND p.component = 'FIB'\n  AND p.param_name = 'JacketFlowParameter'"
    }
   ]
  },
  {
   "title": "PFIB ignition ratio (last week)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH latest_week AS (\n  SELECT time_bucket('1 week', max(d.time)) AS bucket\n  FROM data d\n  JOIN parameters p\n    ON d.instrument_id = p.instrument_id\n   AND d.param_id = p.param_id\n  WHERE p.instrument_id = $instrument \n    AND p.component = 'FIB'\n    AND p.param_name IN ('SuccessfulIgnitionCountParameter', 'TotalIgnitionCountParameter')\n    AND $__timeFilter(d.time)\n)\n\nSELECT\n  COALESCE(NULLIF(delta(counter_agg(d.time, d.value_num) FILTER (WHERE p.param_name = 'SuccessfulIgnitionCountParameter')), 0), 1)::float\n  /\n  COALESCE(NULLIF(delta(counter_agg(d.time, d.value_num) FILTER (WHERE p.param_name = 'TotalIgnitionCountParameter')), 0), 1) AS ratio\n\nFROM data d\nJOIN parameters p\n  ON d.instrument_id = p.instrument_id\n AND d.param_id = p.param_id\nJOIN latest_week lw\n  ON time_bucket('1 week', d.time) = lw.bucket\nWHERE p.instrument_id = $instrument \n  AND p.component = 'FIB'\n  AND p.param_name IN ('SuccessfulIgnitionCountParameter', 'TotalIgnitionCountParameter')\n"
    }
   ]
  }
 ]
}