{
 "title": "Module | Column",
 "tags": [
  "module",
  "sem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg cryo cycle duration",
   "type": "stat",
   "description": "For Aquilos, we calculate the time periods when the temperature is above 0C",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    enum_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name = 'ColumnTemperatureState'\n    AND subsystem = 'ColumnTemperatureControl'\n),\nstate_enum AS (\n  SELECT\n    p.param_id,\n    e.value AS cryocycle\n  FROM\n    state_param p\n    JOIN enum_values e ON e.enum_id = p.enum_id\n  WHERE\n    e.member_name = 'CryoCycle'\n),\nautoloader_states AS (\n  SELECT\n    sp.param_id,\n    st.state,\n    st.start_time,\n    st.end_time\n  FROM\n    state_param sp\n    CROSS JOIN LATERAL (\n      SELECT\n        state,\n        start_time,\n        end_time\n      FROM\n        state_int_timeline(\n          (\n            SELECT\n              state_agg(d.time, d.value_num :: bigint)\n            FROM\n              data d\n            WHERE\n              d.instrument_id = $instrument\n              AND d.param_id = sp.param_id\n          )\n        )\n    ) AS st\n)\n\n  SELECT\n    r.start_time,\n    r.end_time,\n    EXTRACT(EPOCH FROM(r.end_time - r.start_time)) AS total_duration\n  FROM\n    autoloader_states r\n    JOIN state_enum se USING (param_id)\n  WHERE\n    r.state = se.cryocycle\n    AND (r.end_time - r.start_time) > INTERVAL '0 second'\n  ORDER BY\n    r.start_time\n"
    },
    {
     "rawSql": "WITH params AS (\n    SELECT param_id\n    FROM parameters\n    WHERE instrument_id = $instrument \n      AND subsystem = 'Options'\n      AND component = 'Thermometers'\n      AND param_name LIKE 'ExperimentalThermometerCryoShieldTemperature'\n),\n\nflagged AS (\n    SELECT\n        d.time,\n        d.value_num AS temp,\n        CASE WHEN d.value_num > 0 THEN 1 ELSE 0 END AS is_positive\n    FROM data d\n    JOIN params p ON p.param_id = d.param_id\n    WHERE d.instrument_id = $instrument \n      AND $__timeFilter(d.time)\n),\n\ngrouped AS (\n    SELECT\n        *,\n        ROW_NUMBER() OVER (ORDER BY time) \n        - ROW_NUMBER() OVER (PARTITION BY is_positive ORDER BY time) AS grp\n    FROM flagged\n),\n\ncryo_cycles AS (\nSELECT\n    MIN(time) AS start_time,\n    MAX(time) AS end_time,\n    MAX(time)-MIN(time) AS duration\nFROM grouped\nWHERE is_positive = 1\nGROUP BY grp\nORDER BY start_time\n)\n\nSELECT \n  start_time,\n  end_time,\n  EXTRACT(EPOCH FROM(duration)) AS total_duration\nFROM cryo_cycles\nWHERE duration > INTERVAL '20 minutes'"
    }
   ]
  },
  {
   "title": "Base vacuum",
   "type": "timeseries",
   "description": "HVG pressure when the chamber is pumped",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH chamber_state_param AS (\n    SELECT param_id, enum_id\n    FROM parameters\n    WHERE \n        instrument_id = $instrument\n        AND subsystem = 'Vacuum'\n        AND component = 'Chamber'\n        AND param_name = 'Chamber.StateSC'\n),\npumped_value AS (\n    SELECT \n        e.value AS pumped_value_num,\n        p.param_id\n    FROM chamber_state_param p\n    JOIN enum_values e ON e.enum_id = p.enum_id\n    WHERE e.member_name = 'Pumped'\n),\nraw_states AS (\n    SELECT state_agg(v.time, v.value_num::bigint) AS agg\n    FROM data v\n    JOIN chamber_state_param p ON p.param_id = v.param_id\n    WHERE v.instrument_id = $instrument\n      AND $__timeFilter(v.time)\n),\npumped_states AS (\n    SELECT start_time, end_time\n    FROM state_periods(\n        (SELECT agg FROM raw_states),\n        (SELECT pumped_value_num FROM pumped_value)::bigint\n        )\n),\npressure_param AS (\n    SELECT param_id\n    FROM parameters\n    WHERE \n      instrument_id = $instrument\n      AND component = 'Chamber'\n      AND param_name = 'Chamber.HVG'\n),\npressure_values AS (\n    SELECT \n        v.time,\n        v.value_num AS pressure_value\n    FROM data v\n    JOIN pressure_param p ON p.param_id = v.param_id\n    JOIN pumped_states r \n        ON v.time >= r.start_time \n        AND v.time <= r.end_time\n    WHERE \n        v.instrument_id = $instrument\n)\nSELECT\n    time,\n    approx_percentile(\n        0.5,\n        percentile_agg(pressure_value)\n            OVER (\n                ORDER BY time\n                RANGE BETWEEN INTERVAL '2 days' PRECEDING AND CURRENT ROW\n            )\n    ) AS \"Rolling 2-day median HVG pressure\"\nFROM pressure_values\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Interlocks",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH counter_params AS (\n  SELECT param_id, param_name, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND subsystem = 'Vacuum'\n    AND component = 'Interlocks'\n),\n\nbad_values AS (\n  SELECT cp.param_id, cp.param_name, ev.value\n  FROM enum_values ev\n  JOIN counter_params cp USING (enum_id)\n  WHERE ev.member_name IN ('Interlock BAD', 'Disabled')\n)\n\nSELECT\n  bv.param_name,\n  COUNT(*) AS bad_count\nFROM data d\nJOIN bad_values bv ON bv.param_id = d.param_id\n  AND bv.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY bv.param_name\nORDER BY bv.param_name"
    }
   ]
  },
  {
   "title": "Avg time between LN refills",
   "type": "stat",
   "description": "Arctis only",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'TempCtrl'\n    AND param_name = 'Lcldwr'\n),\n\nbucketed AS (\n  SELECT\n    time_bucket('30 seconds', d.time) AS bucket,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN matching_param p ON d.param_id = p.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n  GROUP BY bucket\n),\n\nlagged AS (\n  SELECT\n    bucket,\n    avg_value,\n    LAG(avg_value, 1) OVER (ORDER BY bucket) AS val_1,\n    LAG(avg_value, 2) OVER (ORDER BY bucket) AS val_2,\n    LAG(avg_value, 3) OVER (ORDER BY bucket) AS val_3\n  FROM bucketed\n),\n\nlabeled AS (\n  SELECT *,\n    CASE\n      WHEN avg_value > 90 AND (val_1 < 90 OR val_1 IS NULL) THEN true\n      WHEN avg_value >= COALESCE(val_1, -1e9)\n       AND avg_value >= COALESCE(val_2, -1e9)\n       AND avg_value >= COALESCE(val_3, -1e9)\n       AND avg_value > 90 THEN true\n      ELSE false\n    END AS is_peak\n  FROM lagged\n),\n\nwith_peak_groups AS (\n  SELECT *,\n    CASE\n      WHEN is_peak AND NOT LAG(is_peak, 1, false) OVER (ORDER BY bucket) THEN 1\n      ELSE 0\n    END AS new_peak_start\n  FROM labeled\n),\n\npeak_groups AS (\n  SELECT *,\n    SUM(new_peak_start) OVER (ORDER BY bucket) AS peak_group_id\n  FROM with_peak_groups\n),\n\nranked_peaks AS (\n  SELECT\n    bucket AS time,\n    avg_value,\n    peak_group_id,\n    RANK() OVER (PARTITION BY peak_group_id ORDER BY avg_value DESC) AS val_rank\n  FROM peak_groups\n  WHERE is_peak\n),\n\ncollapsed_peaks AS (\n  SELECT time\n  FROM ranked_peaks\n  WHERE val_rank = 1\n),\n\nwith_deltas AS (\n  SELECT\n    time,\n    LAG(time) OVER (ORDER BY time) AS prev_time\n  FROM collapsed_peaks\n),\n\ndeltas AS (\n  SELECT\n    EXTRACT(EPOCH FROM (time - prev_time)) AS sec_between\n  FROM with_deltas\n  WHERE prev_time IS NOT NULL\n)\n\nSELECT AVG(sec_between) AS avg_sec_between_refills\nFROM deltas;\n"
    }
   ]
  },
  {
   "title": "State",
   "type": "barchart",
   "description": "Based on SC gauge",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Chamber'\n    AND param_name = 'Chamber.StateSC'\n),\n\nenums AS (\n  SELECT e.enum_id, e.member_name, e.value\n  FROM enum_values e\n  JOIN state_param p ON p.enum_id = e.enum_id\n)\n\nSELECT\n  e.member_name AS \"State\",\n  COUNT(*) AS \"Count\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nJOIN enums e ON e.enum_id = p.enum_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY e.member_name\nORDER BY \"Count\" DESC\n"
    }
   ]
  },
  {
   "title": "PVP1 Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument \n    AND component = 'Service'\n    AND param_name = 'PVP1Lifetime'\n)\n\n  SELECT d.value_num\n  FROM data d\n  JOIN counter_param p ON p.param_id = d.param_id\n  WHERE d.instrument_id = $instrument \n    AND $__timeFilter(d.time)\n  ORDER BY d.time DESC\n  LIMIT 1\n"
    }
   ]
  },
  { "title": "Aquilos only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "QuickLoader pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'Quickloader'\n    AND param_name = 'Quickloader.QLG'\n),\n\nhourly_avg AS (\n  SELECT\n    time_bucket('1 hour', d.time) AS hour,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    --AND d.value_num < 10000\n  GROUP BY hour\n)\n\nSELECT\n  hour AS time,\n  avg_value AS \"1-hour average\",\n  AVG(avg_value) OVER (\n    ORDER BY hour\n    RANGE BETWEEN INTERVAL '24 hours' PRECEDING AND CURRENT ROW\n    ) AS \"24-hour average\"\nFROM hourly_avg\nORDER BY hour\n"
    }
   ]
  },
  {
   "title": "Temperatures (1-hour median)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND subsystem = 'Options'\n    AND component = 'Thermometers'\n    AND param_name LIKE 'ExperimentalThermometerCryo%Temperature'\n)\nSELECT\n    time_bucket_gapfill('1 hour', d.time) AS time,\n    p.param_name,\n    locf(approx_percentile(0.5, percentile_agg(d.value_num))) AS median_1h\nFROM data d\nJOIN param_ids p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY 1, 2\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Chamber states",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Chamber'\n    AND param_name = 'Chamber.Mode'\n),\n\nenums AS (\n  SELECT e.enum_id, e.member_name, e.value\n  FROM enum_values e\n  JOIN state_param p ON p.enum_id = e.enum_id\n)\n\nSELECT\n  e.member_name AS \"State\",\n  COUNT(*) AS \"Count\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nJOIN enums e ON e.enum_id = p.enum_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY e.member_name\nORDER BY \"Count\" DESC\n"
    }
   ]
  },
  {
   "title": "Cryo cycles",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n    SELECT param_id\n    FROM parameters\n    WHERE instrument_id = $instrument \n      AND subsystem = 'Options'\n      AND component = 'Thermometers'\n      AND param_name LIKE 'ExperimentalThermometerCryoShieldTemperature'\n),\n\nflagged AS (\n    SELECT\n        d.time,\n        d.value_num AS temp,\n        CASE WHEN d.value_num > 0 THEN 1 ELSE 0 END AS is_positive\n    FROM data d\n    JOIN params p ON p.param_id = d.param_id\n    WHERE d.instrument_id = $instrument \n      AND $__timeFilter(d.time)\n),\n\ngrouped AS (\n    SELECT\n        *,\n        ROW_NUMBER() OVER (ORDER BY time) \n        - ROW_NUMBER() OVER (PARTITION BY is_positive ORDER BY time) AS grp\n    FROM flagged\n)\n\nSELECT\n    MIN(time) AS start_time,\n    MAX(time) AS end_time,\n    MAX(time)-MIN(time) AS duration\nFROM grouped\nWHERE is_positive = 1\nGROUP BY grp\nORDER BY start_time DESC\n"
    }
   ]
  },
  {
   "title": "Holder types",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Stage'\n    AND param_name = 'ActiveHolder'\n),\n\nenums AS (\n  SELECT e.enum_id, e.member_name, e.value\n  FROM enum_values e\n  JOIN state_param p ON p.enum_id = e.enum_id\n)\n\nSELECT\n  e.member_name AS \"Holder\",\n  COUNT(*) AS \"Count\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nJOIN enums e ON e.enum_id = p.enum_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY e.member_name\nORDER BY \"Count\" DESC\n"
    }
   ]
  },
  {
   "title": "Buffer cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id,\n    enum_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name = 'Buffer.BufferState'\n    AND subsystem = 'Vacuum'\n),\n\nstate_enum AS (\n  SELECT e.member_name, e.value\n  FROM\n    enum_values e\n    JOIN state_param p USING (enum_id)\n),\n\ndurations AS (\n  SELECT\n    e.member_name AS state,\n    EXTRACT(EPOCH FROM (end_time-start_time)) AS duration\n  FROM\n    state_int_timeline(\n      (\n        SELECT\n          state_agg(d.time, d.value_num :: bigint) AS agg\n        FROM\n          data d\n          JOIN state_param p USING (param_id)\n        WHERE\n          d.instrument_id = $instrument\n          AND $__timeFilter(d.time)\n          AND d.value_num != 0 -- filter out zeros\n      )\n    )\n  JOIN state_enum e ON e.value = state\n)\n\nSELECT\n  AVG(duration) FILTER (WHERE state = 'Overflow') AS \"Avg duration\",\n  AVG(duration) FILTER (WHERE state = 'OK')  AS \"Avg time between cycles\"\nFROM durations\n"
    }
   ]
  }
 ]
}