{
 "title": "Module | Source",
 "tags": [
  "module",
  "sem"
 ],
 "time": { "from": "2025-10-13T20:44:02.704Z", "to": "2025-11-09T13:28:41.225Z" },
 "templating": {
  "list": [
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  { "title": "Electron Gun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FEG Operate time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FEG'\n    AND param_name = 'OperateTimeFEGParameter'\n)\n\nSELECT d.value_num AS \"OperationTimeCounter\"\nFROM data d\nJOIN counter_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time) \nORDER BY d.time DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "IGP spikes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id, param_name\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name IN ('I-Column.IGP1_PeakCount', 'I-Column.IGP2_PeakCount')\n    AND subsystem = 'Vacuum'\n)\nSELECT\n  p.param_name,\n  MAX(d.value_num) - MIN(d.value_num) AS counts\nFROM data d\nJOIN state_param p USING (param_id)\nWHERE instrument_id = $instrument \n  AND $__timeFilter(d.time)\nGROUP BY p.param_name"
    }
   ]
  },
  {
   "title": "IGP1 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'E-Column'\n    AND param_name = 'E-Column.IGP1'\n),\n\ndaily_avg AS (\n  SELECT\n    time_bucket('1 day', d.time) AS day,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num > 0\n  GROUP BY day, p.param_name\n)\n\nSELECT\n  day AS time,\n  param_name,\n  avg_value AS \"24-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY day\n    ROWS BETWEEN 27 PRECEDING AND CURRENT ROW\n  ) AS \"4-week average\"\nFROM daily_avg\nORDER BY day, param_name;\n"
    }
   ]
  },
  {
   "title": "FEG states",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FEG'\n    AND param_name = 'ExternalStateParameter'\n),\n\nenums AS (\n  SELECT e.enum_id, e.member_name, e.value\n  FROM enum_values e\n  JOIN state_param p ON p.enum_id = e.enum_id\n)\n\nSELECT\n  e.member_name AS \"State\",\n  COUNT(*) AS \"Count\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nJOIN enums e ON e.enum_id = p.enum_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY e.member_name\nORDER BY \"Count\" DESC\n"
    }
   ]
  },
  {
   "title": "IGP2 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'E-Column'\n    AND param_name = 'E-Column.IGP2'\n),\n\ndaily_avg AS (\n  SELECT\n    time_bucket('1 day', d.time) AS day,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num > 0\n  GROUP BY day, p.param_name\n)\n\nSELECT\n  day AS time,\n  param_name,\n  avg_value AS \"24-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY day\n    ROWS BETWEEN 27 PRECEDING AND CURRENT ROW\n  ) AS \"4-week average\"\nFROM daily_avg\nORDER BY day, param_name;\n"
    }
   ]
  },
  {
   "title": "Emission current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'FEG'\n    AND param_name = 'EmissionFEGParameter'\n)\n\nSELECT\n  time,\n  value\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (SELECT param_id FROM matching_param)\n    AND $__timeFilter(time)\n))\nORDER BY 1;\n"
    }
   ]
  },
  { "title": "Ion Gun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "LMIS/PFIB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT instrument_id, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name IN ('SourceAgeParameter', 'OperatingTimeFIBParameter')\n),\n\nfiltered AS (\n  SELECT\n    d.time,\n    d.value_num AS operate_time\n  FROM data d\n  JOIN counter_param p USING (instrument_id, param_id)\n),\n\nchanges AS (\n  SELECT\n    time,\n    operate_time,\n    lag(operate_time) OVER (ORDER BY time) AS prev_value\n  FROM filtered\n),\n\nlast_replacement AS (\n  SELECT time\n  FROM changes\n  WHERE operate_time < prev_value   -- counter reset\n  ORDER BY time DESC\n  LIMIT 1\n),\n\nlast_value AS (\n  SELECT last(operate_time, time) AS source_age\n  FROM filtered\n)\n\nSELECT\n  lv.source_age / 3600 AS \"Source age\",\n  lr.time AS \"Last replacement\"\nFROM last_value lv\nLEFT JOIN last_replacement lr ON true\n"
    }
   ]
  },
  {
   "title": "LMIS heat cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT instrument_id, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name = 'TotalLifetimeHeatsParameter'\n),\n\nlast_reset AS (\n  SELECT MAX(d.time) AS reset_time\n  FROM data d\n  JOIN counter_param p USING (instrument_id, param_id)\n  WHERE d.value_num = 0\n)\n\nSELECT MAX(d.value_num) AS heat_cycles\nFROM data d\nJOIN counter_param p USING (instrument_id, param_id)\nWHERE d.time >= COALESCE(\n  (SELECT reset_time FROM last_reset),\n  to_timestamp($__from/1000)\n)"
    }
   ]
  },
  {
   "title": "IGP3 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'I-Column'\n    AND param_name IN ('IGP3Parameter', 'I-Column.IGP3')\n),\n\ndaily_avg AS (\n  SELECT\n    time_bucket('1 day', d.time) AS day,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num > 0\n  GROUP BY day, p.param_name\n)\n\nSELECT\n  day AS time,\n  param_name,\n  avg_value AS \"24-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY day\n    ROWS BETWEEN 27 PRECEDING AND CURRENT ROW\n  ) AS \"4-week average\"\nFROM daily_avg\nORDER BY day, param_name;\n"
    }
   ]
  },
  {
   "title": "Jacket water flow",
   "type": "stat",
   "description": "Last week mean value",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "WITH target_param AS (\n  SELECT\n    instrument_id,\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name = 'JacketFlowParameter'\n)\n\nSELECT\n  time_bucket('1 week', d.time) as bucket,\n  avg(d.value_num) AS mean_flow\nFROM data d\nJOIN target_param p USING (instrument_id, param_id)\nWHERE $__timeFilter(d.time)\nGROUP BY bucket\nORDER BY bucket DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "PFIB ignition ratio (last week)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH latest_week AS (\n  SELECT time_bucket('1 week', max(d.time)) AS bucket\n  FROM data d\n  JOIN parameters p\n    ON d.instrument_id = p.instrument_id\n   AND d.param_id = p.param_id\n  WHERE p.instrument_id = $instrument \n    AND p.component = 'FIB'\n    AND p.param_name IN ('SuccessfulIgnitionCountParameter', 'TotalIgnitionCountParameter')\n    AND $__timeFilter(d.time)\n)\n\nSELECT\n  COALESCE(NULLIF(delta(counter_agg(d.time, d.value_num) FILTER (WHERE p.param_name = 'SuccessfulIgnitionCountParameter')), 0), 1)::float\n  /\n  COALESCE(NULLIF(delta(counter_agg(d.time, d.value_num) FILTER (WHERE p.param_name = 'TotalIgnitionCountParameter')), 0), 1) AS ratio\n\nFROM data d\nJOIN parameters p\n  ON d.instrument_id = p.instrument_id\n AND d.param_id = p.param_id\nJOIN latest_week lw\n  ON time_bucket('1 week', d.time) = lw.bucket\nWHERE p.instrument_id = $instrument \n  AND p.component = 'FIB'\n  AND p.param_name IN ('SuccessfulIgnitionCountParameter', 'TotalIgnitionCountParameter')\n"
    }
   ]
  },
  {
   "title": "IGP spikes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT\n    param_id, param_name\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_name IN ('I-Column.IGP3_PeakCount', 'I-Column.IGP4_PeakCount')\n    AND subsystem = 'Vacuum'\n)\nSELECT\n  p.param_name,\n  MAX(d.value_num) - MIN(d.value_num) AS counts\nFROM data d\nJOIN state_param p USING (param_id)\nWHERE instrument_id = $instrument \n  AND $__timeFilter(d.time)\nGROUP BY p.param_name"
    }
   ]
  },
  {
   "title": "IGP4 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'I-Column'\n    AND param_name LIKE 'IGP4Parameter'\n),\n\ndaily_avg AS (\n  SELECT\n    time_bucket('1 day', d.time) AS day,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num > 0\n  GROUP BY day, p.param_name\n)\n\nSELECT\n  day AS time,\n  param_name,\n  avg_value AS \"24-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY day\n    ROWS BETWEEN 27 PRECEDING AND CURRENT ROW\n  ) AS \"4-week average\"\nFROM daily_avg\nORDER BY day, param_name;\n"
    }
   ]
  },
  {
   "title": "LMIS emission current (Aquilos only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name = 'EmissionFIBParameter'\n)\n\nSELECT\n  time,\n  value\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (SELECT param_id FROM matching_param)\n    AND $__timeFilter(time)\n))\nORDER BY 1;\n"
    }
   ]
  }
 ]
}