{
 "title": "Productivity",
 "tags": [
  "overview",
  "sem"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nWHERE is_active IS TRUE\nORDER BY name;\n"
   },
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Autoloader counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(daily_cartridge_count) AS \"cartridges/day\",\n  SUM(daily_cartridge_count) AS \"total cartridges\",\n  AVG(daily_cassette_count) AS \"cassettes/day\",\n  SUM(daily_cassette_count) AS \"total cassettes\"\nFROM load_counters_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\n"
    }
   ]
  },
  {
   "title": "Beam time",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  day AS \"time\",\n  state,\n  LEAST(100.0 * SUM(seconds) / 86400.0, 100.0) AS percentage\nFROM sem_beamtime_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\nGROUP BY day, state\nORDER BY day, state\n"
    }
   ]
  },
  {
   "title": "PFIB gas usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH cagg AS (\n  SELECT\n    time_bucket('1 day', d.time) AS day,\n    delta(counter_agg(d.time, d.value_num)) AS daily_usage,\n    substring(p.param_name FROM '^GasUsage_(.+)Parameter$') AS gas_type\n  FROM\n    data d\n    JOIN parameters p USING (param_id, instrument_id)\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND p.component = 'FIB'\n    AND p.param_name LIKE 'GasUsage_%Parameter'\n  GROUP BY day, gas_type\n)\n\nSELECT\n  day AS time,\n  gas_type AS name,\n  daily_usage AS value\nFROM cagg\nORDER BY day\n"
    }
   ]
  },
  {
   "title": "GIS usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  day AS time,\n  gis_port AS name,\n  delta(agg) AS value\nFROM gis_counters_daily\nWHERE instrument_id = $instrument\n  AND $__timeFilter(day)\nORDER BY day"
    }
   ]
  }
 ]
}