{
 "title": "Productivity",
 "tags": [
  "overview",
  "sem"
 ],
 "time": { "from": "2025-10-13T20:44:02.704Z", "to": "2025-11-09T13:28:41.225Z" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceSEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Autoloader counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(daily_cartridge_count) AS \"cartridges/day\",\n  SUM(daily_cartridge_count) AS \"total cartridges\",\n  AVG(daily_cassette_count) AS \"cassettes/day\",\n  SUM(daily_cassette_count) AS \"total cassettes\"\nFROM load_counters_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\n"
    }
   ]
  },
  {
   "title": "KPI",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "targets": [
    {
     "rawSql": "WITH gis_params AS (\n  SELECT\n    instrument_id,\n    param_id,\n    component AS port\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND subsystem = 'GISes'\n    AND param_name LIKE 'GIS%ValveOpenTimeParameter'\n),\n\ngis_usage AS (\n    SELECT\n        port || ' usage',\n        last(value_num, time)/3600.0 AS gis_usage\n    FROM data d\n    JOIN gis_params p USING (instrument_id, param_id)\n    GROUP BY port\n),\n\nsource_param AS (\n  SELECT instrument_id, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FIB'\n    AND param_name IN ('SourceAgeParameter', 'OperatingTimeFIBParameter')\n),\n\nsource_usage AS (\n  SELECT\n    'Source age',\n    last(value_num, time)/3600.0 AS source_age\n  FROM data\n  JOIN source_param p USING (instrument_id, param_id)\n  WHERE $__timeFilter(time) \n)\n\nSELECT * FROM gis_usage\nUNION ALL\nSELECT * FROM source_usage\n"
    }
   ]
  },
  {
   "title": "Beam time",
   "type": "barchart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  day AS \"time\",\n  state,\n  LEAST(100.0 * SUM(seconds) / 86400.0, 100.0) AS percentage\nFROM sem_beamtime_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\nGROUP BY day, state\nORDER BY day, state\n"
    }
   ]
  }
 ]
}