DO
$$
  DECLARE
    current_version INTEGER;
  BEGIN
    -- Get current schema version
    SELECT MAX(version) INTO current_version FROM public.schema_info;

    IF current_version = 6 THEN
      -- 1. Drop before insert trigger and function for event.parameters
      DROP TRIGGER IF EXISTS parameters_upsert_before_insert ON events.parameters;
      DROP FUNCTION IF EXISTS events.parameters_upsert_before_insert();

      -- 2. Remove enum values history and associated triggers/func
      DROP TRIGGER IF EXISTS enum_values_upsert_before_insert ON events.enum_values;
      DROP FUNCTION IF EXISTS events.enum_values_upsert_before_insert();
      DROP TRIGGER IF EXISTS enum_values_log_after_update ON events.enum_values;
      DROP FUNCTION IF EXISTS events.enum_values_log_after_update();
      DROP TABLE events.enum_values_history;

      -- 3. Remove enum id FK from parameters history
      ALTER TABLE events.parameters_history
        DROP CONSTRAINT IF EXISTS parameters_history_enum_id_instrument_id_fkey;

      -- 4. Creating events.configurations
      CREATE TABLE IF NOT EXISTS events.configurations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        config_hash BYTEA NOT NULL UNIQUE,
        config_dict JSONB NOT NULL
      );
      COMMENT ON TABLE events.configurations IS 'HM configuration for IntEnums';

      -- 5. Migrate events.instruments to adjust column padding
      DROP EXTENSION IF EXISTS pgstattuple;

      -- 4. Update schema version
      UPDATE public.schema_info SET version = 7;
    END IF;
  END
$$
