DO
$$
  DECLARE
    current_version INTEGER;
    job INTEGER;
    chunk REGCLASS;
    old_count BIGINT;
    new_count BIGINT;
    map_count BIGINT;
    r RECORD;
  BEGIN
    -- Get current schema version
    SELECT MAX(version) INTO current_version FROM public.schema_info;

    IF current_version = 6 THEN
      -- 1. Run superuser jobs
      DROP EXTENSION IF EXISTS pgstattuple;
      REVOKE pg_stat_scan_tables FROM grafana;
      REVOKE pg_read_all_stats FROM grafana;

      -- 2. Remove ALL old triggers
      SET ROLE emhealth;
      DROP TRIGGER IF EXISTS enum_values_upsert_before_insert ON events.enum_values;
      DROP FUNCTION IF EXISTS events.enum_values_upsert_before_insert();
      DROP TRIGGER IF EXISTS enum_values_log_after_update ON events.enum_values;
      DROP FUNCTION IF EXISTS events.enum_values_log_after_update();
      DROP TRIGGER IF EXISTS parameters_log_after_update ON events.parameters;
      DROP FUNCTION IF EXISTS events.parameters_log_after_update();
      DROP TRIGGER IF EXISTS parameters_upsert_before_insert ON events.parameters;
      DROP FUNCTION IF EXISTS events.parameters_upsert_before_insert();

      -- 3. Drop history tables for now
      DROP TABLE IF EXISTS events.parameters_history;
      DROP TABLE IF EXISTS events.enum_values_history;

      -- 4. Migrate events.instruments
      RAISE NOTICE 'Starting events schema migration..';
      CREATE TABLE IF NOT EXISTS events.instruments_new (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        current_config_id BIGINT,
        serial INTEGER NOT NULL UNIQUE,
        server INET CONSTRAINT ipv4 CHECK (family(server) = 4 AND masklen(server) = 32),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        instrument TEXT NOT NULL UNIQUE,
        model TEXT NOT NULL,
        name TEXT NOT NULL,
        template TEXT NOT NULL,
        ds_version TEXT
      );
      COMMENT ON TABLE events.instruments_new IS 'Main instruments table';

      INSERT INTO events.instruments_new (
        serial,
        server,
        is_active,
        instrument,
        model,
        name,
        template,
        ds_version
      )
      SELECT
        serial,
        server,
        is_active,
        instrument,
        model,
        name,
        template,
        ds_version
      FROM events.instruments;

      CREATE TABLE events.instruments_id_map (
        old_id INTEGER PRIMARY KEY,
        new_id BIGINT NOT NULL UNIQUE
      );

      INSERT INTO events.instruments_id_map (old_id, new_id)
      SELECT
        old.id,
        new.id
      FROM events.instruments old
           JOIN events.instruments_new new
          ON new.serial = old.serial;

      -- 5. Create events.configurations
      CREATE TABLE IF NOT EXISTS events.configurations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        instrument_id BIGINT NOT NULL REFERENCES events.instruments_new (id),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        config_hash BYTEA, -- NULL for now
        config_dict JSONB, -- NULL for now
        CONSTRAINT configurations_instr_id_key UNIQUE (instrument_id, id),
        CONSTRAINT configurations_instr_hash_key UNIQUE (instrument_id, config_hash)
      );
      COMMENT ON TABLE events.configurations IS 'HM IntEnums configurations';
      COMMENT ON CONSTRAINT configurations_instr_hash_key
        ON events.configurations IS 'Two instruments can have the same config hash/dict';

      INSERT INTO events.configurations (instrument_id, config_hash, config_dict)
      SELECT id, ''::bytea, '{}'::jsonb
      FROM events.instruments_new;

      UPDATE events.instruments_new i
      SET current_config_id = c.id
      FROM events.configurations c
      WHERE i.id = c.instrument_id;

      ALTER TABLE events.configurations
        ALTER COLUMN config_hash SET NOT NULL,
        ALTER COLUMN config_dict SET NOT NULL;

      -- 6. Create new empty enum tables
      CREATE TABLE IF NOT EXISTS events.enum_types_new (
        enum_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        instrument_id BIGINT NOT NULL REFERENCES events.instruments_new (id),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        name TEXT NOT NULL,
        CONSTRAINT enum_types_instr_enumid_pkey PRIMARY KEY (instrument_id, enum_id),
        CONSTRAINT enum_types_instr_enumname_key UNIQUE (instrument_id, name)
      );

      COMMENT ON TABLE events.enum_types_new IS 'Current HM IntEnum definitions';
      COMMENT ON CONSTRAINT enum_types_instr_enumname_key
        ON events.enum_types_new IS 'Each instrument has its own set of enum types, but two instruments can have different enums with the same name';

      CREATE TABLE IF NOT EXISTS events.enum_values_new (
        instrument_id BIGINT NOT NULL,
        enum_id BIGINT NOT NULL,
        value INTEGER NOT NULL,
        member_name TEXT NOT NULL,
        CONSTRAINT enum_values_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
          REFERENCES events.enum_types_new (instrument_id, enum_id) ON DELETE CASCADE,
        CONSTRAINT enum_values_names_key UNIQUE (instrument_id, enum_id, member_name),
        CONSTRAINT enum_values_values_key UNIQUE (instrument_id, enum_id, value)
      );

      COMMENT ON TABLE events.enum_values_new IS 'Current HM IntEnum members for each instrument';
      COMMENT ON CONSTRAINT enum_values_instr_enum_fkey
        ON events.enum_values_new IS 'enum_id are scoped per instrument';
      COMMENT ON CONSTRAINT enum_values_names_key
        ON events.enum_values_new IS 'Each enum is required to have unique member names';
      COMMENT ON CONSTRAINT enum_values_values_key
        ON events.enum_values_new IS 'Each enum is required to have unique member values';

      -- 7. Create new params table
      CREATE TABLE IF NOT EXISTS events.parameters_new (
        instrument_id BIGINT NOT NULL,
        param_id BIGINT NOT NULL,
        config_id BIGINT NOT NULL,
        enum_id BIGINT,
        event_id INTEGER NOT NULL,
        abs_limits NUMRANGE,
        crit_limits NUMRANGE,
        warn_limits NUMRANGE,
        caution_limits NUMRANGE,
        subsystem TEXT NOT NULL,
        component TEXT NOT NULL,
        param_name TEXT NOT NULL,
        display_name TEXT NOT NULL,
        display_unit TEXT,
        storage_unit TEXT,
        value_type TEXT NOT NULL,
        event_name TEXT NOT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        CONSTRAINT parameters_instr_param_key UNIQUE (instrument_id, param_id),
        CONSTRAINT parameters_instr_config_fkey FOREIGN KEY (instrument_id, config_id)
          REFERENCES events.configurations (instrument_id, id),
        CONSTRAINT parameters_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
          REFERENCES events.enum_types_new (instrument_id, enum_id),
        CONSTRAINT parameters_value_type_check CHECK (value_type IN ('int', 'float', 'str', 'bool'))
      );

      COMMENT ON TABLE events.parameters_new IS 'HM parameters metadata';
      COMMENT ON CONSTRAINT parameters_instr_param_key
        ON events.parameters_new IS 'param_id is unique per instrument';

      -- 8. Re-creating events.parameters_history
      CREATE TABLE IF NOT EXISTS events.parameters_history (
        inserted timestamptz NOT NULL DEFAULT NOW(),
        instrument_id BIGINT NOT NULL,
        param_id BIGINT NOT NULL,
        config_id BIGINT NOT NULL,
        enum_id BIGINT,
        event_id INTEGER NOT NULL,
        abs_limits NUMRANGE,
        crit_limits NUMRANGE,
        warn_limits NUMRANGE,
        caution_limits NUMRANGE,
        subsystem TEXT NOT NULL,
        component TEXT NOT NULL,
        param_name TEXT NOT NULL,
        display_name TEXT NOT NULL,
        display_unit TEXT,
        storage_unit TEXT,
        value_type TEXT NOT NULL,
        event_name TEXT NOT NULL,
        CONSTRAINT parameters_history_instr_param_time_key UNIQUE (instrument_id, param_id, inserted),
        CONSTRAINT parameters_history_instr_config_fkey FOREIGN KEY (instrument_id, config_id)
          REFERENCES events.configurations (instrument_id, id),
        CONSTRAINT parameters_history_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
          REFERENCES events.enum_types_new (instrument_id, enum_id)
      );
      COMMENT ON TABLE events.parameters_history IS 'Historical HM metadata for each parameter';

      -- 9. Re-creating events.data_staging
      DROP TABLE IF EXISTS events.data_staging;
      CREATE UNLOGGED TABLE IF NOT EXISTS events.data_staging (
        time timestamptz NOT NULL,
        instrument_id BIGINT NOT NULL,
        param_id BIGINT NOT NULL,
        value_num DOUBLE PRECISION,
        value_text TEXT
      );
      COMMENT ON TABLE events.data_staging IS 'Staging table for bulk COPY inserts';

      -- 10. Migrate old params table: param_id is kept, instrument_id changes
      INSERT INTO events.parameters_new (
        instrument_id,
        param_id,
        config_id,
        enum_id,
        event_id,
        abs_limits,
        crit_limits,
        warn_limits,
        caution_limits,
        subsystem,
        component,
        param_name,
        display_name,
        display_unit,
        storage_unit,
        value_type,
        event_name,
        is_active
      )
      SELECT
        im.new_id,
        p.param_id,
        i.current_config_id,
        NULL, -- do not migrate enum_id
        p.event_id,
        numrange(
          CASE
            WHEN abs_min = '-1.7976931348623157e+308'::double precision
              THEN NULL
            ELSE abs_min::numeric
            END,
          CASE
            WHEN abs_max = '1.7976931348623157e+308'::double precision
              THEN NULL
            ELSE abs_max::numeric
            END,
          '[]'
        ),
        NULL,
        NULL,
        NULL,
        p.subsystem,
        p.component,
        p.param_name,
        p.display_name,
        p.display_unit,
        p.storage_unit,
        p.value_type,
        p.event_name,
        TRUE
      FROM events.parameters p
           JOIN events.instruments_id_map im
          ON im.old_id = p.instrument_id
           JOIN events.instruments_new i
          ON i.id = im.new_id;

      -- 11. Convert to rowstore and alter events.data
      SELECT job_id
      INTO job
      FROM
        timescaledb_information.jobs
      WHERE
        proc_name = 'policy_compression'
        AND hypertable_schema = 'events'
        AND hypertable_name = 'data';

      PERFORM alter_job(job, scheduled => FALSE);

      FOR chunk IN SELECT show_chunks('events.data') LOOP
        RAISE NOTICE 'Converting % to rowstore', chunk;
        CALL convert_to_rowstore(chunk);
      END LOOP;

      ALTER TABLE events.data
        DROP CONSTRAINT IF EXISTS data_instrument_id_fkey;
      ALTER TABLE events.data
        DROP CONSTRAINT IF EXISTS data_param_id_instrument_id_time_key;

      FOR r IN
        SELECT view_schema, view_name
        FROM timescaledb_information.continuous_aggregates
        WHERE hypertable_schema = 'events'
          AND hypertable_name = 'data'
      LOOP
        RAISE NOTICE 'Dropping continuous aggregate %.%', r.view_schema, r.view_name;
        EXECUTE format('DROP MATERIALIZED VIEW IF EXISTS %I.%I CASCADE', r.view_schema, r.view_name);
      END LOOP;

      FOR r IN
        SELECT schemaname, matviewname
        FROM pg_matviews
      LOOP
        RAISE NOTICE 'Dropping materialized view %.%', r.schemaname, r.matviewname;
        EXECUTE format(
          'DROP MATERIALIZED VIEW IF EXISTS %I.%I CASCADE;
     SELECT delete_job(job_id)
     FROM timescaledb_information.jobs
     WHERE proc_name = %L;
     DROP PROCEDURE IF EXISTS %I;',
          r.schemaname,
          r.matviewname,
          'refresh_' || r.matviewname,
          'refresh_' || r.matviewname
                );
      END LOOP;

      ALTER TABLE events.data
        ALTER COLUMN instrument_id TYPE BIGINT,
        ALTER COLUMN param_id TYPE BIGINT;

      RAISE NOTICE 'Updating events.data with new instrument_ids..';
      UPDATE events.data d
      SET instrument_id = m.new_id
      FROM events.instruments_id_map m
      WHERE d.instrument_id = m.old_id;

      RAISE NOTICE 'Updating events.data with new indexes..';

      ALTER TABLE events.data
        ADD CONSTRAINT data_instrument_param_time_key
          UNIQUE (instrument_id, param_id, time);

      ALTER TABLE events.data
        ADD CONSTRAINT data_instrument_param_fkey
          FOREIGN KEY (instrument_id, param_id)
            REFERENCES events.parameters_new (instrument_id, param_id);

      PERFORM alter_job(job, scheduled => TRUE);

      -- 12. Swap tables
      ALTER TABLE events.instruments RENAME TO instruments_old;
      ALTER TABLE events.instruments_new RENAME TO instruments;

      ALTER TABLE events.enum_values RENAME TO enum_values_old;
      ALTER TABLE events.enum_values_new RENAME TO enum_values;

      ALTER TABLE events.enum_types RENAME TO enum_types_old;
      ALTER TABLE events.enum_types_new RENAME TO enum_types;

      ALTER TABLE events.parameters RENAME TO parameters_old;
      ALTER TABLE events.parameters_new RENAME TO parameters;

      -- 13. Create new funcs and update parameters_log_after_update()
      RAISE NOTICE 'Creating new functions..';
      EXECUTE $sql$
CREATE OR REPLACE FUNCTION events.import_instrument(
  p_instr_dict JSONB,
  p_config_hash BYTEA,
  p_config_dict JSONB,
  OUT v_instrument_id BIGINT
)
  RETURNS BIGINT
  LANGUAGE plpgsql
AS $func$
DECLARE
  v_current_config_hash BYTEA;
  v_config_id BIGINT;
  v_mismatch RECORD;
BEGIN
  -- Find the instrument and lock it so concurrent imports for the same instrument cannot race
  SELECT i.id, c.config_hash
  INTO v_instrument_id, v_current_config_hash
  FROM events.instruments AS i
       LEFT JOIN events.configurations AS c
      ON c.id = i.current_config_id
  WHERE i.instrument = p_instr_dict ->> 'instrument'
    FOR UPDATE OF i;

  -- Instrument does not exist
  IF NOT FOUND THEN
    RAISE NOTICE '[%] Instrument not found, creating a new entry', p_instr_dict ->> 'name';

    INSERT INTO events.instruments (
      serial,
      server,
      instrument,
      model,
      name,
      template
    )
    VALUES (
      (p_instr_dict ->> 'serial')::INTEGER,
      (p_instr_dict ->> 'server')::INET,
      p_instr_dict ->> 'instrument',
      p_instr_dict ->> 'model',
      p_instr_dict ->> 'name',
      p_instr_dict ->> 'template'
    )
    RETURNING id INTO v_instrument_id;

    INSERT INTO events.configurations (
      instrument_id,
      config_hash,
      config_dict
    )
    VALUES (
      v_instrument_id,
      p_config_hash,
      p_config_dict
    )
    RETURNING id INTO v_config_id;

    UPDATE events.instruments
    SET current_config_id = v_config_id
    WHERE id = v_instrument_id;

  ELSE
    RAISE NOTICE '[%] Instrument already exists', p_instr_dict ->> 'name';

    IF v_current_config_hash IS DISTINCT FROM p_config_hash THEN
      -- Configuration changed: create a new config
      RAISE NOTICE '[%] Configuration has changed, updating', p_instr_dict ->> 'name';
      INSERT INTO events.configurations (
        instrument_id,
        config_hash,
        config_dict
      )
      VALUES (
        v_instrument_id,
        p_config_hash,
        p_config_dict
      )
      RETURNING id INTO v_config_id;

      -- Make the new configuration current
      UPDATE events.instruments
      SET current_config_id = v_config_id
      WHERE id = v_instrument_id;
    END IF;

  END IF;

  -- Insert enum types, on conflict explicitly set is_active=TRUE
  INSERT INTO events.enum_types (
    instrument_id,
    name
  )
  SELECT
    v_instrument_id,
    key
  FROM jsonb_each(p_config_dict->'enums')
  ON CONFLICT (instrument_id, name)
    DO UPDATE SET
    is_active = TRUE
  WHERE events.enum_types.is_active IS DISTINCT FROM TRUE;

  -- Deactivate enum types no longer present in the config
  UPDATE events.enum_types et
  SET is_active = FALSE
  WHERE et.instrument_id = v_instrument_id
    AND et.is_active = TRUE
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_object_keys(p_config_dict->'enums') AS e(name)
      WHERE e.name = et.name
    );

  -- Check for mismatch in enum values for existing members
  FOR v_mismatch IN
    SELECT
      et.instrument_id,
      et.enum_id,
      et.name AS enum_name,
      ev.key AS member_name,
      existing.value AS old_value,
      ev.value::INTEGER AS new_value
    FROM jsonb_each(p_config_dict->'enums') AS e(key, value)
         JOIN events.enum_types AS et
        ON et.instrument_id = v_instrument_id
        AND et.name = e.key
         CROSS JOIN LATERAL jsonb_each_text(e.value) AS ev(key, value)
         JOIN events.enum_values AS existing
        ON existing.instrument_id = v_instrument_id
        AND existing.enum_id = et.enum_id
        AND existing.member_name = ev.key
    WHERE existing.value <> ev.value::INTEGER
  LOOP
    RAISE EXCEPTION
      'Enum value mismatch: instr_id=%, enum_id=%, name=%, member=%, old_value=%, new_value=%',
      v_mismatch.instrument_id,
      v_mismatch.enum_id,
      v_mismatch.enum_name,
      v_mismatch.member_name,
      v_mismatch.old_value,
      v_mismatch.new_value;
  END LOOP;

  -- Insert enum values
  INSERT INTO events.enum_values (
    instrument_id,
    enum_id,
    value,
    member_name
  )
  SELECT
    v_instrument_id,
    et.enum_id,
    ev.value::INTEGER,
    ev.key
  FROM jsonb_each(p_config_dict->'enums') AS e(key, value)
       JOIN events.enum_types AS et
      ON et.instrument_id = v_instrument_id
      AND et.name = e.key
       CROSS JOIN LATERAL jsonb_each_text(e.value) AS ev(key, value)
  ON CONFLICT (instrument_id, enum_id, member_name)
    DO NOTHING;

  -- Insert parameters
  INSERT INTO events.parameters (
    instrument_id,
    param_id,
    config_id,
    enum_id,
    event_id,
    abs_limits,
    subsystem,
    component,
    param_name,
    display_name,
    display_unit,
    storage_unit,
    value_type,
    event_name
  )
  SELECT
    i.id,
    (p.param_id)::BIGINT,
    i.current_config_id,
    et.enum_id,
    (p.data ->> 'event_id')::INTEGER,
    numrange(
            CASE
                WHEN (p.data ->> 'abs_min')::numeric = '-1.7976931348623157e308'::numeric
                    THEN NULL
                ELSE (p.data ->> 'abs_min')::numeric
                END,
            CASE
                WHEN (p.data ->> 'abs_max')::numeric = '1.7976931348623157e308'::numeric
                    THEN NULL
                ELSE (p.data ->> 'abs_max')::numeric
                END,
            '[]'
    ),
    p.data ->> 'subsystem',
    p.data ->> 'component',
    p.data ->> 'param_name',
    p.data ->> 'display_name',
    p.data ->> 'display_unit',
    p.data ->> 'storage_unit',
    p.data ->> 'value_type',
    p.data ->> 'event_name'
  FROM events.instruments AS i
       CROSS JOIN jsonb_each(p_config_dict->'params') AS p(param_id, data)
       LEFT JOIN events.enum_types AS et
      ON et.instrument_id = v_instrument_id
      AND et.name = p.data ->> 'enum_name'
  WHERE i.id = v_instrument_id

  ON CONFLICT (instrument_id, param_id)
    DO UPDATE SET
    config_id = EXCLUDED.config_id,
    enum_id = EXCLUDED.enum_id,
    event_id = EXCLUDED.event_id,
    abs_limits = EXCLUDED.abs_limits,
    subsystem = EXCLUDED.subsystem,
    component = EXCLUDED.component,
    param_name = EXCLUDED.param_name,
    display_name = EXCLUDED.display_name,
    display_unit = EXCLUDED.display_unit,
    storage_unit = EXCLUDED.storage_unit,
    value_type = EXCLUDED.value_type,
    event_name = EXCLUDED.event_name,
    is_active = TRUE

  WHERE ROW(
    events.parameters.enum_id,
    events.parameters.event_id,
    events.parameters.abs_limits,
    events.parameters.subsystem,
    events.parameters.component,
    events.parameters.param_name,
    events.parameters.display_name,
    events.parameters.display_unit,
    events.parameters.storage_unit,
    events.parameters.value_type,
    events.parameters.event_name,
    events.parameters.is_active
    ) IS DISTINCT FROM ROW(
    EXCLUDED.enum_id,
    EXCLUDED.event_id,
    EXCLUDED.abs_limits,
    EXCLUDED.subsystem,
    EXCLUDED.component,
    EXCLUDED.param_name,
    EXCLUDED.display_name,
    EXCLUDED.display_unit,
    EXCLUDED.storage_unit,
    EXCLUDED.value_type,
    EXCLUDED.event_name,
    TRUE
    );

  -- Deactivate params no longer present in the config
  UPDATE events.parameters p
  SET is_active = FALSE
  WHERE p.instrument_id = v_instrument_id
    AND p.is_active = TRUE
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_object_keys(p_config_dict->'params') AS param(param_id)
      WHERE param.param_id::BIGINT = p.param_id
    );

  RETURN;
END;
$func$;

-- Creating update_thresholds
CREATE OR REPLACE FUNCTION events.update_thresholds(
  p_instrument_id BIGINT,
  p_thresholds_dict JSONB,
  OUT v_updated_count INTEGER
)
  LANGUAGE plpgsql
AS $func$
BEGIN
  WITH new_values AS (
    SELECT
      v.key::BIGINT AS param_id,
      numrange(
        (v.value ->> 'CriticalMin')::numeric,
        (v.value ->> 'CriticalMax')::numeric,
        '[]'
      ) AS crit_limits,
      numrange(
        (v.value ->> 'WarningMin')::numeric,
        (v.value ->> 'WarningMax')::numeric,
        '[]'
      ) AS warn_limits,
      numrange(
        (v.value ->> 'CautionMin')::numeric,
        (v.value ->> 'CautionMax')::numeric,
        '[]'
      ) AS caution_limits
    FROM jsonb_each(p_thresholds_dict) v
  )
  UPDATE events.parameters p
  SET
    crit_limits = n.crit_limits,
    warn_limits = n.warn_limits,
    caution_limits = n.caution_limits
  FROM new_values n
  WHERE p.instrument_id = p_instrument_id
    AND p.param_id = n.param_id
    AND (
      p.crit_limits IS DISTINCT FROM n.crit_limits
        OR p.warn_limits IS DISTINCT FROM n.warn_limits
        OR p.caution_limits IS DISTINCT FROM n.caution_limits
      );
  GET DIAGNOSTICS v_updated_count = ROW_COUNT;
  RETURN;
END;
$func$;

-- Creating delete_instrument
CREATE OR REPLACE FUNCTION events.delete_instrument(
  p_instrument_id BIGINT
)
  RETURNS VOID
  LANGUAGE plpgsql
AS $func$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM events.instruments
        WHERE id = p_instrument_id
    ) THEN
        RAISE EXCEPTION 'Instrument % does not exist', p_instrument_id;
    END IF;

    DELETE FROM events.data
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.parameters_history
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.enum_values
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.parameters
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.enum_types
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.configurations
    WHERE instrument_id = p_instrument_id;

    DELETE FROM events.instruments
    WHERE id = p_instrument_id;
END;
$func$;

CREATE OR REPLACE FUNCTION events.parameters_log_after_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $func$
BEGIN
  IF ROW(
    old.instrument_id,
    old.param_id,
    old.config_id,
    old.enum_id,
    old.event_id,
    old.abs_limits,
    old.crit_limits,
    old.warn_limits,
    old.caution_limits,
    old.subsystem,
    old.component,
    old.param_name,
    old.display_name,
    old.display_unit,
    old.storage_unit,
    old.value_type,
    old.event_name
    ) IS DISTINCT FROM ROW(
    new.instrument_id,
    new.param_id,
    new.config_id,
    new.enum_id,
    new.event_id,
    new.abs_limits,
    new.crit_limits,
    new.warn_limits,
    new.caution_limits,
    new.subsystem,
    new.component,
    new.param_name,
    new.display_name,
    new.display_unit,
    new.storage_unit,
    new.value_type,
    new.event_name
    ) THEN
    INSERT INTO events.parameters_history (
      instrument_id,
      param_id,
      config_id,
      enum_id,
      event_id,
      abs_limits,
      crit_limits,
      warn_limits,
      caution_limits,
      subsystem,
      component,
      param_name,
      display_name,
      display_unit,
      storage_unit,
      value_type,
      event_name
    )
    VALUES
      (
        old.instrument_id,
        old.param_id,
        old.config_id,
        old.enum_id,
        old.event_id,
        old.abs_limits,
        old.crit_limits,
        old.warn_limits,
        old.caution_limits,
        old.subsystem,
        old.component,
        old.param_name,
        old.display_name,
        old.display_unit,
        old.storage_unit,
        old.value_type,
        old.event_name
      );

    RAISE NOTICE E'Updated parameter % for instrument %:\n%\n->\n%', old.param_id, old.instrument_id, old, new;
  END IF;

  RETURN new;
END;
$func$;
$sql$;

      CREATE TRIGGER parameters_log_after_update
        AFTER UPDATE
        ON events.parameters
        FOR EACH ROW
      EXECUTE FUNCTION events.parameters_log_after_update();

      -- 14. Validate all
      SELECT count(*) INTO old_count FROM events.instruments_old;
      SELECT count(*) INTO new_count FROM events.instruments;
      SELECT count(*) INTO map_count FROM events.instruments_id_map;

      IF old_count <> new_count THEN
        RAISE EXCEPTION 'Instrument count changed: old=%, new=%', old_count, new_count;
      END IF;

      IF old_count <> map_count THEN
        RAISE EXCEPTION 'Incomplete instrument mapping: old=%, mapped=%', old_count, map_count;
      END IF;

      SELECT count(*) INTO old_count FROM events.parameters_old;
      SELECT count(*) INTO new_count FROM events.parameters;

      IF old_count <> new_count THEN
        RAISE EXCEPTION 'Parameter count changed: old=%, new=%', old_count, new_count;
      END IF;

      SELECT count(*) INTO new_count
      FROM events.parameters_old p
      WHERE NOT EXISTS (
        SELECT 1
        FROM events.instruments_id_map m
             JOIN events.parameters pn
            ON pn.instrument_id = m.new_id
            AND pn.param_id = p.param_id
        WHERE m.old_id = p.instrument_id
      );

      IF new_count <> 0 THEN
        RAISE EXCEPTION 'Parameter mapping failed: % parameters have no destination', new_count;
      END IF;

      -- 15. Drop old tables
      RAISE NOTICE 'Removing old tables..';
      DROP TABLE IF EXISTS events.instruments_id_map;
      DROP TABLE IF EXISTS events.enum_values_old CASCADE;
      DROP TABLE IF EXISTS events.enum_types_old CASCADE;
      DROP TABLE IF EXISTS events.parameters_old CASCADE;
      DROP TABLE IF EXISTS events.instruments_old CASCADE;

      -- 16. Adjust uec.errors unique index for instrument_id type change
      ALTER TABLE uec.errors
        DROP CONSTRAINT IF EXISTS errors_time_instrument_id_errorid_key;

      ALTER TABLE uec.errors
        ALTER COLUMN instrument_id TYPE BIGINT;

      ALTER TABLE uec.errors
        ADD CONSTRAINT errors_instrument_id_errorid_time_key
          UNIQUE (instrument_id, errorid, time);

      -- 17. Update schema version
      SET ROLE postgres;
      UPDATE public.schema_info SET version = 7;
    END IF;
  END
$$
