{
 "title": "Data browser",
 "description": "Raw data analysis mainly used for development",
 "tags": [
  "dev",
  "tem"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   {
    "name": "subsystem",
    "query": "SELECT subsystem\nFROM parameters\nWHERE instrument_id = $instrument\n"
   },
   {
    "name": "component",
    "query": "SELECT component\nFROM parameters\nWHERE instrument_id = $instrument\nAND subsystem = '$subsystem'\n"
   },
   {
    "name": "param",
    "query": "SELECT param_id AS __value,\nparam_name AS __text\nFROM parameters\nWHERE instrument_id = $instrument \nAND subsystem = '$subsystem'\nAND component IN (${component:sqlstring})\n"
   },
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  param_id,\n  subsystem,\n  component,\n  param_name,\n  display_name,\n  COALESCE(storage_unit, '') AS storage_unit,\n  enum_id, \n  value_type \nFROM parameters\nWHERE \n  instrument_id = $instrument\n  AND param_id IN ($param)\n"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Time series for $param",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    param_id,\n    display_name\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND param_id IN ($param)\n)\nSELECT\n  d.time,\n  d.value_num AS \"value\",\n  p.display_name AS \"__name__\"\nFROM\n  data d\n  JOIN params p USING (param_id)\nWHERE\n  d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY\n  d.time;"
    }
   ]
  },
  { "title": "Table view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Table view for $param",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "repeat": "param",
   "targets": [
    {
     "rawSql": "SELECT\n    d.time,\n    d.value_num AS \"value\",\n    e.member_name AS \"enumeration\"\nFROM data d\nLEFT JOIN enum_values e\n  ON e.enum_id = (SELECT enum_id FROM parameters WHERE instrument_id = $instrument AND param_id = $param)\n AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND d.param_id = $param\n  AND $__timeFilter(d.time)\nORDER BY d.time;\n"
    }
   ]
  },
  { "title": "Enumerations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Enumerations for $param",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "repeat": "param",
   "targets": [
    {
     "rawSql": "WITH target_param AS (\n  SELECT enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_id = $param\n)\n\nSELECT\n et.id AS enum_id,\n et.name AS enum_name,\n ev.member_name,\n ev.value\nFROM enum_values ev\nJOIN enum_types et ON et.id = ev.enum_id\nWHERE et.instrument_id = $instrument\n  AND (\n    NOT EXISTS (SELECT 1 FROM target_param)\n    OR et.id IN (SELECT enum_id FROM target_param)\n  )\nORDER BY ev.value"
    }
   ]
  }
 ]
}