{
 "title": "Fleet overview",
 "description": "General overview of all systems",
 "tags": [
  "overview",
  "tem"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Beam time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instrument",
   "type": "piechart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH total AS (\n  SELECT SUM(seconds) AS total_seconds\n  FROM vacuum_state_daily\n  WHERE $__timeFilter(day)\n    AND instrument_id = $instrument\n)\nSELECT\n  v.state,\n  SUM(v.seconds) AS duration_seconds,\n  ROUND(100.0 * SUM(v.seconds) / NULLIF(t.total_seconds, 0), 2) AS percentage\nFROM vacuum_state_daily v\nCROSS JOIN total t\nWHERE $__timeFilter(v.day)\n  AND v.instrument_id = $instrument\nGROUP BY v.state, t.total_seconds\nORDER BY percentage DESC;\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$instrument",
   "type": "gauge",
   "description": "Average amount of time EPU or Tomo  acquisition is running ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH total AS (\n  SELECT\n    (SELECT EXTRACT(EPOCH FROM SUM(running_duration))\n     FROM epu_running_daily\n     WHERE instrument_id = $instrument\n       AND $__timeFilter(time)) AS total_epu_seconds,\n    (SELECT EXTRACT(EPOCH FROM SUM(running_duration))\n     FROM tomo_running_daily\n     WHERE instrument_id = $instrument\n       AND $__timeFilter(time)) AS total_tomo_seconds\n)\nSELECT\n  ROUND(COALESCE(total_epu_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS epu_utilization_percent,\n  ROUND(COALESCE(total_tomo_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS tomo_utilization_percent\nFROM total;\n"
    }
   ]
  },
  { "title": "Last cryo cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  p.param_name,\n  CURRENT_DATE - d.time::date AS days_since_cryocycle_start,\n  d.time AS cryo_start_time\nFROM parameters p\nJOIN LATERAL (\n  SELECT time\n  FROM data\n  WHERE instrument_id = $instrument\n    AND value_num <> 0\n    AND param_id = p.param_id\n  ORDER BY time DESC\n  LIMIT 1\n) d ON true\nWHERE p.instrument_id = $instrument\n  AND p.param_name IN ('AutoloaderCryoCycleDuration', 'ColumnCryoCycleDuration', 'CryoCycleDurationCLS', 'CryoCycleDurationMicroscope');\n"
    }
   ]
  },
  { "title": "Specimen throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Autogrid loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cartridge_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON i.id = lcd.instrument_id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  {
   "title": "Cassette loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cassette_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i \n  ON lcd.instrument_id = i.id\nWHERE lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  { "title": "Data throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Offloaded data per day",
   "type": "timeseries",
   "description": "Only for TFS cameras",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  dcd.day AS time,\n  i.name AS instrument,\n  SUM(dcd.daily_terabytes) AS value\nFROM data_counters_daily dcd\nJOIN instruments i \n  ON dcd.instrument_id = i.id\nWHERE dcd.instrument_id IN ($instrument)\n  AND $__timeFilter(dcd.day)\nGROUP BY dcd.day, i.name\nORDER BY dcd.day;\n"
    }
   ]
  },
  {
   "title": "Acquisitions per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  icd.day AS time,\n  i.name AS instrument,\n  SUM(icd.daily_images) AS value\nFROM image_counters_daily icd\nJOIN instruments i \n  ON icd.instrument_id = i.id\nWHERE icd.instrument_id IN ($instrument)\n  AND $__timeFilter(icd.day)\nGROUP BY icd.day, i.name\nORDER BY icd.day;\n"
    }
   ]
  }
 ]
}