{
 "title": "Fleet overview",
 "description": "General overview of all systems",
 "tags": [
  "overview",
  "tem"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Beam time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instrument",
   "type": "piechart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  state,\n  SUM(seconds) AS duration_seconds,\n  ROUND(100.0 * SUM(seconds) / NULLIF(SUM(SUM(seconds)) OVER (), 0), 2) AS percentage\nFROM vacuum_state_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\nGROUP BY state\nORDER BY percentage DESC;\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$instrument",
   "type": "gauge",
   "description": "Average amount of time EPU or Tomo  acquisition is running ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "-- Total EPU time\nWITH epu_sum AS (\n  SELECT\n    EXTRACT(EPOCH FROM SUM(running_duration)) AS total_epu_seconds\n  FROM epu_running_daily\n  WHERE instrument_id = $instrument\n    AND $__timeFilter(time)\n),\n\n-- Total Tomo time\ntomo_sum AS (\n  SELECT\n    EXTRACT(EPOCH FROM SUM(running_duration)) AS total_tomo_seconds\n  FROM tomo_running_daily\n  WHERE instrument_id = $instrument\n    AND $__timeFilter(time)\n)\n\n-- Final result\nSELECT\n  ROUND(COALESCE(e.total_epu_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS epu_utilization_percent,\n  ROUND(COALESCE(t.total_tomo_seconds, 0) / NULLIF(($__to - $__from) / 1000.0, 0) * 100.0, 2) AS tomo_utilization_percent\nFROM epu_sum e\nCROSS JOIN tomo_sum t;\n"
    }
   ]
  },
  { "title": "Last cryo cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT param_name, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument \n    AND param_name IN ('AutoloaderCryoCycleDuration', 'ColumnCryoCycleDuration')\n)\nSELECT\n  p.param_name,\n  CURRENT_DATE - d.time::date AS days_since_cryocycle_start,\n  d.time AS cryo_start_time\nFROM param_ids p\nJOIN LATERAL (\n  SELECT time\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = p.param_id\n    AND value_num <> 0\n  ORDER BY time DESC\n  LIMIT 1\n) d ON true"
    }
   ]
  },
  { "title": "Specimen throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Autogrid loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cartridge_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i ON i.id = lcd.instrument_id\nWHERE\n  lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  {
   "title": "Cassette loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cassette_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i ON lcd.instrument_id = i.id\nWHERE\n  lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  { "title": "Data throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Offloaded data per day",
   "type": "timeseries",
   "description": "Only for Falcon cameras",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  dcd.day AS time,\n  i.name AS instrument,\n  SUM(dcd.daily_terabytes) AS value\nFROM data_counters_daily dcd\nJOIN instruments i ON dcd.instrument_id = i.id\nWHERE\n  dcd.instrument_id IN ($instrument)\n  AND $__timeFilter(dcd.day)\nGROUP BY dcd.day, i.name\nORDER BY dcd.day;\n"
    }
   ]
  },
  {
   "title": "Acquisitions per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  icd.day AS time,\n  i.name AS instrument,\n  SUM(icd.daily_images) AS value\nFROM image_counters_daily icd\nJOIN instruments i ON icd.instrument_id = i.id\nWHERE\n  icd.instrument_id IN ($instrument)\n  AND $__timeFilter(icd.day)\nGROUP BY icd.day, i.name\nORDER BY icd.day;\n"
    }
   ]
  }
 ]
}