{
 "title": "Module | Source",
 "tags": [
  "module",
  "tem"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  { "title": "Gun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FEG Operate time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FegStates'\n    AND param_name = 'OperationTimeCounter'\n)\n\nSELECT d.value_num AS \"OperationTimeCounter\"\nFROM data d\nJOIN counter_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time) \nORDER BY d.time DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "FEG states",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FegStates'\n    AND param_name = 'FegState'\n    AND display_name = 'Feg State'\n),\n\nenums AS (\n  SELECT e.enum_id, e.member_name, e.value\n  FROM enum_values e\n  JOIN state_param p ON p.enum_id = e.enum_id\n)\n\nSELECT\n  e.member_name AS \"State\",\n  COUNT(*) AS \"Count\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nJOIN enums e ON e.enum_id = p.enum_id\n  AND e.value = d.value_num\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY e.member_name\nORDER BY \"Count\" DESC\n"
    }
   ]
  },
  {
   "title": "Emission current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'Emission'\n    AND param_name = 'EmissionCurrent'\n)\n\nSELECT\n  time,\n  value\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (SELECT param_id FROM matching_param)\n    AND $__timeFilter(time)\n))\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "SFEG/XFEG start counters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FegStates'\n    AND param_name IN ('ColdStartCount', 'WarmStartCount')\n)\n\nSELECT\n  p.param_name,\n  MAX(d.value_num) - MIN(d.value_num) AS count_diff\nFROM data d\nJOIN counter_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY p.param_name\nORDER BY p.param_name\n"
    }
   ]
  },
  {
   "title": "FEG vessel temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'TempElecVessel'\n    AND param_name = 'FegTemperature'\n)\nSELECT\n  time_bucket(INTERVAL '$__interval', d.time) AS time,\n  AVG(d.value_num) - 273.15 AS \"Average temperature\"\nFROM\n  data d\n  JOIN param_ids p ON p.param_id = d.param_id\nWHERE\n  d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "IGPf current",
   "type": "timeseries",
   "description": "For C-FEG it is always 0.0 uA",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component IN ('IGP3', 'IGPf')\n    AND param_name IN ('IGP3Current', 'IGPfCurrent')\n),\n\nhourly_avg AS (\n  SELECT\n    time_bucket('1h', d.time) AS hour,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n  GROUP BY hour, p.param_name\n)\n\nSELECT\n  hour AS time,\n  param_name,\n  avg_value AS \"1-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY hour\n    ROWS BETWEEN 23 PRECEDING AND CURRENT ROW\n  ) AS \"24-hour average\"\nFROM hourly_avg\nORDER BY hour, param_name;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component IN ('IGP3', 'IGPf')\n    AND param_name IN ('IGPfOnTime', 'IGPfLeadTime')\n),\n\nlast_values AS (\n  SELECT DISTINCT ON (d.param_id)\n    d.param_id,\n    d.value_num,\n    d.time\n  FROM data d\n  JOIN counter_param p ON p.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n  ORDER BY d.param_id, d.time DESC\n)\n\nSELECT\n  p.param_name,\n  l.value_num,\n  l.time\nFROM last_values l\nJOIN counter_param p ON p.param_id = l.param_id\n"
    }
   ]
  },
  {
   "title": "IGPa pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'IGPa'\n    AND param_name = 'IGPaPressure'\n),\n\nhourly_avg AS (\n  SELECT\n    time_bucket('1h', d.time) AS hour,\n    p.param_name,\n    AVG(d.value_num) AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n  GROUP BY hour, p.param_name\n)\n\nSELECT\n  hour AS time,\n  param_name,\n  avg_value AS \"1-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY hour\n    ROWS BETWEEN 23 PRECEDING AND CURRENT ROW\n  ) AS \"24-hour average\"\nFROM hourly_avg\nORDER BY hour, param_name;\n"
    }
   ]
  },
  {
   "title": "C-FEG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flash counters",
     "type": "table",
     "description": "High T flash occurs when the filament test line is > 2.7A",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "WITH param_ids AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Filament'\n    AND param_name = 'FilamentTestline'\n),\n\nfiltered_data AS (\n  SELECT\n    d.time,\n    d.value_num,\n    CASE WHEN d.value_num >= 1 THEN 1 ELSE 0 END AS is_on,\n    p.param_id\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n),\n\nsegmented AS (\n  SELECT *,\n         SUM(CASE WHEN is_on = 0 THEN 1 ELSE 0 END)\n           OVER (ORDER BY time) AS segment_id\n  FROM filtered_data\n),\n\nactive_segments AS (\n  SELECT segment_id,\n         MIN(time) AS start_time,\n         MAX(time) AS end_time,\n         EXTRACT(EPOCH FROM MAX(time) - MIN(time)) AS duration_sec,\n         CASE WHEN MAX(value_num) >= 2.7 THEN 'HighTFlash' ELSE 'LowTFlash' END AS flash_type\n  FROM segmented\n  WHERE is_on = 1\n  GROUP BY segment_id\n)\n\nSELECT\n  flash_type AS \"Flash type\",\n  COUNT(*) AS \"Count\",\n  SUM(duration_sec) AS \"Total duration\"\nFROM active_segments\nGROUP BY flash_type"
      }
     ]
    },
    {
     "title": "HighT flash threshold",
     "type": "stat",
     "description": "Threshold value which is used to distinguish the value of the\nfilament test line between a low or high flash",
     "gridPos": { "h": 5, "w": 3, "x": 7, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "SELECT 2.7 AS \"SpikeDistinctionValue\""
      }
     ]
    },
    {
     "title": "C-FEG High T flash count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 10, "y": 26 },
     "targets": [
      {
       "rawSql": "WITH counter_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'FegStates'\n    AND param_name = 'HighTFlashCount'\n)\n\nSELECT MAX(d.value_num)-MIN(d.value_num) AS \"HighTFlashCount\"\nFROM data d\nJOIN counter_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time) \n"
      }
     ]
    },
    {
     "title": "Avg time between flashes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "WITH param_ids AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Filament'\n    AND param_name = 'FilamentTestline'\n),\n\nvalue_changes AS (\n  SELECT\n    d.time,\n    d.value_num,\n    LAG(d.value_num) OVER (ORDER BY d.time) AS prev_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n),\n\nstart_events AS (\n  SELECT time\n  FROM value_changes\n  WHERE (prev_value IS NULL OR prev_value < 1) AND value_num >= 1\n  ORDER BY time\n),\n\nintervals AS (\n  SELECT\n    time,\n    LAG(time) OVER (ORDER BY time) AS prev_time\n  FROM start_events\n)\n\nSELECT\n  AVG(EXTRACT(EPOCH FROM (time - prev_time))) AS \"Avg time between flashes\"\nFROM intervals\nWHERE prev_time IS NOT NULL;\n"
      }
     ]
    },
    {
     "title": "Extractor V optimal vs set",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name, param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'Extractor'\n    AND param_name IN ('ExtractorOptimumVoltage', 'ExtractorUserSettings')\n)\nSELECT\n  d.time,\n  d.value_num,\n  p.param_name\nFROM\n  data d\n  JOIN param_ids p ON p.param_id = d.param_id\nWHERE\n  d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
      }
     ]
    },
    {
     "title": "Flash BCM ratio",
     "type": "timeseries",
     "description": "Ratio of beam current before flash / after flash",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "-- LowTFlashBcmRatio\nSELECT\n  time AS \"time\",\n  'LowTFlashBcmRatio' AS param_name,\n  value AS value_num\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (\n      SELECT param_id \n      FROM parameters \n      WHERE instrument_id = $instrument\n        AND component = 'FegStates'\n        AND param_name = 'LowTFlashBcmRatio'\n    )\n    AND $__timeFilter(time)\n))\n\nUNION ALL\n\n-- HighTFlashBcmRatio\nSELECT\n  time AS \"time\",\n  'HighTFlashBcmRatio' AS param_name,\n  value AS value_num\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (\n      SELECT param_id \n      FROM parameters \n      WHERE instrument_id = $instrument\n        AND component = 'FegStates'\n        AND param_name = 'HighTFlashBcmRatio'\n    )\n    AND $__timeFilter(time)\n))\nORDER BY time, param_name;\n"
      }
     ]
    },
    {
     "title": "Beam current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "WITH param_ids AS (\n  SELECT\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'BeamCurrent'\n    AND param_name = 'BeamCurrentStable'\n)\n\nSELECT\n  time,\n  value AS \"BeamCurrentStable\"\nFROM unnest((\n  SELECT lttb(\n    time,\n    value_num,\n    2 * (($__to - $__from) / $__interval_ms)::int\n  )\n  FROM data\n  WHERE instrument_id = $instrument\n    AND param_id = (\n      SELECT param_id \n      FROM param_ids\n    )\n    AND $__timeFilter(time)\n))\nORDER BY time\n"
      }
     ]
    }
   ]
  },
  { "title": "High Tension", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "HT tank state errors",
   "type": "stat",
   "description": "Count events when HT tank is not ON",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH state_param AS (\n  SELECT param_id, enum_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'HTTank'\n    AND param_name = 'HTTankState'\n),\n\nenum_on_value AS (\n  SELECT e.value\n  FROM enum_values e\n  JOIN state_param p ON e.enum_id = p.enum_id\n  WHERE e.member_name = 'On'\n  LIMIT 1\n)\n\nSELECT\n  COUNT(*) AS \"Error count\",\n  MAX(d.time) AS \"Latest error\"\nFROM data d\nJOIN state_param p ON d.param_id = p.param_id\nCROSS JOIN enum_on_value eo\nWHERE d.instrument_id = $instrument\n  AND d.value_num != eo.value\n  AND $__timeFilter(d.time)\n"
    }
   ]
  },
  {
   "title": "Interlocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH counter_param AS (\n  SELECT param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'HTTankInterlocks'\n),\n\nwith_changes AS (\n  SELECT\n    d.time,\n    d.value_num,\n    p.param_name,\n    LAG(d.value_num) OVER (PARTITION BY d.param_id ORDER BY d.time) AS prev_value\n  FROM data d\n  JOIN counter_param p ON p.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n)\n\nSELECT\n  param_name,\n  COUNT(*) AS interlock_count\nFROM with_changes\nWHERE value_num = 1 AND (prev_value IS DISTINCT FROM 1)\nGROUP BY param_name\nORDER BY param_name;\n"
    }
   ]
  },
  {
   "title": "SF6 pressure",
   "type": "timeseries",
   "description": "Nominal pressure is 4 bar",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'HTTank'\n    AND param_name = 'HTTankSF6Pressure'\n),\n\nhourly_avg AS (\n  SELECT\n    time_bucket('1h', d.time) AS hour,\n    p.param_name,\n    AVG(d.value_num)/100000.0 AS avg_value\n  FROM data d\n  JOIN param_ids p ON p.param_id = d.param_id\n  WHERE\n    d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n  GROUP BY hour, p.param_name\n)\n\nSELECT\n  hour AS time,\n  param_name,\n  avg_value AS \"1-hour average\",\n  AVG(avg_value) OVER (\n    PARTITION BY param_name\n    ORDER BY hour\n    ROWS BETWEEN 23 PRECEDING AND CURRENT ROW\n  ) AS \"24-hour average\"\nFROM hourly_avg\nORDER BY hour, param_name;\n"
    }
   ]
  },
  {
   "title": "Emission spikes",
   "type": "timeseries",
   "description": "Threshold is 6 uA",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT\n    param_name,\n    param_id\n  FROM\n    parameters\n  WHERE\n    instrument_id = $instrument\n    AND component = 'HTTank'\n    AND param_name IN ('HTTankEmissionCurrent', 'HTTankSettingVoltage')\n)\nSELECT\n  d.time,\n  d.value_num,\n  p.param_name\nFROM\n  data d\n  JOIN param_ids p ON p.param_id = d.param_id\nWHERE\n  d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
    }
   ]
  },
  {
   "title": "HT emission",
   "type": "stat",
   "description": "Latest value of HT Dark Current",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH emission_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'HTTank'\n    AND param_name = 'HTTankEmissionCurrent'\n)\n\nSELECT d.time, d.value_num AS \"HT emission\"\nFROM data d\nJOIN emission_param p ON p.param_id = d.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time) \nORDER BY d.time DESC\nLIMIT 1;\n"
    }
   ]
  }
 ]
}