{
 "title": "Module | SemiAutoloader",
 "tags": [
  "module",
  "tem"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" },
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is for Tundra only!"
   }
  },
  { "title": "Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CLS/Gate pressures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "WITH matching_params AS (\n  SELECT param_id, display_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_name IN ('PIRsucCLSPressure', 'PIRchGaugePressure', 'PPgGaugePressure', 'PIRsucGatePressure')\n    AND subsystem = 'SemiAutomatedLoader'\n    AND component = 'Gauges'\n)\n\n  SELECT\n   d.time,\n   d.value_num,\n   mp.display_name\n  FROM data d\n  JOIN matching_params mp ON mp.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
    }
   ]
  },
  {
   "title": "(Un)loading phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH matching_params AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_name IN ('LoadingPhase', 'UnloadingPhase')\n    AND subsystem = 'SemiAutomatedLoader'\n    AND component = 'Process'\n)\n\n  SELECT\n   time,\n   value_num AS phase\n  FROM data d\n  JOIN matching_params mp ON mp.param_id = d.param_id\n  WHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\nORDER BY d.time\n"
    }
   ]
  },
  { "title": "Mechanics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "TD pickup position deviation on CLS",
   "type": "gauge",
   "description": "Deviation of the last measurement from the median of the last 10 values. 11200 steps is 1mm",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "rawSql": "WITH motor_position AS (\n  SELECT p.param_id, ev.value AS pickup_value\n  FROM parameters p\n  JOIN enum_values ev ON ev.enum_id = p.enum_id\n  WHERE p.instrument_id = $instrument\n    AND p.component = 'Motors'\n    AND p.param_name = 'TDOnCLSMotorPosition'\n    AND ev.member_name = 'Pickup_Cooling'\n),\nencoder_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Motors'\n    AND param_name = 'MtdRawEncoderPosition'\n),\npickup_events AS (\n  SELECT d.time\n  FROM data d\n  JOIN motor_position mp ON d.param_id = mp.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num = mp.pickup_value\n),\nencoder_data AS (\n  SELECT d.time, d.value_num\n  FROM data d\n  JOIN encoder_param ep ON d.param_id = ep.param_id\n  WHERE $__timeFilter(d.time)\n),\nencoder_at_pickup AS (SELECT\n  e.time AS pickup_cooling_time,\n  ed.time AS encoder_time,\n  ed.value_num AS encoder_value\nFROM pickup_events e\nJOIN LATERAL (\n  SELECT ed.time, ed.value_num\n  FROM encoder_data ed\n  WHERE ed.time < e.time\n  ORDER BY ed.time DESC\n  LIMIT 1\n) ed ON TRUE\nORDER BY e.time DESC\nLIMIT 10\n),\nmedian_last_10 AS (\n  SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY encoder_value) AS encoder_median\n  FROM encoder_at_pickup\n),\nlast_pickup AS (\n  SELECT encoder_value AS last_encoder_value\n  FROM encoder_at_pickup\n  ORDER BY pickup_cooling_time DESC\n  LIMIT 1\n)\nSELECT\n  (last_pickup.last_encoder_value - median_last_10.encoder_median) AS deviation\nFROM last_pickup\nCROSS JOIN median_last_10;"
    }
   ]
  },
  {
   "title": "TD exchange position deviation on Gate",
   "type": "gauge",
   "description": "Deviation of the last measurement from the median of the last 10 values. 11200 steps is 1mm",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "rawSql": "WITH motor_position AS (\n  SELECT p.param_id, ev.value AS pickup_value\n  FROM parameters p\n  JOIN enum_values ev ON ev.enum_id = p.enum_id\n  WHERE p.instrument_id = $instrument\n    AND p.component = 'Motors'\n    AND p.param_name = 'TDOnTemGateMotorPosition'\n    AND ev.member_name = 'Exchange'\n),\nencoder_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Motors'\n    AND param_name = 'MtdRawEncoderPosition'\n),\npickup_events AS (\n  SELECT d.time\n  FROM data d\n  JOIN motor_position mp ON d.param_id = mp.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n    AND d.value_num = mp.pickup_value\n),\nencoder_data AS (\n  SELECT d.time, d.value_num\n  FROM data d\n  JOIN encoder_param ep ON d.param_id = ep.param_id\n  WHERE $__timeFilter(d.time)\n),\nencoder_at_pickup AS (SELECT\n  e.time AS pickup_cooling_time,\n  ed.time AS encoder_time,\n  ed.value_num AS encoder_value\nFROM pickup_events e\nJOIN LATERAL (\n  SELECT ed.time, ed.value_num\n  FROM encoder_data ed\n  WHERE ed.time < e.time\n  ORDER BY ed.time DESC\n  LIMIT 1\n) ed ON TRUE\nORDER BY e.time DESC\nLIMIT 10\n),\nmedian_last_10 AS (\n  SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY encoder_value) AS encoder_median\n  FROM encoder_at_pickup\n),\nlast_pickup AS (\n  SELECT encoder_value AS last_encoder_value\n  FROM encoder_at_pickup\n  ORDER BY pickup_cooling_time DESC\n  LIMIT 1\n)\nSELECT\n  (last_pickup.last_encoder_value - median_last_10.encoder_median) AS deviation\nFROM last_pickup\nCROSS JOIN median_last_10;"
    }
   ]
  },
  {
   "title": "Motor errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH error_param AS (\n  SELECT p.param_id, ev.value AS error_value\n  FROM parameters p\n  JOIN enum_values ev ON ev.enum_id = p.enum_id\n  WHERE p.instrument_id = $instrument\n    AND p.component = 'Motors'\n    AND p.param_name = 'MtdState'\n    AND ev.member_name = 'Error'\n)\n\nSELECT COUNT(*) AS mtd_errors\nFROM data d\nJOIN error_param ep ON d.param_id = ep.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\n  AND d.value_num = ep.error_value;\n"
    },
    {
     "rawSql": "WITH error_param AS (\n  SELECT p.param_id, ev.value AS error_value\n  FROM parameters p\n  JOIN enum_values ev ON ev.enum_id = p.enum_id\n  WHERE p.instrument_id = $instrument\n    AND p.component = 'Motors'\n    AND p.param_name = 'McstState'\n    AND ev.member_name = 'Error'\n)\n\nSELECT COUNT(*) AS mcst_errors\nFROM data d\nJOIN error_param ep ON d.param_id = ep.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\n  AND d.value_num = ep.error_value;\n"
    }
   ]
  },
  { "title": "Temperatures and LN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "WITH matching_params AS (\n  SELECT param_id, display_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Thermometer'\n    AND param_name IN ('T_gripperTemperature', 'T_clbarTemperature', 'T_ColDewarTemperature')\n)\n\nSELECT\n  time_bucket(INTERVAL '$__interval', d.time) AS time,\n  p.display_name,\n  AVG(d.value_num) AS temperature\nFROM data d\nJOIN matching_params p\n  ON d.param_id = p.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\n  AND d.value_num != 0\nGROUP BY time, p.display_name\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Temperature mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT\n    param_name,\n    param_id\n  FROM\n    parameters p\n  WHERE\n    instrument_id = $instrument\n    AND param_name IN ('CompartmentStateCLS', 'CompartmentStateMicroscope')\n)\nSELECT\n  v.time,\n  p.param_name,\n  v.value_num\nFROM\n  data v\n  JOIN matching_param p ON v.param_id = p.param_id\nWHERE\n  instrument_id = $instrument\n  AND $__timeFilter(v.time)\nORDER BY\n  v.time"
    }
   ]
  },
  {
   "title": "Loading station pot LN level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'LN2Sensors'\n    AND param_name = 'LN2LevelGateState'\n)\n\n  SELECT\n    d.time,\n    d.value_num AS level\n  FROM data d\n  JOIN matching_param p ON d.param_id = p.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n"
    }
   ]
  },
  {
   "title": "Temperature outliers",
   "type": "stat",
   "description": "Count any temperature outliers <70K or above 310K",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH matching_params AS (\n  SELECT param_id, param_name\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Thermometer'\n    AND param_name IN ('T_gripperTemperature', 'T_clbarTemperature', 'T_ColDewarTemperature')\n)\n\nSELECT\n  COUNT(*) AS \"Count\",\n  MAX(d.time) AS \"Last outlier\"\nFROM data d\nJOIN matching_params p ON d.param_id = p.param_id\nWHERE d.instrument_id = $instrument\n  AND $__timeFilter(d.time)\n  AND (d.value_num < 70 OR d.value_num > 310);\n"
    }
   ]
  },
  {
   "title": "Avg CLS cryo cycle duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Process'\n    AND param_name = 'CryoCycleDurationCLS'\n),\n\nvalue_data AS (\n  SELECT\n    d.time,\n    d.value_num,\n    LAG(d.value_num) OVER (ORDER BY d.time) AS prev_value\n  FROM data d\n  JOIN matching_param p ON d.param_id = p.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n),\n\nresets AS (\n  SELECT time, prev_value\n  FROM value_data\n  WHERE value_num = 0\n    AND prev_value IS NOT NULL\n    AND prev_value > 0\n)\n\nSELECT AVG(prev_value) AS avg_max_before_reset\nFROM resets;\n"
    }
   ]
  },
  {
   "title": "Avg column cryo cycle duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'Process'\n    AND param_name = 'CryoCycleDurationMicroscope'\n),\n\nvalue_data AS (\n  SELECT\n    d.time,\n    d.value_num,\n    LAG(d.value_num) OVER (ORDER BY d.time) AS prev_value\n  FROM data d\n  JOIN matching_param p ON d.param_id = p.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n),\n\nresets AS (\n  SELECT time, prev_value\n  FROM value_data\n  WHERE value_num = 0\n    AND prev_value IS NOT NULL\n    AND prev_value > 0\n)\n\nSELECT AVG(prev_value) AS avg_max_before_reset\nFROM resets;\n"
    }
   ]
  },
  {
   "title": "Sample loads since last cryo cycle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT param_name, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_name = 'CryoCycleDurationMicroscope'\n),\n\nlast_cryo AS (\n  SELECT\n    p.param_name,\n    d.time AS cryo_end_time\n  FROM param_ids p\n  JOIN LATERAL (\n    SELECT time\n    FROM data\n    WHERE instrument_id = $instrument\n      AND param_id = p.param_id\n      AND value_num <> 0\n    ORDER BY time DESC\n    LIMIT 1\n  ) d ON true\n),\n\ncassette_counter_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_name = 'SampleTransferCount'\n),\n\nbaseline AS (\n  SELECT d.value_num AS baseline_val\n  FROM data d\n  JOIN cassette_counter_param ccp ON d.param_id = ccp.param_id\n  JOIN last_cryo lc ON true\n  WHERE d.instrument_id = $instrument\n    AND d.time <= lc.cryo_end_time\n  ORDER BY d.time DESC\n  LIMIT 1\n),\n\nafter_cryo AS (\n  SELECT MAX(d.value_num) AS max_val\n  FROM data d\n  JOIN cassette_counter_param ccp ON d.param_id = ccp.param_id\n  JOIN last_cryo lc ON true\n  WHERE d.instrument_id = $instrument\n    AND d.time >= lc.cryo_end_time\n)\n\nSELECT\n  COALESCE(a.max_val, b.baseline_val) - COALESCE(b.baseline_val, 0) AS sample_loads_since_cryocycle\nFROM baseline b\nCROSS JOIN after_cryo a;\n"
    }
   ]
  },
  {
   "title": "Column dewar LN level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "WITH matching_param AS (\n  SELECT param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND component = 'LN2Sensor'\n    AND param_name = 'SensorState'\n)\n\n  SELECT\n    d.time,\n    d.value_num AS level\n  FROM data d\n  JOIN matching_param p ON d.param_id = p.param_id\n  WHERE d.instrument_id = $instrument\n    AND $__timeFilter(d.time)\n"
    }
   ]
  }
 ]
}