{
 "title": "Fleet overview",
 "description": "General overview of all systems",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nORDER BY name;\n"
   },
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Beam time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instrument",
   "type": "piechart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  state,\n  SUM(seconds) AS duration_seconds,\n  ROUND(100.0 * SUM(seconds) / NULLIF(SUM(SUM(seconds)) OVER (), 0), 2) AS percentage\nFROM vacuum_state_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\nGROUP BY state\nORDER BY percentage DESC;\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$instrument",
   "type": "gauge",
   "description": "Average amount of time EPU or Tomo  acquisition is running ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "-- Total EPU time\nWITH epu_sum AS (\n  SELECT\n    SUM(running_duration) AS total_epu\n  FROM epu_acquisition_daily\n  WHERE instrument_id = $instrument\n    AND $__timeFilter(time)\n),\n\n-- Total Tomo time\ntomo_sum AS (\n  SELECT\n    SUM(running_duration) AS total_tomo\n  FROM tomo_acquisition_daily\n  WHERE instrument_id = $instrument\n    AND $__timeFilter(time)\n),\n\n-- Day count in range (inclusive)\ndate_range AS (\n  SELECT\n    (DATE_TRUNC('day', to_timestamp($__to / 1000.0)::timestamptz)::date -\n     DATE_TRUNC('day', to_timestamp($__from / 1000.0)::timestamptz)::date + 1\n    ) AS num_days\n)\n\n-- Final result\nSELECT\n  ROUND(COALESCE(e.total_epu, 0) / (d.num_days * 86400.0) * 100.0, 2) AS epu_utilization_percent,\n  ROUND(COALESCE(t.total_tomo, 0) / (d.num_days * 86400.0) * 100.0, 2) AS tomo_utilization_percent\nFROM epu_sum e, tomo_sum t, date_range d\n"
    }
   ]
  },
  { "title": "Last cryo cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$instrument",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "repeat": "instrument",
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "WITH param_ids AS (\n  SELECT param_name, param_id\n  FROM parameters\n  WHERE instrument_id = $instrument\n    AND param_name IN ('AutoloaderCryoCycleDuration', 'ColumnCryoCycleDuration')\n),\nzero_start AS (\n  SELECT\n    p.param_name,\n    d.time AS cryo_start_time\n  FROM param_ids p\n  JOIN LATERAL (\n    SELECT time\n    FROM (\n      SELECT\n        time,\n        value_num,\n        LAG(value_num) OVER (ORDER BY time) AS prev_value\n      FROM data\n      WHERE instrument_id = $instrument\n        AND param_id = p.param_id\n    ) sub\n    WHERE value_num = 0 AND prev_value IS DISTINCT FROM 0\n    ORDER BY time DESC\n    LIMIT 1\n  ) d ON true\n)\n\nSELECT\n  param_name,\n  CURRENT_DATE - cryo_start_time::date AS days_since_cryocycle_start,\n  cryo_start_time\nFROM zero_start"
    }
   ]
  },
  { "title": "Specimen throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Autogrid loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cartridge_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i ON i.id = lcd.instrument_id\nWHERE\n  lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  {
   "title": "Cassette loads per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  lcd.day AS time,\n  i.name AS instrument,\n  lcd.daily_cassette_count AS value\nFROM load_counters_daily lcd\nJOIN instruments i ON lcd.instrument_id = i.id\nWHERE\n  lcd.instrument_id IN ($instrument)\n  AND $__timeFilter(lcd.day)\nORDER BY lcd.day;\n"
    }
   ]
  },
  { "title": "Data throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Offloaded data per day",
   "type": "timeseries",
   "description": "Only for Falcon cameras",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  dcd.day AS time,\n  i.name AS instrument,\n  SUM(dcd.daily_terabytes) AS value\nFROM data_counters_daily dcd\nJOIN instruments i ON dcd.instrument_id = i.id\nWHERE\n  dcd.instrument_id IN ($instrument)\n  AND $__timeFilter(dcd.day)\nGROUP BY dcd.day, i.name\nORDER BY dcd.day;\n"
    }
   ]
  },
  {
   "title": "Acquisitions per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  icd.day AS time,\n  i.name AS instrument,\n  SUM(icd.daily_images) AS value\nFROM image_counters_daily icd\nJOIN instruments i ON icd.instrument_id = i.id\nWHERE\n  icd.instrument_id IN ($instrument)\n  AND $__timeFilter(icd.day)\nGROUP BY icd.day, i.name\nORDER BY icd.day;\n"
    }
   ]
  }
 ]
}