{
 "title": "Productivity",
 "tags": [
  "overview",
  "tem"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": "SELECT\n  id AS __value,\n  name || ' [' || model || '] (' || serial || ')' AS __text\nFROM instruments\nWHERE is_active IS TRUE\nORDER BY name;\n"
   },
   { "name": "sourceTEM", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Autoloader counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(daily_cartridge_count) AS \"cartridges/day\",\n  SUM(daily_cartridge_count) AS \"total cartridges\",\n  AVG(daily_cassette_count) AS \"cassettes/day\",\n  SUM(daily_cassette_count) AS \"total cassettes\"\nFROM load_counters_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\n"
    }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "stat",
   "description": "Acquisitions are counted for both TFS and Gatan cameras. Data volume is only available for TFS cameras",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(AVG(daily_images)) AS \"images/day\",\n  SUM(daily_images) AS \"total images\"\nFROM image_counters_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\n"
    },
    {
     "rawSql": "SELECT\n  AVG(daily_terabytes) AS \"data/day\",\n  SUM(daily_terabytes) AS \"total data\"\nFROM data_counters_daily\nWHERE $__timeFilter(day)\n  AND instrument_id = $instrument\n"
    }
   ]
  },
  {
   "title": "EPU counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(ec.total_image_counter) AS total_images,\n  ROUND(AVG(ec.total_image_counter)) AS avg_images_per_session,\n  COALESCE(EXTRACT(EPOCH FROM SUM(er.running_duration)), 0) AS total_running_duration,\n  SUM(ec.skip_image_counter) AS total_skipped_images,\n\n  -- terminated counts\n  SUM(CASE WHEN er.has_terminated = TRUE  THEN 1 ELSE 0 END) AS terminated_count,\n  SUM(CASE WHEN er.has_terminated = FALSE THEN 1 ELSE 0 END) AS completed_count\n\nFROM epu_counters ec\nJOIN epu_sessions es\n  ON es.session_id = ec.session_id\n  AND es.start_time = ec.start_time\nJOIN epu_runs er\n  ON er.session_id = ec.session_id\n  AND er.start_time = ec.start_time\n\nWHERE ec.instrument_id = $instrument\n  AND es.instrument_id = $instrument\n  AND er.instrument_id = $instrument\n  AND $__timeFilter(es.start_time)"
    }
   ]
  },
  {
   "title": "EPU-D counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS total_runs,\n  COALESCE(EXTRACT(EPOCH FROM SUM(total_duration)), 0) AS total_duration\nFROM epud_runs\nWHERE instrument_id = $instrument\n  AND $__timeFilter(start_time)"
    }
   ]
  },
  {
   "title": "Tomo counters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(ec.total_ts_counter) AS total_ts,\n  ROUND(AVG(ec.total_ts_counter)) AS avg_ts_per_session,\n  COALESCE(EXTRACT(EPOCH FROM SUM(er.running_duration)), 0) AS total_running_duration,\n  SUM(ec.total_sm_counter) AS total_sm,\n  \n  -- terminated counts\n  SUM(CASE WHEN er.has_terminated = TRUE  THEN 1 ELSE 0 END) AS terminated_count,\n  SUM(CASE WHEN er.has_terminated = FALSE THEN 1 ELSE 0 END) AS completed_count\n\nFROM tomo_counters ec\nJOIN tomo_sessions es\n  ON es.session_id = ec.session_id\n  AND es.start_time = ec.start_time\nJOIN tomo_runs er\n  ON er.session_id = ec.session_id\n  AND er.start_time = ec.start_time\nWHERE ec.instrument_id = $instrument\n  AND es.instrument_id = $instrument\n  AND er.instrument_id = $instrument\n  AND $__timeFilter(es.start_time)\n"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "barchart",
   "description": "Amount of time EPU or Tomo acquisition is running per day",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH all_durations AS (\n  SELECT\n    time::date AS day,\n    'epu' AS source,\n    EXTRACT(EPOCH FROM running_duration) AS running_seconds\n  FROM epu_running_daily\n  WHERE $__timeFilter(time)\n    AND instrument_id = $instrument\n\n  UNION ALL\n\n  SELECT\n    time::date AS day,\n    'tomo' AS source,\n    EXTRACT(EPOCH FROM running_duration) AS running_seconds\n  FROM tomo_running_daily\n  WHERE $__timeFilter(time)\n    AND instrument_id = $instrument\n),\n\ndays AS (\n  SELECT generate_series(\n    $__timeFrom()::date,\n    $__timeTo()::date,\n    interval '1 day'\n  ) AS day\n)\n\nSELECT\n  d.day AS time,\n  ROUND(100.0 * COALESCE(SUM(CASE WHEN ad.source = 'epu' THEN ad.running_seconds END), 0) / 86400.0, 2) AS \"EPU\",\n  ROUND(100.0 * COALESCE(SUM(CASE WHEN ad.source = 'tomo' THEN ad.running_seconds END), 0) / 86400.0, 2) AS \"Tomo\"\nFROM days d\nLEFT JOIN all_durations ad ON ad.day = d.day\nGROUP BY d.day\nORDER BY d.day;\n"
    }
   ]
  },
  {
   "title": "Beam time",
   "type": "barchart",
   "description": "Beam time is based on the vacuum state of each instrument",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH daily_totals AS (\n  SELECT\n    day,\n    SUM(seconds) AS total_seconds\n  FROM vacuum_state_daily\n  WHERE $__timeFilter(day)\n    AND instrument_id = $instrument\n  GROUP BY day\n)\nSELECT\n  v.day AS \"time\",\n  v.state,\n  100.0 * SUM(v.seconds) / NULLIF(t.total_seconds, 0) AS percentage\nFROM vacuum_state_daily v\nJOIN daily_totals t\n  ON v.day = t.day\nWHERE $__timeFilter(v.day)\n  AND v.instrument_id = $instrument\nGROUP BY v.day, v.state, t.total_seconds\nORDER BY v.day, v.state;\n"
    }
   ]
  },
  {
   "title": "EPU acquisition speed",
   "type": "barchart",
   "description": "Running duration is the actual automated acquisition run",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  ec.session_id AS \"SessionID\",\n  es.start_time AS \"Start time\",\n  es.end_time AS \"End time\",\n  er.running_duration AS \"Running duration\",\n  ec.total_image_counter AS \"Total images\",\n  ec.skip_image_counter AS \"Skipped images\",\n  CASE \n    WHEN EXTRACT(EPOCH FROM er.running_duration) > 0 THEN\n      ec.total_image_counter / (EXTRACT(EPOCH FROM er.running_duration) / 3600)\n    ELSE NULL\n  END AS \"Images/hour\",\n  er.has_terminated AS \"Terminated\"\nFROM epu_counters ec\nJOIN epu_sessions es\n  ON es.session_id = ec.session_id\n  AND es.start_time = ec.start_time\nJOIN epu_runs er\n  ON er.session_id = ec.session_id\n  AND er.start_time = ec.start_time\nWHERE ec.instrument_id = $instrument\n  AND es.instrument_id = $instrument\n  AND er.instrument_id = $instrument\n  AND $__timeFilter(es.start_time)\nORDER BY es.start_time;\n"
    }
   ]
  },
  {
   "title": "Tomo acquisition speed",
   "type": "barchart",
   "description": "Running duration is the actual automated acquisition run",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  ec.session_id AS \"SessionID\",\n  es.start_time AS \"Start time\",\n  es.end_time AS \"End time\",\n  er.running_duration AS \"Running duration\",\n  ec.total_image_counter AS \"Total images\",\n  ec.total_ts_counter AS \"Tilt series\",\n  CASE \n    WHEN EXTRACT(EPOCH FROM er.running_duration) > 0 THEN\n      ec.total_image_counter / (EXTRACT(EPOCH FROM er.running_duration) / 3600)\n    ELSE NULL\n  END AS \"Images/hour\",\n  CASE \n    WHEN EXTRACT(EPOCH FROM er.running_duration) > 0 THEN\n      ec.total_ts_counter / (EXTRACT(EPOCH FROM er.running_duration) / 3600)\n    ELSE NULL\n  END AS \"TS/hour\",  \n  ec.total_sm_counter AS \"Search maps\",\n  er.has_terminated AS \"Terminated\"\nFROM tomo_counters ec\nJOIN tomo_sessions es\n  ON es.session_id = ec.session_id\n  AND es.start_time = ec.start_time\nJOIN tomo_runs er\n  ON er.session_id = ec.session_id\n  AND er.start_time = ec.start_time\nWHERE ec.instrument_id = $instrument\n  AND es.instrument_id = $instrument\n  AND er.instrument_id = $instrument\n  AND $__timeFilter(es.start_time)\nORDER BY es.start_time;\n"
    }
   ]
  }
 ]
}