apiVersion: 1

# See https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/

muteTimes:
    - orgId: 1
      name: weekends
      time_intervals:
        - weekdays: [saturday, sunday]
    - orgId: 1
      name: weekdays_daytime
      time_intervals:
        - times:
            - start_time: "08:00"
              end_time: "24:00"
          weekdays: [ friday, thursday, wednesday, tuesday, monday ]
    - orgId: 1
      name: weekdays_nighttime
      time_intervals:
        - times:
            - start_time: "00:00"
              end_time: "08:00"
          weekdays: [ friday, thursday, wednesday, tuesday, monday ]

contactPoints:
    - orgId: 1
      name: email-contact-point
      receivers:
      - uid: email_uid
        type: email
        disableResolveMessage: true
        settings:
          addresses: $GRAFANA_EMAIL_TO
          singleEmail: true
          subject: |
            {{ template "custom_email.subject" . }}
          message: |
            {{ template "custom_email.message" . }}

deleteContactPoints:
    - orgId: 1
      uid: ""

policies:
    - orgId: 1
      receiver: email-contact-point
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: email-contact-point
          # Critical alerts are fired immediately
          object_matchers:
            - - severity
              - =
              - critical
          group_wait: 1s
          group_interval: 1s
          repeat_interval: 5m
        - receiver: email-contact-point
          # Warnings and muted on weekends
          object_matchers:
            - - severity
              - =
              - warning
          mute_time_intervals:
            - weekends
        - object_matchers: # Cautions are muted forever, no emails
            - - severity
              - =
              - caution
          mute_time_intervals:
            - weekdays_daytime
            - weekends
            - weekdays_nighttime
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h


templates:
    - orgId: 1
      name: custom_email.subject
      template: |
        {{ define "custom_email.subject" }}
          {{- $multiple := gt (len .Alerts) 1 -}}
          {{- $instr := "" -}}
          {{- if $multiple -}}
            {{- $instr = "Multiple instruments" -}}
          {{- else -}}
            {{- $instr = (index .Alerts 0).Labels.instrument -}}
          {{- end -}}
        
          {{- $status := "ALERT" -}}
          {{- if eq .Status "resolved" -}}
            {{- $status = "RESOLVED" -}}
          {{- end -}}
        
          {{- trimSpace (printf "[%s] %s - %s" $status $instr (index .Alerts 0).Annotations.summary) -}}
        {{ end }}

    - orgId: 1
      name: custom_email.message
      template: |
        {{ define "custom_email.message" }}
          Alerts: {{ len .Alerts.Firing }} firing, {{ len .Alerts.Resolved }} resolved

          {{ range .Alerts }}
          {{- $statusIcon := "" -}}
          {{- if eq .Labels.severity "critical" -}}
            {{ $statusIcon = "🔴 CRITICAL" }}
          {{- else if eq .Labels.severity "warning" -}}
            {{ $statusIcon = "🟠 WARNING" }}
          {{- else if eq .Labels.severity "caution" -}}
            {{ $statusIcon = "🟡 CAUTION" }}
          {{- else -}}
            {{ $statusIcon = "⚪ UNKNOWN" }}
          {{- end -}}
          ALERT DETAILS
          ----------------
          Date/Time: {{ .StartsAt }}
          Status: {{ .Status }}
          Instrument:  {{ .Labels.grafana_folder }} / {{ .Labels.instrument }}
          Module: {{ .Labels.module }}
          Severity: {{ $statusIcon }}

          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}

          View Alert: {{ .GeneratorURL }}
          {{ if gt (len .DashboardURL) 0 }}View Dashboard: ({{ .DashboardURL }}){{ end }}
          Silence: {{ .SilenceURL }}
          ============================================================
          {{ end }}
        {{ end }}
