apiVersion: 1
groups:
    - orgId: 1
      name: Module offline
      folder: TEM
      interval: 5m
      rules:
        - uid: bewyqwb2l2neof
          title: Energy filter off
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: hm-tem
              model:
                editorMode: code
                format: time_series
                intervalMs: 1.8e+06
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |
                    WITH target_param AS (
                      SELECT p.param_id, i.name, i.id
                      FROM parameters p
                      JOIN instruments i ON i.id = p.instrument_id
                      WHERE subsystem = 'EnergyFilterBrick'
                        AND param_name = 'EnergyFilterIsAvailable'
                    )
                    SELECT
                        d.time AS "time",
                        t.name AS "instrument",
                        'EnergyFilter' AS "module",
                        d.value_num AS "value"
                    FROM data d
                    JOIN target_param t
                      ON d.param_id = t.param_id
                      AND d.instrument_id = t.id
                    ORDER BY d.time ASC
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: reducer
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: reducer
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: reducer
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          annotations:
            summary: Energy filter offline
            description: The energy filter is not available for this instrument. Please check system status.
          labels:
            module: EF
            severity: critical
          notification_settings:
            receiver: email-contact-point
