-- Creating events.instruments
CREATE TABLE IF NOT EXISTS events.instruments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  current_config_id BIGINT,
  serial INTEGER NOT NULL UNIQUE,
  server INET CONSTRAINT ipv4 CHECK (family(server) = 4 AND masklen(server) = 32),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  instrument TEXT NOT NULL UNIQUE,
  model TEXT NOT NULL,
  name TEXT NOT NULL,
  template TEXT NOT NULL,
  ds_version TEXT
);

COMMENT ON TABLE events.instruments IS 'Main instruments table';

-- Creating events.configirations
CREATE TABLE IF NOT EXISTS events.configurations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  config_hash BYTEA NOT NULL,
  config_dict JSONB NOT NULL,
  CONSTRAINT configurations_instr_id_key UNIQUE (instrument_id, id),
  CONSTRAINT configurations_instr_hash_key UNIQUE (instrument_id, config_hash)
);

COMMENT ON TABLE events.configurations IS 'HM IntEnums configurations';
COMMENT ON CONSTRAINT configurations_instr_hash_key
  ON events.configurations IS 'Two instruments can have the same config hash/dict';

-- Creating events.enum_types
CREATE TABLE IF NOT EXISTS events.enum_types (
  enum_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  name TEXT NOT NULL,
  CONSTRAINT enum_types_instr_enumid_pkey PRIMARY KEY (instrument_id, enum_id),
  CONSTRAINT enum_types_instr_enumname_key UNIQUE (instrument_id, name)
);

COMMENT ON TABLE events.enum_types IS 'Current HM IntEnum definitions';
COMMENT ON CONSTRAINT enum_types_instr_enumname_key
  ON events.enum_types IS 'Each instrument has its own set of enum types, but two instruments can have different enums with the same name';

-- Creating events.enum_values
CREATE TABLE IF NOT EXISTS events.enum_values (
  instrument_id BIGINT NOT NULL,
  enum_id BIGINT NOT NULL,
  value INTEGER NOT NULL,
  member_name TEXT NOT NULL,
  CONSTRAINT enum_values_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
    REFERENCES events.enum_types (instrument_id, enum_id) ON DELETE CASCADE,
  CONSTRAINT enum_values_names_key UNIQUE (instrument_id, enum_id, member_name),
  CONSTRAINT enum_values_values_key UNIQUE (instrument_id, enum_id, value)
);

COMMENT ON TABLE events.enum_values IS 'Current HM IntEnum members for each instrument';
COMMENT ON CONSTRAINT enum_values_instr_enum_fkey
  ON events.enum_values IS 'enum_id are scoped per instrument';
COMMENT ON CONSTRAINT enum_values_names_key
  ON events.enum_values IS 'Each enum is required to have unique member names';
COMMENT ON CONSTRAINT enum_values_values_key
  ON events.enum_values IS 'Each enum is required to have unique member values';

-- Creating events.parameters
CREATE TABLE IF NOT EXISTS events.parameters (
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  config_id BIGINT NOT NULL REFERENCES events.configurations(id),
  enum_id BIGINT,
  event_id INTEGER NOT NULL,
  abs_limits NUMRANGE,
  subsystem TEXT NOT NULL,
  component TEXT NOT NULL,
  param_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  display_unit TEXT,
  storage_unit TEXT,
  value_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT parameters_instr_param_key UNIQUE (instrument_id, param_id),
  CONSTRAINT parameters_instr_config_fkey FOREIGN KEY (instrument_id, config_id)
    REFERENCES events.configurations (instrument_id, id),
  CONSTRAINT parameters_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
    REFERENCES events.enum_types (instrument_id, enum_id),
  CONSTRAINT parameters_value_type_check CHECK (value_type IN ('int', 'float', 'str', 'bool'))
);

COMMENT ON TABLE events.parameters IS 'HM parameters metadata';
COMMENT ON CONSTRAINT parameters_instr_param_key
  ON events.parameters IS 'param_id is unique per instrument';

-- Creating events.parameters_history
CREATE TABLE IF NOT EXISTS events.parameters_history (
  inserted timestamptz NOT NULL DEFAULT NOW(),
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  config_id BIGINT NOT NULL REFERENCES events.configurations(id),
  enum_id BIGINT,
  event_id INTEGER NOT NULL,
  abs_limits NUMRANGE,
  subsystem TEXT NOT NULL,
  component TEXT NOT NULL,
  param_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  display_unit TEXT,
  storage_unit TEXT,
  value_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  CONSTRAINT parameters_history_instr_param_time_key UNIQUE (instrument_id, param_id, inserted),
  CONSTRAINT parameters_history_instr_config_fkey FOREIGN KEY (instrument_id, config_id)
    REFERENCES events.configurations (instrument_id, id),
  CONSTRAINT parameters_history_instr_enum_fkey FOREIGN KEY (instrument_id, enum_id)
    REFERENCES events.enum_types (instrument_id, enum_id)
);

COMMENT ON TABLE events.parameters_history IS 'Historical HM metadata for each parameter';

-- Creating events.data_staging
CREATE UNLOGGED TABLE IF NOT EXISTS events.data_staging (
  time timestamptz NOT NULL,
  instrument_id BIGINT NOT NULL,
  param_id BIGINT NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT
);

COMMENT ON TABLE events.data_staging IS 'Staging table for bulk COPY inserts';

-- Creating events.data
CREATE TABLE IF NOT EXISTS events.data (
  time timestamptz NOT NULL,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT,
  UNIQUE (instrument_id, param_id, time),
  FOREIGN KEY (instrument_id, param_id) REFERENCES events.parameters (instrument_id, param_id)
)
WITH (
  tsdb.hypertable,
  tsdb.chunk_interval = :var_data_chunk_size,
  tsdb.partition_column = 'time',
  tsdb.create_default_indexes = FALSE,
  tsdb.segmentby = 'instrument_id',
  tsdb.orderby = 'param_id, time DESC'
  );

COMMENT ON TABLE events.data IS 'Main time series table with HM events';

SELECT enable_chunk_skipping('events.data', 'param_id');
