-- instruments table ------------------------------------------------------------------------------
-- Creating events.configirations
CREATE TABLE IF NOT EXISTS events.configurations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  valid_from TIMESTAMPTZ NOT NULL,
  config_hash BYTEA NOT NULL,
  config_dict JSONB NOT NULL,
  UNIQUE (instrument_id, valid_from),
  UNIQUE (instrument_id, config_hash)
);

COMMENT ON TABLE events.instruments IS 'HM IntEnums configurations';

-- Creating events.instruments
CREATE TABLE IF NOT EXISTS events.instruments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  current_config_id BIGINT REFERENCES events.configurations(id),
  serial INTEGER NOT NULL UNIQUE,
  server INET CONSTRAINT ipv4 CHECK (family(server) = 4 AND masklen(server) = 32),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  instrument TEXT NOT NULL UNIQUE,
  model TEXT NOT NULL,
  name TEXT NOT NULL,
  template TEXT NOT NULL,
  ds_version TEXT
);

COMMENT ON TABLE events.instruments IS 'Main instruments table';


-- enumeration tables --
-- Creating events.enum_types
CREATE TABLE IF NOT EXISTS events.enum_types (
  id BIGINT NOT NULL,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  name TEXT NOT NULL,
  PRIMARY KEY (instrument_id, id),
  UNIQUE (instrument_id, name)
);

COMMENT ON TABLE events.enum_types IS 'HM IntEnum names. Each instrument has its own set of enum types';

-- Creating events.enum_values
CREATE TABLE IF NOT EXISTS events.enum_values (
  instrument_id BIGINT NOT NULL,
  enum_id BIGINT NOT NULL,
  value INTEGER NOT NULL,
  member_name TEXT NOT NULL,
  FOREIGN KEY (instrument_id, enum_id) REFERENCES events.enum_types (instrument_id, id),
  UNIQUE (instrument_id, enum_id, member_name),
  UNIQUE (instrument_id, enum_id, value)
);

COMMENT ON TABLE events.enum_values IS 'HM IntEnum values for each enumeration';

-- parameter tables -------------------------------------------------------------------------------
-- Creating events.parameters
CREATE TABLE IF NOT EXISTS events.parameters (
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  config_id BIGINT NOT NULL REFERENCES events.configurations(id),
  enum_id BIGINT,
  abs_min DOUBLE PRECISION,
  abs_max DOUBLE PRECISION,
  event_id INTEGER NOT NULL,
  subsystem TEXT NOT NULL,
  component TEXT NOT NULL,
  param_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  display_unit TEXT,
  storage_unit TEXT,
  value_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  FOREIGN KEY (instrument_id, enum_id) REFERENCES events.enum_types (instrument_id, id) ON DELETE SET NULL (enum_id),
  UNIQUE (instrument_id, param_id),
  CHECK (abs_min <= abs_max),
  CHECK (value_type IN ('int', 'float', 'str', 'bool'))
);

COMMENT ON TABLE events.parameters IS 'HM parameters metadata. param_id is unique per instrument. Multiple parameters can refer to the same enum type';

-- Creating events.parameters_history
CREATE TABLE IF NOT EXISTS events.parameters_history (
  inserted timestamptz NOT NULL DEFAULT NOW(),
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  config_id BIGINT NOT NULL REFERENCES events.configurations(id),
  enum_id BIGINT,
  abs_min DOUBLE PRECISION,
  abs_max DOUBLE PRECISION,
  event_id INTEGER NOT NULL,
  subsystem TEXT NOT NULL,
  component TEXT NOT NULL,
  param_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  display_unit TEXT,
  storage_unit TEXT,
  value_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  UNIQUE (instrument_id, param_id, inserted),
  CHECK (abs_min <= abs_max),
  CHECK (value_type IN ('int', 'float', 'str', 'bool'))
);

COMMENT ON TABLE events.parameters_history IS 'Historical HM metadata for each parameter';


-- data tables ------------------------------------------------------------------------------------
-- Creating events.data
CREATE UNLOGGED TABLE IF NOT EXISTS events.data_staging (
  time timestamptz NOT NULL,
  instrument_id BIGINT NOT NULL,
  param_id BIGINT NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT
);

COMMENT ON TABLE events.data_staging IS 'Staging table for bulk COPY inserts';

CREATE TABLE IF NOT EXISTS events.data (
  time timestamptz NOT NULL,
  instrument_id BIGINT NOT NULL REFERENCES events.instruments (id),
  param_id BIGINT NOT NULL,
  value_num DOUBLE PRECISION,
  value_text TEXT,
  UNIQUE (instrument_id, param_id, time),
  FOREIGN KEY (instrument_id, param_id) REFERENCES events.parameters (instrument_id, param_id)
)
WITH (
  tsdb.hypertable,
  tsdb.chunk_interval = :var_data_chunk_size,
  tsdb.partition_column = 'time',
  tsdb.create_default_indexes = FALSE,
  tsdb.segmentby = 'instrument_id',
  tsdb.orderby = 'param_id, time DESC'
  );

COMMENT ON TABLE events.data IS 'Main time series table with HM events';

SELECT enable_chunk_skipping('events.data', 'param_id');
