-- instruments table ------------------------------------------------------------------------------
-- Creating events.instruments
CREATE TABLE IF NOT EXISTS events.instruments (
                                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  instrument TEXT NOT NULL UNIQUE,
                                                  serial INTEGER NOT NULL UNIQUE,
                                                  model TEXT NOT NULL,
                                                  name TEXT NOT NULL,
                                                  template TEXT NOT NULL,
                                                  server INET,
                                                  ds_version TEXT,
                                                  is_active BOOLEAN NOT NULL DEFAULT true
);
COMMENT ON TABLE events.instruments IS 'Main instruments table';


-- enumeration tables --
-- Creating events.enum_types
CREATE TABLE IF NOT EXISTS events.enum_types (
                                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 instrument_id INTEGER NOT NULL REFERENCES events.instruments(id) ON DELETE CASCADE,
                                                 name TEXT NOT NULL,
                                                 UNIQUE (id, instrument_id),
                                                 UNIQUE (instrument_id, name)
);
COMMENT ON TABLE events.enum_types IS 'HM IntEnum names. Each instrument has its own set of enum types';

-- Creating events.enum_values
CREATE TABLE IF NOT EXISTS events.enum_values (
                                    enum_id INTEGER NOT NULL REFERENCES events.enum_types(id) ON DELETE CASCADE,
                                    member_name TEXT NOT NULL,
                                    value INTEGER NOT NULL,
                                    UNIQUE (enum_id, member_name),
                                    UNIQUE (enum_id, value)
);
COMMENT ON TABLE events.enum_values IS 'HM IntEnum values for each enumeration';

-- Creating events.enum_values_history
CREATE TABLE IF NOT EXISTS events.enum_values_history (
                                            enum_id INTEGER NOT NULL REFERENCES events.enum_types(id) ON DELETE CASCADE,
                                            inserted TIMESTAMPTZ NOT NULL DEFAULT now(),
                                            member_name TEXT NOT NULL,
                                            value INTEGER NOT NULL
);
COMMENT ON TABLE events.enum_values_history IS 'Historical HM IntEnum values for each enumeration';


-- parameter tables -------------------------------------------------------------------------------
-- Creating events.parameters
CREATE TABLE IF NOT EXISTS events.parameters (
                                                 instrument_id INTEGER NOT NULL REFERENCES events.instruments(id) ON DELETE CASCADE,
                                                 param_id INTEGER NOT NULL,
                                                 subsystem TEXT NOT NULL,
                                                 component TEXT NOT NULL,
                                                 param_name TEXT NOT NULL,
                                                 display_name TEXT NOT NULL,
                                                 display_unit TEXT,
                                                 storage_unit TEXT,
                                                 enum_id INTEGER,
                                                 FOREIGN KEY (enum_id, instrument_id)
                                                     REFERENCES events.enum_types (id, instrument_id)
                                                     ON DELETE SET NULL (enum_id),
                                                 value_type TEXT NOT NULL,
                                                 event_id INTEGER NOT NULL,
                                                 event_name TEXT NOT NULL,
                                                 abs_min DOUBLE PRECISION,
                                                 abs_max DOUBLE PRECISION,
                                                 UNIQUE (instrument_id, param_id)
);
COMMENT ON TABLE events.parameters IS 'HM parameters metadata. param_id is unique per instrument. Multiple parameters can refer to the same enum type';

-- Creating events.parameters_history
CREATE TABLE IF NOT EXISTS events.parameters_history (
                                                         instrument_id INTEGER NOT NULL REFERENCES events.instruments(id) ON DELETE CASCADE,
                                                         inserted TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                         param_id INTEGER NOT NULL,
                                                         subsystem TEXT NOT NULL,
                                                         component TEXT NOT NULL,
                                                         param_name TEXT NOT NULL,
                                                         display_name TEXT NOT NULL,
                                                         display_unit TEXT,
                                                         storage_unit TEXT,
                                                         enum_id INTEGER,
                                                         FOREIGN KEY (enum_id, instrument_id)
                                                             REFERENCES events.enum_types (id, instrument_id)
                                                             ON DELETE SET NULL (enum_id),
                                                         value_type TEXT NOT NULL,
                                                         event_id INTEGER NOT NULL,
                                                         event_name TEXT NOT NULL,
                                                         abs_min DOUBLE PRECISION,
                                                         abs_max DOUBLE PRECISION,
                                                         UNIQUE (instrument_id, param_id, inserted)
);
COMMENT ON TABLE events.parameters_history IS 'Historical HM metadata for each parameter';


-- data table -------------------------------------------------------------------------------------
-- Creating events.data
CREATE UNLOGGED TABLE IF NOT EXISTS events.data_staging (
                                                            time TIMESTAMPTZ NOT NULL,
                                                            instrument_id INTEGER NOT NULL,
                                                            param_id INTEGER NOT NULL,
                                                            value_num DOUBLE PRECISION,
                                                            value_text TEXT
);
COMMENT ON TABLE events.data_staging IS 'Staging table for bulk COPY inserts';

CREATE TABLE IF NOT EXISTS events.data (
                                           time TIMESTAMPTZ NOT NULL,
                                           instrument_id INTEGER NOT NULL REFERENCES events.instruments(id) ON DELETE CASCADE,
                                           param_id INTEGER NOT NULL,
                                           value_num DOUBLE PRECISION,
                                           value_text TEXT,
                                           UNIQUE (param_id, instrument_id, time)
                                           -- To define an index as a UNIQUE or PRIMARY KEY index, the index must include the time column and the partitioning column
) WITH (
                                             tsdb.hypertable,
                                             tsdb.chunk_interval=:var_data_chunk_size,
                                             tsdb.partition_column='time',
                                             tsdb.create_default_indexes=false,
                                             tsdb.segmentby='instrument_id',
                                             tsdb.orderby='time DESC'
                                             );
COMMENT ON TABLE events.data IS 'Main time series table with HM events';

SELECT enable_chunk_skipping('events.data', 'param_id');
